####################################################################################################
#                                                                                                  #
#   generated by dconstruct ver. 1.52.0                                                            #
#   listing for file: game_dumps/t2r/dc1/ss-finding-nora\ss-nor-infiltrate-traverse-igc-vent-enter.bin#
#   filesize: 6561 bytes                                                                           #
#   total entries: 1                                                                               #
#   functions: 15                                                                                  #
#   has state script: true                                                                         #
#   game type: t2r                                                                                 #
#   optimizations enabled: true                                                                    #
#                                                                                                  #
####################################################################################################



##############################  ENTRY 0  ##############################

ss-nor-infiltrate-traverse-igc-vent-enter = state-script [0x00048] {
  OPTIONS: 
    [0x0004A8]     player
    STATE task-check {
      ON start {
        TRACK main {
          {
            0000   0x0016A0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-complete?>
            0001   0x0016A8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x0016B0   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-traverse-to-nora>
            0003   0x0016B8   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0004   0x0016C0   43 32 02 00   Move                 r50, r2       r50 = nor-traverse-to-nora
            0005   0x0016C8   1B 00 00 02   Call                 r0, r0, 2     r0 = task-complete?(find-nora, nor-traverse-to-nora)
            0006   0x0016D0   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 => L_RETURN_0
            0007   0x0016D8   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x0016E0   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <complete>
            0009   0x0016E8   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x0016F0   43 31 01 00   Move                 r49, r1       r49 = complete
            000B   0x0016F8   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x001700   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            000D   0x001708   2D 0F 00 00   Branch               0xF           GOTO => L_RETURN
          L_RETURN_0:
            000E   0x001710   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            000F   0x001718   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001720    function: task-complete?
            0001   0x001728    sid: find-nora
            0002   0x001730    sid: nor-traverse-to-nora
            0003   0x001738    function: go
            0004   0x001740    sid: complete
          }
          {
            0000   0x001308   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-active?>
            0001   0x001310   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x001318   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-traverse-to-nora>
            0003   0x001320   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0004   0x001328   43 32 02 00   Move                 r50, r2       r50 = nor-traverse-to-nora
            0005   0x001330   1B 00 00 02   Call                 r0, r0, 2     r0 = task-active?(find-nora, nor-traverse-to-nora)
            0006   0x001338   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 => L_RETURN_0
            0007   0x001340   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x001348   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <wait-igc>
            0009   0x001350   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x001358   43 31 01 00   Move                 r49, r1       r49 = wait-igc
            000B   0x001360   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x001368   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(wait-igc, 1)
            000D   0x001370   2D 0F 00 00   Branch               0xF           GOTO => L_RETURN
          L_RETURN_0:
            000E   0x001378   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            000F   0x001380   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001388    function: task-active?
            0001   0x001390    sid: find-nora
            0002   0x001398    sid: nor-traverse-to-nora
            0003   0x0013A0    function: go
            0004   0x0013A8    sid: wait-igc
          }
        }

      }
      ON event task-complete {
        TRACK main {
          {
            0000   0x001308   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-active?>
            0001   0x001310   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x001318   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-traverse-to-nora>
            0003   0x001320   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0004   0x001328   43 32 02 00   Move                 r50, r2       r50 = nor-traverse-to-nora
            0005   0x001330   1B 00 00 02   Call                 r0, r0, 2     r0 = task-active?(find-nora, nor-traverse-to-nora)
            0006   0x001338   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 => L_RETURN_0
            0007   0x001340   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x001348   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <wait-igc>
            0009   0x001350   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x001358   43 31 01 00   Move                 r49, r1       r49 = wait-igc
            000B   0x001360   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x001368   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(wait-igc, 1)
            000D   0x001370   2D 0F 00 00   Branch               0xF           GOTO => L_RETURN
          L_RETURN_0:
            000E   0x001378   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            000F   0x001380   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001388    function: task-active?
            0001   0x001390    sid: find-nora
            0002   0x001398    sid: nor-traverse-to-nora
            0003   0x0013A0    function: go
            0004   0x0013A8    sid: wait-igc
          }
        }

      }
    } END STATE task-check

    STATE wait-igc {
      ON event trigger-vent-enter {
        TRACK main {
          {
            0000   0x001278   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <holster-player-weapon>
            0001   0x001280   0C 01 02 00   LoadU16Imm           r1, 2         r1 = 2
            0002   0x001288   40 02 01 00   LoadStaticFloatImm   r2, 1         r2 = ST[1] -> <1.000000>
            0003   0x001290   43 31 01 00   Move                 r49, r1       r49 = 2
            0004   0x001298   43 32 02 00   Move                 r50, r2       r50 = 1.000000
            0005   0x0012A0   1C 00 00 02   CallFf               r0, r0, 2     r0 = holster-player-weapon(2, 1.000000)
            0006   0x0012A8   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0012B0    function: holster-player-weapon
            0001   0x0012B8    float: 1.000000
          }
          {
            0000   0x001228   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <send-event>
            0001   0x001230   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <player-in-vent>
            0002   0x001238   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <ss-nor-traverse-vent-igc-packing-npc-1>
            0003   0x001240   43 31 01 00   Move                 r49, r1       r49 = player-in-vent
            0004   0x001248   43 32 02 00   Move                 r50, r2       r50 = ss-nor-traverse-vent-igc-packing-npc-1
            0005   0x001250   1C 00 00 02   CallFf               r0, r0, 2     r0 = send-event(player-in-vent, ss-nor-traverse-vent-igc-packing-npc-1)
            0006   0x001258   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001260    function: send-event
            0001   0x001268    sid: player-in-vent
            0002   0x001270    sid: ss-nor-traverse-vent-igc-packing-npc-1
          }
        }

      }
      ON event holster-player-weapon {
        TRACK main {
          {
            0000   0x000B20   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <holster-player-weapon>
            0001   0x000B28   0C 01 00 00   LoadU16Imm           r1, 0         r1 = 0
            0002   0x000B30   40 02 01 00   LoadStaticFloatImm   r2, 1         r2 = ST[1] -> <1.000000>
            0003   0x000B38   43 31 01 00   Move                 r49, r1       r49 = 0
            0004   0x000B40   43 32 02 00   Move                 r50, r2       r50 = 1.000000
            0005   0x000B48   1C 00 00 02   CallFf               r0, r0, 2     r0 = holster-player-weapon(0, 1.000000)
            0006   0x000B50   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x000B58    function: holster-player-weapon
            0001   0x000B60    float: 1.000000
          }
        }

      }
      ON event task-complete {
        TRACK main {
          {
            0000   0x001748   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x001750   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <complete>
            0002   0x001758   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001760   43 31 01 00   Move                 r49, r1       r49 = complete
            0004   0x001768   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x001770   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            0006   0x001778   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001780    function: go
            0001   0x001788    sid: complete
          }
        }

      }
    } END STATE wait-igc

    STATE vent-enter {
      ON start {
        TRACK main {
          {
            0000   0x0013B0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-player-move-to-entry>
            0001   0x0013B8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <nor-infiltrate-hospital-vent-enter--ellie>
            0002   0x0013C0   15 02 02 00   LookupPointer        r2, 2         r2 = ST[2] -> <get-spawner-locator>
            0003   0x0013C8   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <ap-nor-infiltrate-traverse-vent-exit-1>
            0004   0x0013D0   0C 04 01 00   LoadU16Imm           r4, 1         r4 = 1
            0005   0x0013D8   43 31 03 00   Move                 r49, r3       r49 = ap-nor-infiltrate-traverse-vent-exit-1
            0006   0x0013E0   43 32 04 00   Move                 r50, r4       r50 = 1
            0007   0x0013E8   1C 02 02 02   CallFf               r2, r2, 2     r2 = get-spawner-locator(ap-nor-infiltrate-traverse-vent-exit-1, 1)
            0008   0x0013F0   0C 03 01 00   LoadU16Imm           r3, 1         r3 = 1
            0009   0x0013F8   0C 04 00 00   LoadU16Imm           r4, 0         r4 = 0
            000A   0x001400   40 05 04 00   LoadStaticFloatImm   r5, 4         r5 = ST[4] -> <0.400000>
            000B   0x001408   4A 06 05 00   LoadStaticU64Imm     r6, 5         r6 = ST[5] -> <apReference-camera1>
            000C   0x001410   4A 07 06 00   LoadStaticU64Imm     r7, 6         r7 = ST[6] -> <apReference>
            000D   0x001418   40 08 07 00   LoadStaticFloatImm   r8, 7         r8 = ST[7] -> <0.000000>
            000E   0x001420   0C 09 00 00   LoadU16Imm           r9, 0         r9 = 0
            000F   0x001428   0C 0A 01 00   LoadU16Imm           r10, 1        r10 = 1
            0010   0x001430   0C 0B 00 00   LoadU16Imm           r11, 0        r11 = 0
            0011   0x001438   0C 0C 01 00   LoadU16Imm           r12, 1        r12 = 1
            0012   0x001440   40 0D 07 00   LoadStaticFloatImm   r13, 7        r13 = ST[7] -> <0.000000>
            0013   0x001448   0C 0E 00 00   LoadU16Imm           r14, 0        r14 = 0
            0014   0x001450   0C 0F 01 00   LoadU16Imm           r15, 1        r15 = 1
            0015   0x001458   43 31 01 00   Move                 r49, r1       r49 = nor-infiltrate-hospital-vent-enter--ellie
            0016   0x001460   43 32 02 00   Move                 r50, r2       r50 = RET_get-spawner-locator
            0017   0x001468   43 33 03 00   Move                 r51, r3       r51 = 1
            0018   0x001470   43 34 04 00   Move                 r52, r4       r52 = 0
            0019   0x001478   43 35 05 00   Move                 r53, r5       r53 = 0.400000
            001A   0x001480   43 36 06 00   Move                 r54, r6       r54 = apReference-camera1
            001B   0x001488   43 37 07 00   Move                 r55, r7       r55 = apReference
            001C   0x001490   43 38 08 00   Move                 r56, r8       r56 = 0.000000
            001D   0x001498   43 39 09 00   Move                 r57, r9       r57 = 0
            001E   0x0014A0   43 3A 0A 00   Move                 r58, r10      r58 = 1
            001F   0x0014A8   43 3B 0B 00   Move                 r59, r11      r59 = 0
            0020   0x0014B0   43 3C 0C 00   Move                 r60, r12      r60 = 1
            0021   0x0014B8   43 3D 0D 00   Move                 r61, r13      r61 = 0.000000
            0022   0x0014C0   43 3E 0E 00   Move                 r62, r14      r62 = 0
            0023   0x0014C8   43 3F 0F 00   Move                 r63, r15      r63 = 1
            0024   0x0014D0   1B 00 00 0F   Call                 r0, r0, 15    r0 = wait-player-move-to-entry(nor-infiltrate-hospital-vent-enter--ellie, RET_get-spawner-locator, 1, 0, 0.400000, apReference-camera1, apReference, 0.000000, 0, 1, 0, 1, 0.000000, 0, 1)
            0025   0x0014D8   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0014E0    function: wait-player-move-to-entry
            0001   0x0014E8    sid: nor-infiltrate-hospital-vent-enter--ellie
            0002   0x0014F0    function: get-spawner-locator
            0003   0x0014F8    sid: ap-nor-infiltrate-traverse-vent-exit-1
            0004   0x001500    float: 0.400000
            0005   0x001508    sid: apReference-camera1
            0006   0x001510    sid: apReference
            0007   0x001518    float: 0.000000
          }
          {
            0000   0x0015B8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <camera-enable-animated>
            0001   0x0015C0   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <1.500000>
            0002   0x0015C8   40 02 02 00   LoadStaticFloatImm   r2, 2         r2 = ST[2] -> <-1.000000>
            0003   0x0015D0   0C 03 01 00   LoadU16Imm           r3, 1         r3 = 1
            0004   0x0015D8   0C 04 E8 03   LoadU16Imm           r4, 1000      r4 = 1000
            0005   0x0015E0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0006   0x0015E8   0C 06 00 00   LoadU16Imm           r6, 0         r6 = 0
            0007   0x0015F0   0C 07 00 00   LoadU16Imm           r7, 0         r7 = 0
            0008   0x0015F8   43 31 01 00   Move                 r49, r1       r49 = 1.500000
            0009   0x001600   43 32 02 00   Move                 r50, r2       r50 = -1.000000
            000A   0x001608   43 33 03 00   Move                 r51, r3       r51 = 1
            000B   0x001610   43 34 04 00   Move                 r52, r4       r52 = 1000
            000C   0x001618   43 35 05 00   Move                 r53, r5       r53 = 0
            000D   0x001620   43 36 06 00   Move                 r54, r6       r54 = 0
            000E   0x001628   43 37 07 00   Move                 r55, r7       r55 = 0
            000F   0x001630   1C 00 00 07   CallFf               r0, r0, 7     r0 = camera-enable-animated(1.500000, -1.000000, 1, 1000, 0, 0, 0)
            0010   0x001638   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001640    function: camera-enable-animated
            0001   0x001648    float: 1.500000
            0002   0x001650    float: -1.000000
          }
          {
            0000   0x0012C0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <turn-off-flashlight>
            0001   0x0012C8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <player>
            0002   0x0012D0   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0003   0x0012D8   43 31 01 00   Move                 r49, r1       r49 = player
            0004   0x0012E0   43 32 02 00   Move                 r50, r2       r50 = 0
            0005   0x0012E8   1B 00 00 02   Call                 r0, r0, 2     r0 = turn-off-flashlight(player, 0)
            0006   0x0012F0   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0012F8    function: turn-off-flashlight
            0001   0x001300    sid: player
          }
          {
            0000   0x001520   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <send-event>
            0001   0x001528   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <player-entered-vent>
            0002   0x001530   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <ss-nor-traverse-igc-militia-and-nora-conversation-1>
            0003   0x001538   43 31 01 00   Move                 r49, r1       r49 = player-entered-vent
            0004   0x001540   43 32 02 00   Move                 r50, r2       r50 = ss-nor-traverse-igc-militia-and-nora-conversation-1
            0005   0x001548   1C 00 00 02   CallFf               r0, r0, 2     r0 = send-event(player-entered-vent, ss-nor-traverse-igc-militia-and-nora-conversation-1)
            0006   0x001550   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001558    function: send-event
            0001   0x001560    sid: player-entered-vent
            0002   0x001568    sid: ss-nor-traverse-igc-militia-and-nora-conversation-1
          }
          {
            0000   0x000B68   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-animate_>
            0001   0x000B70   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <player>
            0002   0x000B78   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-infiltrate-hospital-vent-enter--ellie>
            0003   0x000B80   15 03 03 00   LookupPointer        r3, 3         r3 = ST[3] -> <#%alloc-array>
            0004   0x000B88   4A 04 04 00   LoadStaticU64Imm     r4, 4         r4 = ST[4] -> <single-frame>
            0005   0x000B90   0C 05 10 00   LoadU16Imm           r5, 16        r5 = 16
            0006   0x000B98   0C 06 07 00   LoadU16Imm           r6, 7         r6 = 7
            0007   0x000BA0   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0008   0x000BA8   43 31 04 00   Move                 r49, r4       r49 = single-frame
            0009   0x000BB0   43 32 05 00   Move                 r50, r5       r50 = 16
            000A   0x000BB8   43 33 06 00   Move                 r51, r6       r51 = 7
            000B   0x000BC0   43 34 07 00   Move                 r52, r7       r52 = 1
            000C   0x000BC8   1C 03 03 04   CallFf               r3, r3, 4     r3 = #%alloc-array(single-frame, 16, 7, 1)
            000D   0x000BD0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            000E   0x000BD8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            000F   0x000BE0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0010   0x000BE8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0011   0x000BF0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0012   0x000BF8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0013   0x000C00   0C 05 0A 00   LoadU16Imm           r5, 10        r5 = 10
            0014   0x000C08   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 65535] = 10
            0015   0x000C10   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0016   0x000C18   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0017   0x000C20   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0018   0x000C28   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0019   0x000C30   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            001A   0x000C38   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            001B   0x000C40   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            001C   0x000C48   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            001D   0x000C50   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = 0
            001E   0x000C58   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            001F   0x000C60   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0020   0x000C68   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0021   0x000C70   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0022   0x000C78   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0023   0x000C80   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0024   0x000C88   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            0025   0x000C90   15 05 05 00   LookupPointer        r5, 5         r5 = ST[5] -> <get-spawner-locator>
            0026   0x000C98   4A 06 06 00   LoadStaticU64Imm     r6, 6         r6 = ST[6] -> <ap-nor-infiltrate-traverse-vent-exit-1>
            0027   0x000CA0   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0028   0x000CA8   43 31 06 00   Move                 r49, r6       r49 = ap-nor-infiltrate-traverse-vent-exit-1
            0029   0x000CB0   43 32 07 00   Move                 r50, r7       r50 = 1
            002A   0x000CB8   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-spawner-locator(ap-nor-infiltrate-traverse-vent-exit-1, 1)
            002B   0x000CC0   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = RET_get-spawner-locator
            002C   0x000CC8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            002D   0x000CD0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            002E   0x000CD8   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            002F   0x000CE0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0030   0x000CE8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0031   0x000CF0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0032   0x000CF8   0C 05 1C 00   LoadU16Imm           r5, 28        r5 = 28
            0033   0x000D00   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 28
            0034   0x000D08   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0035   0x000D10   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0036   0x000D18   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0037   0x000D20   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0038   0x000D28   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0039   0x000D30   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003A   0x000D38   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            003B   0x000D40   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            003C   0x000D48   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            003D   0x000D50   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            003E   0x000D58   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003F   0x000D60   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0040   0x000D68   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0041   0x000D70   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0042   0x000D78   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0043   0x000D80   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0044   0x000D88   40 05 07 00   LoadStaticFloatImm   r5, 7         r5 = ST[7] -> <0.200000>
            0045   0x000D90   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 0.200000
            0046   0x000D98   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0047   0x000DA0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0048   0x000DA8   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0049   0x000DB0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            004A   0x000DB8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            004B   0x000DC0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            004C   0x000DC8   0C 05 1E 00   LoadU16Imm           r5, 30        r5 = 30
            004D   0x000DD0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 30
            004E   0x000DD8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            004F   0x000DE0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0050   0x000DE8   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0051   0x000DF0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0052   0x000DF8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            0053   0x000E00   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0054   0x000E08   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0055   0x000E10   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0056   0x000E18   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            0057   0x000E20   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0058   0x000E28   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0059   0x000E30   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            005A   0x000E38   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            005B   0x000E40   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            005C   0x000E48   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            005D   0x000E50   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            005E   0x000E58   40 05 08 00   LoadStaticFloatImm   r5, 8         r5 = ST[8] -> <0.500000>
            005F   0x000E60   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 0.500000
            0060   0x000E68   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0061   0x000E70   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0062   0x000E78   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            0063   0x000E80   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0064   0x000E88   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            0065   0x000E90   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0066   0x000E98   0C 05 3D 00   LoadU16Imm           r5, 61        r5 = 61
            0067   0x000EA0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 61
            0068   0x000EA8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0069   0x000EB0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006A   0x000EB8   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            006B   0x000EC0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            006C   0x000EC8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            006D   0x000ED0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006E   0x000ED8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            006F   0x000EE0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0070   0x000EE8   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            0071   0x000EF0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0072   0x000EF8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0073   0x000F00   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            0074   0x000F08   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0075   0x000F10   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            0076   0x000F18   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0077   0x000F20   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0078   0x000F28   0C 05 82 00   LoadU16Imm           r5, 130       r5 = 130
            0079   0x000F30   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 8] = 130
            007A   0x000F38   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            007B   0x000F40   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            007C   0x000F48   0C 05 04 00   LoadU16Imm           r5, 4         r5 = 4
            007D   0x000F50   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            007E   0x000F58   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 4
            007F   0x000F60   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0080   0x000F68   0C 05 3C 00   LoadU16Imm           r5, 60        r5 = 60
            0081   0x000F70   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 60
            0082   0x000F78   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0083   0x000F80   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0084   0x000F88   0C 05 04 00   LoadU16Imm           r5, 4         r5 = 4
            0085   0x000F90   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0086   0x000F98   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 4
            0087   0x000FA0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0088   0x000FA8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0089   0x000FB0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            008A   0x000FB8   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            008B   0x000FC0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            008C   0x000FC8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            008D   0x000FD0   0C 05 04 00   LoadU16Imm           r5, 4         r5 = 4
            008E   0x000FD8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            008F   0x000FE0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 4
            0090   0x000FE8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0091   0x000FF0   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0092   0x000FF8   40 05 08 00   LoadStaticFloatImm   r5, 8         r5 = ST[8] -> <0.500000>
            0093   0x001000   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 0.500000
            0094   0x001008   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0095   0x001010   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0096   0x001018   0C 05 05 00   LoadU16Imm           r5, 5         r5 = 5
            0097   0x001020   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0098   0x001028   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 5
            0099   0x001030   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            009A   0x001038   0C 05 18 00   LoadU16Imm           r5, 24        r5 = 24
            009B   0x001040   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 24
            009C   0x001048   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            009D   0x001050   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            009E   0x001058   0C 05 05 00   LoadU16Imm           r5, 5         r5 = 5
            009F   0x001060   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            00A0   0x001068   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 5
            00A1   0x001070   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            00A2   0x001078   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            00A3   0x001080   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            00A4   0x001088   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            00A5   0x001090   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            00A6   0x001098   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            00A7   0x0010A0   0C 05 05 00   LoadU16Imm           r5, 5         r5 = 5
            00A8   0x0010A8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            00A9   0x0010B0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 5
            00AA   0x0010B8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            00AB   0x0010C0   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            00AC   0x0010C8   0C 05 06 00   LoadU16Imm           r5, 6         r5 = 6
            00AD   0x0010D0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 8] = 6
            00AE   0x0010D8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            00AF   0x0010E0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            00B0   0x0010E8   0C 05 06 00   LoadU16Imm           r5, 6         r5 = 6
            00B1   0x0010F0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            00B2   0x0010F8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 6
            00B3   0x001100   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            00B4   0x001108   0C 05 46 00   LoadU16Imm           r5, 70        r5 = 70
            00B5   0x001110   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 70
            00B6   0x001118   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            00B7   0x001120   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            00B8   0x001128   0C 05 06 00   LoadU16Imm           r5, 6         r5 = 6
            00B9   0x001130   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            00BA   0x001138   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 6
            00BB   0x001140   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            00BC   0x001148   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            00BD   0x001150   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            00BE   0x001158   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            00BF   0x001160   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            00C0   0x001168   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            00C1   0x001170   0C 05 06 00   LoadU16Imm           r5, 6         r5 = 6
            00C2   0x001178   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            00C3   0x001180   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 6
            00C4   0x001188   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            00C5   0x001190   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            00C6   0x001198   0C 05 0C 00   LoadU16Imm           r5, 12        r5 = 12
            00C7   0x0011A0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 8] = 12
            00C8   0x0011A8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            00C9   0x0011B0   43 03 04 00   Move                 r3, r4        r3 = RET_#%alloc-array
            00CA   0x0011B8   43 31 01 00   Move                 r49, r1       r49 = player
            00CB   0x0011C0   43 32 02 00   Move                 r50, r2       r50 = nor-infiltrate-hospital-vent-enter--ellie
            00CC   0x0011C8   43 33 03 00   Move                 r51, r3       r51 = RET_#%alloc-array
            00CD   0x0011D0   1C 00 00 03   CallFf               r0, r0, 3     r0 = wait-animate_(player, nor-infiltrate-hospital-vent-enter--ellie, RET_#%alloc-array)
            00CE   0x0011D8   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0011E0    function: wait-animate_
            0001   0x0011E8    sid: player
            0002   0x0011F0    sid: nor-infiltrate-hospital-vent-enter--ellie
            0003   0x0011F8    function: #%alloc-array
            0004   0x001200    sid: single-frame
            0005   0x001208    function: get-spawner-locator
            0006   0x001210    sid: ap-nor-infiltrate-traverse-vent-exit-1
            0007   0x001218    float: 0.200000
            0008   0x001220    float: 0.500000
          }
          {
            0000   0x001658   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <camera-fade-out-animated>
            0001   0x001660   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <1.500000>
            0002   0x001668   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0003   0x001670   43 31 01 00   Move                 r49, r1       r49 = 1.500000
            0004   0x001678   43 32 02 00   Move                 r50, r2       r50 = 0
            0005   0x001680   1B 00 00 02   Call                 r0, r0, 2     r0 = camera-fade-out-animated(1.500000, 0)
            0006   0x001688   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001690    function: camera-fade-out-animated
            0001   0x001698    float: 1.500000
          }
          {
            0000   0x001570   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x001578   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <wait-igc>
            0002   0x001580   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001588   43 31 01 00   Move                 r49, r1       r49 = wait-igc
            0004   0x001590   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x001598   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(wait-igc, 1)
            0006   0x0015A0   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0015A8    function: go
            0001   0x0015B0    sid: wait-igc
          }
        }

      }
      ON event task-complete {
        TRACK main {
          {
            0000   0x001748   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x001750   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <complete>
            0002   0x001758   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001760   43 31 01 00   Move                 r49, r1       r49 = complete
            0004   0x001768   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x001770   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            0006   0x001778   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001780    function: go
            0001   0x001788    sid: complete
          }
        }

      }
    } END STATE vent-enter

    STATE complete {
    } END STATE complete

}
