#pragma once

#include "expression.h"
#include "binary_expressions/add.h"
#include "binary_expressions/sub.h"
#include "binary_expressions/mul.h"
#include "binary_expressions/div.h"
#include "binary_expressions/mod.h"
#include "assign.h"
#include "binary_expressions/compare.h"
#include "binary_expressions/logical.h"
#include "cast.h"
#include "binary_expressions/bitwise_and.h"
#include "binary_expressions/bitwise_or.h"
#include "binary_expressions/bitwise_xor.h"
#include "binary_expressions/shift.h"
#include "unary_expressions/logical_not_expression.h"
#include "unary_expressions/bitwise_not_expression.h"
#include "unary_expressions/negate_expression.h"
#include "unary_expressions/dereference_expression.h"
#include "unary_expressions/post_arithmetic.h"
#include "primary_expressions/call.h"
#include "primary_expressions/grouping.h"
#include "primary_expressions/literal.h"
#include "primary_expressions/identifier.h"
#include "primary_expressions/match.h"
#include "primary_expressions/subscript.h"
#include "primary_expressions/sizeof_expression.h"
#include "external_declaration.h"
#include "using_declaration.h"
//#include "declarations/function_definition.h"
//#include "parameter.h"
#include "statements/block.h"
#include "statements/if.h"
#include "statements/for.h"
#include "statements/foreach.h"
#include "statements/while.h"
#include "statements/expression_statement.h"
#include "statements/variable_declaration.h"
#include "statements/return.h"
#include "statements/breakpoint.h"
#include "function_definition.h"
#include "program.h"
#include "state_script/state_script.h"
#include "state_script/state_script_block.h"
#include "state_script/state_script_lambda.h"
#include "state_script/state.h"
#include "state_script/track.h"

namespace dconstruct::compilation {

    using global = std::variant<ast::full_type, ast::global_decl_uptr>;

}