####################################################################################################
#                                                                                                  #
#   generated by dconstruct ver. 2.1.0                                                             #
#   listing for file: .../main/bin_unpacked/dc1\ss-forwardbase\ss-fob-scar-raiders-cold-blood.bin  #
#   filesize: 8060 bytes                                                                           #
#   total entries: 1                                                                               #
#   functions: 23                                                                                  #
#   has state script: true                                                                         #
#   game type: t2r                                                                                 #
#   optimizations enabled: sso var, foreach, match, second var, member access, regex               #
#                                                                                                  #
####################################################################################################



##############################  ENTRY 0  ##############################

ss-fob-scar-raiders-cold-blood = state-script [0x00048] {
  statescript #ss-fob-scar-raiders-cold-blood {
    options {
      #player
    }
    declarations {
    }
    state task-check {
      block start {
        track main {
          lambda task-check@start@main@0 {
            0000   0x000EB0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-complete?>
            0001   0x000EB8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <forward-base>
            0002   0x000EC0   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <fob-scar-raiders-cold-blood>
            0003   0x000EC8   43 31 01 00   Move                 r49, r1       r49 = forward-base
            0004   0x000ED0   43 32 02 00   Move                 r50, r2       r50 = fob-scar-raiders-cold-blood
            0005   0x000ED8   1B 00 00 02   Call                 r0, r0, 2     r0 = task-complete?(forward-base, fob-scar-raiders-cold-blood)
            0006   0x000EE0   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 
            0007   0x000EE8   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x000EF0   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <complete>
            0009   0x000EF8   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x000F00   43 31 01 00   Move                 r49, r1       r49 = complete
            000B   0x000F08   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x000F10   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            000D   0x000F18   2D 0F 00 00   Branch               0xF           GOTO 
            000E   0x000F20   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            000F   0x000F28   00 00 00 00   Return               r0            Return 
          }
          lambda task-check@start@main@1 {
            0000   0x001108   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-active?>
            0001   0x001110   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <forward-base>
            0002   0x001118   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <fob-scar-raiders-cold-blood>
            0003   0x001120   43 31 01 00   Move                 r49, r1       r49 = forward-base
            0004   0x001128   43 32 02 00   Move                 r50, r2       r50 = fob-scar-raiders-cold-blood
            0005   0x001130   1B 00 00 02   Call                 r0, r0, 2     r0 = task-active?(forward-base, fob-scar-raiders-cold-blood)
            0006   0x001138   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 
            0007   0x001140   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x001148   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <cold-blood>
            0009   0x001150   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x001158   43 31 01 00   Move                 r49, r1       r49 = cold-blood
            000B   0x001160   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x001168   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(cold-blood, 1)
            000D   0x001170   2D 0F 00 00   Branch               0xF           GOTO 
            000E   0x001178   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            000F   0x001180   00 00 00 00   Return               r0            Return 
          }
        }
      }
      block event task-complete {
        track main {
          lambda task-check@event_task-complete@main@0 {
            0000   0x001108   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-active?>
            0001   0x001110   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <forward-base>
            0002   0x001118   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <fob-scar-raiders-cold-blood>
            0003   0x001120   43 31 01 00   Move                 r49, r1       r49 = forward-base
            0004   0x001128   43 32 02 00   Move                 r50, r2       r50 = fob-scar-raiders-cold-blood
            0005   0x001130   1B 00 00 02   Call                 r0, r0, 2     r0 = task-active?(forward-base, fob-scar-raiders-cold-blood)
            0006   0x001138   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 
            0007   0x001140   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x001148   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <cold-blood>
            0009   0x001150   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x001158   43 31 01 00   Move                 r49, r1       r49 = cold-blood
            000B   0x001160   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x001168   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(cold-blood, 1)
            000D   0x001170   2D 0F 00 00   Branch               0xF           GOTO 
            000E   0x001178   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            000F   0x001180   00 00 00 00   Return               r0            Return 
          }
        }
      }
    }
    state cold-blood {
      block start {
        track npc {
          lambda cold-blood@start@npc@0 {
            0000   0x001078   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <spawn-entity-at>
            0001   0x001080   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <npc-fob-kitchen-chase-1>
            0002   0x001088   15 02 02 00   LookupPointer        r2, 2         r2 = ST[2] -> <get-spawner-locator>
            0003   0x001090   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <pos-kitchen-shelf-spawn-1>
            0004   0x001098   0C 04 01 00   LoadU16Imm           r4, 1         r4 = 1
            0005   0x0010A0   43 31 03 00   Move                 r49, r3       r49 = pos-kitchen-shelf-spawn-1
            0006   0x0010A8   43 32 04 00   Move                 r50, r4       r50 = 1
            0007   0x0010B0   1C 02 02 02   CallFf               r2, r2, 2     r2 = get-spawner-locator(pos-kitchen-shelf-spawn-1, 1)
            0008   0x0010B8   0C 03 00 00   LoadU16Imm           r3, 0         r3 = 0
            0009   0x0010C0   43 31 01 00   Move                 r49, r1       r49 = npc-fob-kitchen-chase-1
            000A   0x0010C8   43 32 02 00   Move                 r50, r2       r50 = RET_get-spawner-locator
            000B   0x0010D0   43 33 03 00   Move                 r51, r3       r51 = 0
            000C   0x0010D8   1C 00 00 03   CallFf               r0, r0, 3     r0 = spawn-entity-at(npc-fob-kitchen-chase-1, RET_get-spawner-locator, 0)
            000D   0x0010E0   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@start@npc@1 {
            0000   0x001040   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <npc-set-script-only-no-perception>
            0001   0x001048   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <npc-fob-kitchen-chase-1>
            0002   0x001050   43 31 01 00   Move                 r49, r1       r49 = npc-fob-kitchen-chase-1
            0003   0x001058   1B 00 00 01   Call                 r0, r0, 1     r0 = npc-set-script-only-no-perception(npc-fob-kitchen-chase-1)
            0004   0x001060   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@start@npc@2 {
            0000   0x001968   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <signal>
            0001   0x001970   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <shelf>
            0002   0x001978   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0003   0x001980   43 31 01 00   Move                 r49, r1       r49 = shelf
            0004   0x001988   43 32 02 00   Move                 r50, r2       r50 = 0
            0005   0x001990   1C 00 00 02   CallFf               r0, r0, 2     r0 = signal(shelf, 0)
            0006   0x001998   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@start@npc@3 {
            0000   0x001458   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-animate_>
            0001   0x001460   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <npc-fob-kitchen-chase-1>
            0002   0x001468   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <fob-scar-raiders-cold-blood--f-npc>
            0003   0x001470   15 03 03 00   LookupPointer        r3, 3         r3 = ST[3] -> <#%alloc-array>
            0004   0x001478   4A 04 04 00   LoadStaticU64Imm     r4, 4         r4 = ST[4] -> <single-frame>
            0005   0x001480   0C 05 10 00   LoadU16Imm           r5, 16        r5 = 16
            0006   0x001488   0C 06 04 00   LoadU16Imm           r6, 4         r6 = 4
            0007   0x001490   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0008   0x001498   43 31 04 00   Move                 r49, r4       r49 = single-frame
            0009   0x0014A0   43 32 05 00   Move                 r50, r5       r50 = 16
            000A   0x0014A8   43 33 06 00   Move                 r51, r6       r51 = 4
            000B   0x0014B0   43 34 07 00   Move                 r52, r7       r52 = 1
            000C   0x0014B8   1C 03 03 04   CallFf               r3, r3, 4     r3 = #%alloc-array(single-frame, 16, 4, 1)
            000D   0x0014C0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            000E   0x0014C8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            000F   0x0014D0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0010   0x0014D8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0011   0x0014E0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0012   0x0014E8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0013   0x0014F0   0C 05 0A 00   LoadU16Imm           r5, 10        r5 = 10
            0014   0x0014F8   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 65535] = 10
            0015   0x001500   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0016   0x001508   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0017   0x001510   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0018   0x001518   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0019   0x001520   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            001A   0x001528   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            001B   0x001530   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            001C   0x001538   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            001D   0x001540   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = 0
            001E   0x001548   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            001F   0x001550   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0020   0x001558   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0021   0x001560   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0022   0x001568   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0023   0x001570   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0024   0x001578   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            0025   0x001580   15 05 05 00   LookupPointer        r5, 5         r5 = ST[5] -> <get-spawner-locator>
            0026   0x001588   4A 06 06 00   LoadStaticU64Imm     r6, 6         r6 = ST[6] -> <ap-fob-store-chase-shelf-1>
            0027   0x001590   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0028   0x001598   43 31 06 00   Move                 r49, r6       r49 = ap-fob-store-chase-shelf-1
            0029   0x0015A0   43 32 07 00   Move                 r50, r7       r50 = 1
            002A   0x0015A8   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-spawner-locator(ap-fob-store-chase-shelf-1, 1)
            002B   0x0015B0   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = RET_get-spawner-locator
            002C   0x0015B8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            002D   0x0015C0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            002E   0x0015C8   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            002F   0x0015D0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0030   0x0015D8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0031   0x0015E0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0032   0x0015E8   0C 05 1C 00   LoadU16Imm           r5, 28        r5 = 28
            0033   0x0015F0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 28
            0034   0x0015F8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0035   0x001600   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0036   0x001608   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0037   0x001610   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0038   0x001618   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0039   0x001620   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003A   0x001628   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            003B   0x001630   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            003C   0x001638   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            003D   0x001640   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            003E   0x001648   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003F   0x001650   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0040   0x001658   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0041   0x001660   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0042   0x001668   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0043   0x001670   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0044   0x001678   40 05 07 00   LoadStaticFloatImm   r5, 7         r5 = ST[7] -> <0.300000>
            0045   0x001680   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 0.300000
            0046   0x001688   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0047   0x001690   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0048   0x001698   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0049   0x0016A0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            004A   0x0016A8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            004B   0x0016B0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            004C   0x0016B8   0C 05 1E 00   LoadU16Imm           r5, 30        r5 = 30
            004D   0x0016C0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 30
            004E   0x0016C8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            004F   0x0016D0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0050   0x0016D8   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0051   0x0016E0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0052   0x0016E8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            0053   0x0016F0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0054   0x0016F8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0055   0x001700   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0056   0x001708   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            0057   0x001710   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0058   0x001718   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0059   0x001720   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            005A   0x001728   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            005B   0x001730   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            005C   0x001738   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            005D   0x001740   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            005E   0x001748   40 05 08 00   LoadStaticFloatImm   r5, 8         r5 = ST[8] -> <0.500000>
            005F   0x001750   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 0.500000
            0060   0x001758   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0061   0x001760   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0062   0x001768   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            0063   0x001770   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0064   0x001778   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            0065   0x001780   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0066   0x001788   0C 05 39 00   LoadU16Imm           r5, 57        r5 = 57
            0067   0x001790   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 57
            0068   0x001798   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0069   0x0017A0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006A   0x0017A8   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            006B   0x0017B0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            006C   0x0017B8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            006D   0x0017C0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006E   0x0017C8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            006F   0x0017D0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0070   0x0017D8   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            0071   0x0017E0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0072   0x0017E8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0073   0x0017F0   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            0074   0x0017F8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0075   0x001800   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            0076   0x001808   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0077   0x001810   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0078   0x001818   40 05 09 00   LoadStaticFloatImm   r5, 9         r5 = ST[9] -> <30.000000>
            0079   0x001820   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 30.000000
            007A   0x001828   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            007B   0x001830   43 03 04 00   Move                 r3, r4        r3 = RET_#%alloc-array
            007C   0x001838   43 31 01 00   Move                 r49, r1       r49 = npc-fob-kitchen-chase-1
            007D   0x001840   43 32 02 00   Move                 r50, r2       r50 = fob-scar-raiders-cold-blood--f-npc
            007E   0x001848   43 33 03 00   Move                 r51, r3       r51 = RET_#%alloc-array
            007F   0x001850   1C 00 00 03   CallFf               r0, r0, 3     r0 = wait-animate_(npc-fob-kitchen-chase-1, fob-scar-raiders-cold-blood--f-npc, RET_#%alloc-array)
            0080   0x001858   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@start@npc@4 {
            0000   0x000E78   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <interactable-enable>
            0001   0x000E80   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <int-fob-store-kitchen-dead-1>
            0002   0x000E88   43 31 01 00   Move                 r49, r1       r49 = int-fob-store-kitchen-dead-1
            0003   0x000E90   1C 00 00 01   CallFf               r0, r0, 1     r0 = interactable-enable(int-fob-store-kitchen-dead-1)
            0004   0x000E98   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@start@npc@5 {
            0000   0x001B10   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <animate_>
            0001   0x001B18   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <npc-fob-kitchen-chase-1>
            0002   0x001B20   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <fob-scar-raiders-cold-blood-loop--f-npc>
            0003   0x001B28   15 03 03 00   LookupPointer        r3, 3         r3 = ST[3] -> <#%alloc-array>
            0004   0x001B30   4A 04 04 00   LoadStaticU64Imm     r4, 4         r4 = ST[4] -> <single-frame>
            0005   0x001B38   0C 05 10 00   LoadU16Imm           r5, 16        r5 = 16
            0006   0x001B40   0C 06 01 00   LoadU16Imm           r6, 1         r6 = 1
            0007   0x001B48   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0008   0x001B50   43 31 04 00   Move                 r49, r4       r49 = single-frame
            0009   0x001B58   43 32 05 00   Move                 r50, r5       r50 = 16
            000A   0x001B60   43 33 06 00   Move                 r51, r6       r51 = 1
            000B   0x001B68   43 34 07 00   Move                 r52, r7       r52 = 1
            000C   0x001B70   1C 03 03 04   CallFf               r3, r3, 4     r3 = #%alloc-array(single-frame, 16, 1, 1)
            000D   0x001B78   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            000E   0x001B80   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            000F   0x001B88   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0010   0x001B90   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0011   0x001B98   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0012   0x001BA0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0013   0x001BA8   0C 05 0A 00   LoadU16Imm           r5, 10        r5 = 10
            0014   0x001BB0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 65535] = 10
            0015   0x001BB8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0016   0x001BC0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0017   0x001BC8   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0018   0x001BD0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0019   0x001BD8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            001A   0x001BE0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            001B   0x001BE8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            001C   0x001BF0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            001D   0x001BF8   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = 0
            001E   0x001C00   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            001F   0x001C08   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0020   0x001C10   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0021   0x001C18   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0022   0x001C20   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0023   0x001C28   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0024   0x001C30   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            0025   0x001C38   15 05 05 00   LookupPointer        r5, 5         r5 = ST[5] -> <get-spawner-locator>
            0026   0x001C40   4A 06 06 00   LoadStaticU64Imm     r6, 6         r6 = ST[6] -> <ap-fob-store-chase-shelf-1>
            0027   0x001C48   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0028   0x001C50   43 31 06 00   Move                 r49, r6       r49 = ap-fob-store-chase-shelf-1
            0029   0x001C58   43 32 07 00   Move                 r50, r7       r50 = 1
            002A   0x001C60   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-spawner-locator(ap-fob-store-chase-shelf-1, 1)
            002B   0x001C68   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = RET_get-spawner-locator
            002C   0x001C70   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            002D   0x001C78   43 03 04 00   Move                 r3, r4        r3 = RET_#%alloc-array
            002E   0x001C80   43 31 01 00   Move                 r49, r1       r49 = npc-fob-kitchen-chase-1
            002F   0x001C88   43 32 02 00   Move                 r50, r2       r50 = fob-scar-raiders-cold-blood-loop--f-npc
            0030   0x001C90   43 33 03 00   Move                 r51, r3       r51 = RET_#%alloc-array
            0031   0x001C98   1C 00 00 03   CallFf               r0, r0, 3     r0 = animate_(npc-fob-kitchen-chase-1, fob-scar-raiders-cold-blood-loop--f-npc, RET_#%alloc-array)
            0032   0x001CA0   00 00 00 00   Return               r0            Return 
          }
        }
        track shelf {
          lambda cold-blood@start@shelf@0 {
            0000   0x001AD8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-for>
            0001   0x001AE0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <shelf>
            0002   0x001AE8   43 31 01 00   Move                 r49, r1       r49 = shelf
            0003   0x001AF0   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait-for(shelf)
            0004   0x001AF8   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@start@shelf@1 {
            0000   0x0011B0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <animate_>
            0001   0x0011B8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <obj-fob-store-chase-shelf-1>
            0002   0x0011C0   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <fob-scar-raiders-cold-blood--shelf>
            0003   0x0011C8   15 03 03 00   LookupPointer        r3, 3         r3 = ST[3] -> <#%alloc-array>
            0004   0x0011D0   4A 04 04 00   LoadStaticU64Imm     r4, 4         r4 = ST[4] -> <single-frame>
            0005   0x0011D8   0C 05 10 00   LoadU16Imm           r5, 16        r5 = 16
            0006   0x0011E0   0C 06 02 00   LoadU16Imm           r6, 2         r6 = 2
            0007   0x0011E8   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0008   0x0011F0   43 31 04 00   Move                 r49, r4       r49 = single-frame
            0009   0x0011F8   43 32 05 00   Move                 r50, r5       r50 = 16
            000A   0x001200   43 33 06 00   Move                 r51, r6       r51 = 2
            000B   0x001208   43 34 07 00   Move                 r52, r7       r52 = 1
            000C   0x001210   1C 03 03 04   CallFf               r3, r3, 4     r3 = #%alloc-array(single-frame, 16, 2, 1)
            000D   0x001218   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            000E   0x001220   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            000F   0x001228   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0010   0x001230   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0011   0x001238   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0012   0x001240   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0013   0x001248   0C 05 0A 00   LoadU16Imm           r5, 10        r5 = 10
            0014   0x001250   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 65535] = 10
            0015   0x001258   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0016   0x001260   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0017   0x001268   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0018   0x001270   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0019   0x001278   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            001A   0x001280   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            001B   0x001288   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            001C   0x001290   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            001D   0x001298   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = 0
            001E   0x0012A0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            001F   0x0012A8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0020   0x0012B0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0021   0x0012B8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0022   0x0012C0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0023   0x0012C8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0024   0x0012D0   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            0025   0x0012D8   15 05 05 00   LookupPointer        r5, 5         r5 = ST[5] -> <get-spawner-locator>
            0026   0x0012E0   4A 06 06 00   LoadStaticU64Imm     r6, 6         r6 = ST[6] -> <ap-fob-store-chase-shelf-1>
            0027   0x0012E8   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0028   0x0012F0   43 31 06 00   Move                 r49, r6       r49 = ap-fob-store-chase-shelf-1
            0029   0x0012F8   43 32 07 00   Move                 r50, r7       r50 = 1
            002A   0x001300   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-spawner-locator(ap-fob-store-chase-shelf-1, 1)
            002B   0x001308   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = RET_get-spawner-locator
            002C   0x001310   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            002D   0x001318   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            002E   0x001320   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            002F   0x001328   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0030   0x001330   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0031   0x001338   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0032   0x001340   0C 05 39 00   LoadU16Imm           r5, 57        r5 = 57
            0033   0x001348   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 57
            0034   0x001350   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0035   0x001358   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0036   0x001360   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0037   0x001368   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0038   0x001370   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0039   0x001378   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003A   0x001380   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            003B   0x001388   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            003C   0x001390   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            003D   0x001398   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            003E   0x0013A0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003F   0x0013A8   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0040   0x0013B0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0041   0x0013B8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0042   0x0013C0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0043   0x0013C8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0044   0x0013D0   40 05 07 00   LoadStaticFloatImm   r5, 7         r5 = ST[7] -> <30.000000>
            0045   0x0013D8   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 30.000000
            0046   0x0013E0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0047   0x0013E8   43 03 04 00   Move                 r3, r4        r3 = RET_#%alloc-array
            0048   0x0013F0   43 31 01 00   Move                 r49, r1       r49 = obj-fob-store-chase-shelf-1
            0049   0x0013F8   43 32 02 00   Move                 r50, r2       r50 = fob-scar-raiders-cold-blood--shelf
            004A   0x001400   43 33 03 00   Move                 r51, r3       r51 = RET_#%alloc-array
            004B   0x001408   1C 00 00 03   CallFf               r0, r0, 3     r0 = animate_(obj-fob-store-chase-shelf-1, fob-scar-raiders-cold-blood--shelf, RET_#%alloc-array)
            004C   0x001410   00 00 00 00   Return               r0            Return 
          }
        }
      }
      block update {
        track main {
          lambda cold-blood@update@main@0 {
            0000   0x0018B0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <player-force-walk>
            0001   0x0018B8   1C 00 00 00   CallFf               r0, r0, 0     r0 = player-force-walk()
            0002   0x0018C0   00 00 00 00   Return               r0            Return 
          }
        }
      }
      block event npc-died {
        track main {
          lambda cold-blood@event_npc-died@main@0 {
            0000   0x001A30   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait>
            0001   0x001A38   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <2.000000>
            0002   0x001A40   43 31 01 00   Move                 r49, r1       r49 = 2.000000
            0003   0x001A48   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait(2.000000)
            0004   0x001A50   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@event_npc-died@main@1 {
            0000   0x001920   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x001928   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <teleport>
            0002   0x001930   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001938   43 31 01 00   Move                 r49, r1       r49 = teleport
            0004   0x001940   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x001948   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(teleport, 1)
            0006   0x001950   00 00 00 00   Return               r0            Return 
          }
        }
      }
      block event player-requested-interact {
        track main {
          lambda cold-blood@event_player-requested-interact@main@0 {
            0000   0x000F90   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait>
            0001   0x000F98   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <0.500000>
            0002   0x000FA0   43 31 01 00   Move                 r49, r1       r49 = 0.500000
            0003   0x000FA8   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait(0.500000)
            0004   0x000FB0   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@event_player-requested-interact@main@1 {
            0000   0x0019B0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <stop-animating>
            0001   0x0019B8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <npc-fob-kitchen-chase-1>
            0002   0x0019C0   0C 02 02 00   LoadU16Imm           r2, 2         r2 = 2
            0003   0x0019C8   40 03 02 00   LoadStaticFloatImm   r3, 2         r3 = ST[2] -> <0.000000>
            0004   0x0019D0   0C 04 00 00   LoadU16Imm           r4, 0         r4 = 0
            0005   0x0019D8   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0006   0x0019E0   43 31 01 00   Move                 r49, r1       r49 = npc-fob-kitchen-chase-1
            0007   0x0019E8   43 32 02 00   Move                 r50, r2       r50 = 2
            0008   0x0019F0   43 33 03 00   Move                 r51, r3       r51 = 0.000000
            0009   0x0019F8   43 34 04 00   Move                 r52, r4       r52 = 0
            000A   0x001A00   43 35 05 00   Move                 r53, r5       r53 = 0
            000B   0x001A08   1C 00 00 05   CallFf               r0, r0, 5     r0 = stop-animating(npc-fob-kitchen-chase-1, 2, 0.000000, 0, 0)
            000C   0x001A10   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@event_player-requested-interact@main@2 {
            0000   0x000FC8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <npc-die>
            0001   0x000FD0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <npc-fob-kitchen-chase-1>
            0002   0x000FD8   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0003   0x000FE0   0C 03 00 00   LoadU16Imm           r3, 0         r3 = 0
            0004   0x000FE8   0C 04 00 00   LoadU16Imm           r4, 0         r4 = 0
            0005   0x000FF0   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0006   0x000FF8   43 31 01 00   Move                 r49, r1       r49 = npc-fob-kitchen-chase-1
            0007   0x001000   43 32 02 00   Move                 r50, r2       r50 = 0
            0008   0x001008   43 33 03 00   Move                 r51, r3       r51 = 0
            0009   0x001010   43 34 04 00   Move                 r52, r4       r52 = 0
            000A   0x001018   43 35 05 00   Move                 r53, r5       r53 = 1
            000B   0x001020   1C 00 00 05   CallFf               r0, r0, 5     r0 = npc-die(npc-fob-kitchen-chase-1, 0, 0, 0, 1)
            000C   0x001028   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@event_player-requested-interact@main@3 {
            0000   0x001CE0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait>
            0001   0x001CE8   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <1.000000>
            0002   0x001CF0   43 31 01 00   Move                 r49, r1       r49 = 1.000000
            0003   0x001CF8   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait(1.000000)
            0004   0x001D00   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@event_player-requested-interact@main@4 {
            0000   0x001A68   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <fade-to-black>
            0001   0x001A70   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <1.000000>
            0002   0x001A78   40 02 02 00   LoadStaticFloatImm   r2, 2         r2 = ST[2] -> <2.000000>
            0003   0x001A80   40 03 01 00   LoadStaticFloatImm   r3, 1         r3 = ST[1] -> <1.000000>
            0004   0x001A88   0C 04 00 00   LoadU16Imm           r4, 0         r4 = 0
            0005   0x001A90   43 31 01 00   Move                 r49, r1       r49 = 1.000000
            0006   0x001A98   43 32 02 00   Move                 r50, r2       r50 = 2.000000
            0007   0x001AA0   43 33 03 00   Move                 r51, r3       r51 = 1.000000
            0008   0x001AA8   43 34 04 00   Move                 r52, r4       r52 = 0
            0009   0x001AB0   1C 00 00 04   CallFf               r0, r0, 4     r0 = fade-to-black(1.000000, 2.000000, 1.000000, 0)
            000A   0x001AB8   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@event_player-requested-interact@main@5 {
            0000   0x000F58   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait>
            0001   0x000F60   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <3.000000>
            0002   0x000F68   43 31 01 00   Move                 r49, r1       r49 = 3.000000
            0003   0x000F70   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait(3.000000)
            0004   0x000F78   00 00 00 00   Return               r0            Return 
          }
          lambda cold-blood@event_player-requested-interact@main@6 {
            0000   0x001920   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x001928   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <teleport>
            0002   0x001930   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001938   43 31 01 00   Move                 r49, r1       r49 = teleport
            0004   0x001940   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x001948   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(teleport, 1)
            0006   0x001950   00 00 00 00   Return               r0            Return 
          }
        }
      }
    }
    state teleport {
      block start {
        track main {
          lambda teleport@start@main@0 {
            0000   0x0018D0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-complete!>
            0001   0x0018D8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <forward-base>
            0002   0x0018E0   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <fob-scar-raiders-cold-blood>
            0003   0x0018E8   43 31 01 00   Move                 r49, r1       r49 = forward-base
            0004   0x0018F0   43 32 02 00   Move                 r50, r2       r50 = fob-scar-raiders-cold-blood
            0005   0x0018F8   1B 00 00 02   Call                 r0, r0, 2     r0 = task-complete!(forward-base, fob-scar-raiders-cold-blood)
            0006   0x001900   00 00 00 00   Return               r0            Return 
          }
          lambda teleport@start@main@1 {
            0000   0x001D18   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x001D20   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <complete>
            0002   0x001D28   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001D30   43 31 01 00   Move                 r49, r1       r49 = complete
            0004   0x001D38   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x001D40   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            0006   0x001D48   00 00 00 00   Return               r0            Return 
          }
        }
      }
    }
    state complete {
    }
  }
}
