#pragma once

#include "expression.h"
#include "add.h"
#include "sub.h"
#include "mul.h"
#include "div.h"
#include "assign.h"
#include "compare.h"
#include "call.h"
#include "grouping.h"
#include "literal.h"
#include "identifier.h"
#include "assign_statement.h"
#include "function_definition.h"
#include "parameter.h"
#include "statements.h"
#include "variable_declaration.h"