####################################################################################################
#                                                                                                  #
#   generated by dconstruct ver. 1.52.0                                                            #
#   listing for file: .\game_dumps\t2r\dc1\ss-finding-nora\ss-nor-ellie-alone-ambush-setup.bin     #
#   filesize: 8373 bytes                                                                           #
#   total entries: 1                                                                               #
#   functions: 27                                                                                  #
#   has state script: true                                                                         #
#   game type: t2r                                                                                 #
#   optimizations enabled: true                                                                    #
#                                                                                                  #
####################################################################################################



##############################  ENTRY 0  ##############################

ss-nor-ellie-alone-ambush-setup = state-script [0x00048] {
  OPTIONS: 
    [0x000658]     player
    [0x000660]     nor-theater-streets-script
  DECLARATIONS: 
    [0x0001E0] boolean  used-door            = uninitialized
    [0x000210] boolean  uneasy-at-door-sound = uninitialized
    STATE --all-- {
      ON event player-entered-house {
        TRACK main {
          {
            0000   0x001588   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-continue-active?>
            0001   0x001590   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x001598   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-ellie-alone-streets>
            0003   0x0015A0   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <workbench-ambush-mid-struggle>
            0004   0x0015A8   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0005   0x0015B0   43 32 02 00   Move                 r50, r2       r50 = nor-ellie-alone-streets
            0006   0x0015B8   43 33 03 00   Move                 r51, r3       r51 = workbench-ambush-mid-struggle
            0007   0x0015C0   1B 00 00 03   Call                 r0, r0, 3     r0 = task-continue-active?(find-nora, nor-ellie-alone-streets, workbench-ambush-mid-struggle)
            0008   0x0015C8   30 00 00 00   OpLogNot             r0, r0        r0 = !RET_task-continue-active?
            0009   0x0015D0   2F 32 00 00   BranchIfNot          r0, 0x32      IF NOT r0 => L_RETURN_0
            000A   0x0015D8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-continue-active?>
            000B   0x0015E0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            000C   0x0015E8   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-ellie-alone-streets>
            000D   0x0015F0   4A 03 04 00   LoadStaticU64Imm     r3, 4         r3 = ST[4] -> <workbench-ambush>
            000E   0x0015F8   43 31 01 00   Move                 r49, r1       r49 = find-nora
            000F   0x001600   43 32 02 00   Move                 r50, r2       r50 = nor-ellie-alone-streets
            0010   0x001608   43 33 03 00   Move                 r51, r3       r51 = workbench-ambush
            0011   0x001610   1B 00 00 03   Call                 r0, r0, 3     r0 = task-continue-active?(find-nora, nor-ellie-alone-streets, workbench-ambush)
            0012   0x001618   30 00 00 00   OpLogNot             r0, r0        r0 = !RET_task-continue-active?
            0013   0x001620   2F 30 00 00   BranchIfNot          r0, 0x30      IF NOT r0 => L_1
            0014   0x001628   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-continue-active?>
            0015   0x001630   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0016   0x001638   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-ellie-alone-streets>
            0017   0x001640   4A 03 05 00   LoadStaticU64Imm     r3, 5         r3 = ST[5] -> <ambush-done>
            0018   0x001648   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0019   0x001650   43 32 02 00   Move                 r50, r2       r50 = nor-ellie-alone-streets
            001A   0x001658   43 33 03 00   Move                 r51, r3       r51 = ambush-done
            001B   0x001660   1B 00 00 03   Call                 r0, r0, 3     r0 = task-continue-active?(find-nora, nor-ellie-alone-streets, ambush-done)
            001C   0x001668   30 00 00 00   OpLogNot             r0, r0        r0 = !RET_task-continue-active?
            001D   0x001670   2F 2E 00 00   BranchIfNot          r0, 0x2E      IF NOT r0 => L_2
            001E   0x001678   15 00 06 00   LookupPointer        r0, 6         r0 = ST[6] -> <get-svar>
            001F   0x001680   4A 01 07 00   LoadStaticU64Imm     r1, 7         r1 = ST[7] -> <nor-alone-workbench-ambush-done>
            0020   0x001688   43 31 01 00   Move                 r49, r1       r49 = nor-alone-workbench-ambush-done
            0021   0x001690   1B 00 00 01   Call                 r0, r0, 1     r0 = get-svar(nor-alone-workbench-ambush-done)
            0022   0x001698   0C 01 00 00   LoadU16Imm           r1, 0         r1 = 0
            0023   0x0016A0   1D 00 00 01   IEqual               r0, r0, r1    r0 = r0 == r1
            0024   0x0016A8   2F 2C 00 00   BranchIfNot          r0, 0x2C      IF NOT r0 => L_3
            0025   0x0016B0   15 00 08 00   LookupPointer        r0, 8         r0 = ST[8] -> <send-event>
            0026   0x0016B8   4A 01 09 00   LoadStaticU64Imm     r1, 9         r1 = ST[9] -> <ambush-apartment>
            0027   0x0016C0   4A 02 0A 00   LoadStaticU64Imm     r2, 10        r2 = ST[10] -> <ss-nor-ellie-alone-task-controller-1>
            0028   0x0016C8   43 31 01 00   Move                 r49, r1       r49 = ambush-apartment
            0029   0x0016D0   43 32 02 00   Move                 r50, r2       r50 = ss-nor-ellie-alone-task-controller-1
            002A   0x0016D8   1C 00 00 02   CallFf               r0, r0, 2     r0 = send-event(ambush-apartment, ss-nor-ellie-alone-task-controller-1)
            002B   0x0016E0   2D 2D 00 00   Branch               0x33          GOTO => L_RETURN
          L_3:
            002C   0x0016E8   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            002D   0x0016F0   2D 2F 00 00   Branch               0x33          GOTO => L_RETURN
          L_2:
            002E   0x0016F8   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            002F   0x001700   2D 31 00 00   Branch               0x33          GOTO => L_RETURN
          L_1:
            0030   0x001708   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            0031   0x001710   2D 33 00 00   Branch               0x33          GOTO => L_RETURN
          L_RETURN_0:
            0032   0x001718   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            0033   0x001720   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001728    function: task-continue-active?
            0001   0x001730    sid: find-nora
            0002   0x001738    sid: nor-ellie-alone-streets
            0003   0x001740    sid: workbench-ambush-mid-struggle
            0004   0x001748    sid: workbench-ambush
            0005   0x001750    sid: ambush-done
            0006   0x001758    function: get-svar
            0007   0x001760    sid: nor-alone-workbench-ambush-done
            0008   0x001768    function: send-event
            0009   0x001770    sid: ambush-apartment
            000A   0x001778    sid: ss-nor-ellie-alone-task-controller-1
          }
        }

      }
    } END STATE --all--

    STATE task-check {
      ON start {
        TRACK main {
          {
            0000   0x001420   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-complete?>
            0001   0x001428   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x001430   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-ellie-alone-streets>
            0003   0x001438   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0004   0x001440   43 32 02 00   Move                 r50, r2       r50 = nor-ellie-alone-streets
            0005   0x001448   1B 00 00 02   Call                 r0, r0, 2     r0 = task-complete?(find-nora, nor-ellie-alone-streets)
            0006   0x001450   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 => L_RETURN_0
            0007   0x001458   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x001460   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <complete>
            0009   0x001468   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x001470   43 31 01 00   Move                 r49, r1       r49 = complete
            000B   0x001478   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x001480   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            000D   0x001488   2D 0F 00 00   Branch               0xF           GOTO => L_RETURN
          L_RETURN_0:
            000E   0x001490   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            000F   0x001498   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0014A0    function: task-complete?
            0001   0x0014A8    sid: find-nora
            0002   0x0014B0    sid: nor-ellie-alone-streets
            0003   0x0014B8    function: go
            0004   0x0014C0    sid: complete
          }
          {
            0000   0x0014C8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-continue-active?>
            0001   0x0014D0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x0014D8   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-ellie-alone-streets>
            0003   0x0014E0   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <workbench-ambush>
            0004   0x0014E8   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0005   0x0014F0   43 32 02 00   Move                 r50, r2       r50 = nor-ellie-alone-streets
            0006   0x0014F8   43 33 03 00   Move                 r51, r3       r51 = workbench-ambush
            0007   0x001500   1B 00 00 03   Call                 r0, r0, 3     r0 = task-continue-active?(find-nora, nor-ellie-alone-streets, workbench-ambush)
            0008   0x001508   2F 10 00 00   BranchIfNot          r0, 0x10      IF NOT r0 => L_RETURN_0
            0009   0x001510   15 00 04 00   LookupPointer        r0, 4         r0 = ST[4] -> <go>
            000A   0x001518   4A 01 05 00   LoadStaticU64Imm     r1, 5         r1 = ST[5] -> <complete>
            000B   0x001520   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000C   0x001528   43 31 01 00   Move                 r49, r1       r49 = complete
            000D   0x001530   43 32 02 00   Move                 r50, r2       r50 = 1
            000E   0x001538   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            000F   0x001540   2D 11 00 00   Branch               0x11          GOTO => L_RETURN
          L_RETURN_0:
            0010   0x001548   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            0011   0x001550   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001558    function: task-continue-active?
            0001   0x001560    sid: find-nora
            0002   0x001568    sid: nor-ellie-alone-streets
            0003   0x001570    sid: workbench-ambush
            0004   0x001578    function: go
            0005   0x001580    sid: complete
          }
          {
            0000   0x001B80   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-continue-active?>
            0001   0x001B88   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x001B90   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-ellie-alone-streets>
            0003   0x001B98   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <workbench-ambush-mid-struggle>
            0004   0x001BA0   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0005   0x001BA8   43 32 02 00   Move                 r50, r2       r50 = nor-ellie-alone-streets
            0006   0x001BB0   43 33 03 00   Move                 r51, r3       r51 = workbench-ambush-mid-struggle
            0007   0x001BB8   1B 00 00 03   Call                 r0, r0, 3     r0 = task-continue-active?(find-nora, nor-ellie-alone-streets, workbench-ambush-mid-struggle)
            0008   0x001BC0   2F 10 00 00   BranchIfNot          r0, 0x10      IF NOT r0 => L_RETURN_0
            0009   0x001BC8   15 00 04 00   LookupPointer        r0, 4         r0 = ST[4] -> <go>
            000A   0x001BD0   4A 01 05 00   LoadStaticU64Imm     r1, 5         r1 = ST[5] -> <complete>
            000B   0x001BD8   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000C   0x001BE0   43 31 01 00   Move                 r49, r1       r49 = complete
            000D   0x001BE8   43 32 02 00   Move                 r50, r2       r50 = 1
            000E   0x001BF0   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            000F   0x001BF8   2D 11 00 00   Branch               0x11          GOTO => L_RETURN
          L_RETURN_0:
            0010   0x001C00   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            0011   0x001C08   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001C10    function: task-continue-active?
            0001   0x001C18    sid: find-nora
            0002   0x001C20    sid: nor-ellie-alone-streets
            0003   0x001C28    sid: workbench-ambush-mid-struggle
            0004   0x001C30    function: go
            0005   0x001C38    sid: complete
          }
          {
            0000   0x0012F0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-active?>
            0001   0x0012F8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x001300   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-ellie-alone-streets>
            0003   0x001308   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0004   0x001310   43 32 02 00   Move                 r50, r2       r50 = nor-ellie-alone-streets
            0005   0x001318   1B 00 00 02   Call                 r0, r0, 2     r0 = task-active?(find-nora, nor-ellie-alone-streets)
            0006   0x001320   2F 1C 00 00   BranchIfNot          r0, 0x1C      IF NOT r0 => L_RETURN_0
            0007   0x001328   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <get-svar>
            0008   0x001330   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <nor-alone-workbench-ambush-done>
            0009   0x001338   43 31 01 00   Move                 r49, r1       r49 = nor-alone-workbench-ambush-done
            000A   0x001340   1B 00 00 01   Call                 r0, r0, 1     r0 = get-svar(nor-alone-workbench-ambush-done)
            000B   0x001348   0C 01 00 00   LoadU16Imm           r1, 0         r1 = 0
            000C   0x001350   1D 00 00 01   IEqual               r0, r0, r1    r0 = r0 == r1
            000D   0x001358   2F 15 00 00   BranchIfNot          r0, 0x15      IF NOT r0 => L_1
            000E   0x001360   15 00 05 00   LookupPointer        r0, 5         r0 = ST[5] -> <go>
            000F   0x001368   4A 01 06 00   LoadStaticU64Imm     r1, 6         r1 = ST[6] -> <wait-interact>
            0010   0x001370   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0011   0x001378   43 31 01 00   Move                 r49, r1       r49 = wait-interact
            0012   0x001380   43 32 02 00   Move                 r50, r2       r50 = 1
            0013   0x001388   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(wait-interact, 1)
            0014   0x001390   2D 1B 00 00   Branch               0x1D          GOTO => L_RETURN
          L_1:
            0015   0x001398   15 00 05 00   LookupPointer        r0, 5         r0 = ST[5] -> <go>
            0016   0x0013A0   4A 01 07 00   LoadStaticU64Imm     r1, 7         r1 = ST[7] -> <complete>
            0017   0x0013A8   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0018   0x0013B0   43 31 01 00   Move                 r49, r1       r49 = complete
            0019   0x0013B8   43 32 02 00   Move                 r50, r2       r50 = 1
            001A   0x0013C0   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            001B   0x0013C8   2D 1D 00 00   Branch               0x1D          GOTO => L_RETURN
          L_RETURN_0:
            001C   0x0013D0   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            001D   0x0013D8   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0013E0    function: task-active?
            0001   0x0013E8    sid: find-nora
            0002   0x0013F0    sid: nor-ellie-alone-streets
            0003   0x0013F8    function: get-svar
            0004   0x001400    sid: nor-alone-workbench-ambush-done
            0005   0x001408    function: go
            0006   0x001410    sid: wait-interact
            0007   0x001418    sid: complete
          }
        }

      }
      ON event task-complete {
        TRACK main {
          {
            0000   0x001878   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-active?>
            0001   0x001880   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x001888   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-ellie-alone-streets>
            0003   0x001890   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0004   0x001898   43 32 02 00   Move                 r50, r2       r50 = nor-ellie-alone-streets
            0005   0x0018A0   1B 00 00 02   Call                 r0, r0, 2     r0 = task-active?(find-nora, nor-ellie-alone-streets)
            0006   0x0018A8   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 => L_RETURN_0
            0007   0x0018B0   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x0018B8   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <wait-interact>
            0009   0x0018C0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x0018C8   43 31 01 00   Move                 r49, r1       r49 = wait-interact
            000B   0x0018D0   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x0018D8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(wait-interact, 1)
            000D   0x0018E0   2D 0F 00 00   Branch               0xF           GOTO => L_RETURN
          L_RETURN_0:
            000E   0x0018E8   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            000F   0x0018F0   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0018F8    function: task-active?
            0001   0x001900    sid: find-nora
            0002   0x001908    sid: nor-ellie-alone-streets
            0003   0x001910    function: go
            0004   0x001918    sid: wait-interact
          }
        }

      }
    } END STATE task-check

    STATE wait-interact {
      ON start {
        TRACK prog {
          {
            0000   0x001A20   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-for-event>
            0001   0x001A28   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <at-workbench>
            0002   0x001A30   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0003   0x001A38   0C 03 00 00   LoadU16Imm           r3, 0         r3 = 0
            0004   0x001A40   0C 04 00 00   LoadU16Imm           r4, 0         r4 = 0
            0005   0x001A48   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0006   0x001A50   0C 06 00 00   LoadU16Imm           r6, 0         r6 = 0
            0007   0x001A58   0C 07 00 00   LoadU16Imm           r7, 0         r7 = 0
            0008   0x001A60   0C 08 00 00   LoadU16Imm           r8, 0         r8 = 0
            0009   0x001A68   0C 09 00 00   LoadU16Imm           r9, 0         r9 = 0
            000A   0x001A70   0C 0A 00 00   LoadU16Imm           r10, 0        r10 = 0
            000B   0x001A78   43 31 01 00   Move                 r49, r1       r49 = at-workbench
            000C   0x001A80   43 32 02 00   Move                 r50, r2       r50 = 0
            000D   0x001A88   43 33 03 00   Move                 r51, r3       r51 = 0
            000E   0x001A90   43 34 04 00   Move                 r52, r4       r52 = 0
            000F   0x001A98   43 35 05 00   Move                 r53, r5       r53 = 0
            0010   0x001AA0   43 36 06 00   Move                 r54, r6       r54 = 0
            0011   0x001AA8   43 37 07 00   Move                 r55, r7       r55 = 0
            0012   0x001AB0   43 38 08 00   Move                 r56, r8       r56 = 0
            0013   0x001AB8   43 39 09 00   Move                 r57, r9       r57 = 0
            0014   0x001AC0   43 3A 0A 00   Move                 r58, r10      r58 = 0
            0015   0x001AC8   1C 00 00 0A   CallFf               r0, r0, 10    r0 = wait-for-event(at-workbench, 0, 0, 0, 0, 0, 0, 0, 0, 0)
            0016   0x001AD0   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001AD8    function: wait-for-event
            0001   0x001AE0    sid: at-workbench
          }
          {
            0000   0x0011D0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x0011D8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <complete>
            0002   0x0011E0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x0011E8   43 31 01 00   Move                 r49, r1       r49 = complete
            0004   0x0011F0   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x0011F8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            0006   0x001200   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001208    function: go
            0001   0x001210    sid: complete
          }
        }

      }
      ON event player-enter-upstairs-ambush-apartment-stairwell {
        TRACK main {
          {
            0000   0x001B38   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x001B40   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <play-sound-stairwell>
            0002   0x001B48   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001B50   43 31 01 00   Move                 r49, r1       r49 = play-sound-stairwell
            0004   0x001B58   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x001B60   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(play-sound-stairwell, 1)
            0006   0x001B68   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001B70    function: go
            0001   0x001B78    sid: play-sound-stairwell
          }
        }

      }
      ON event player-enter-upstairs-ambush-apartment-window {
        TRACK main {
          {
            0000   0x001188   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x001190   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <play-sound-window>
            0002   0x001198   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x0011A0   43 31 01 00   Move                 r49, r1       r49 = play-sound-window
            0004   0x0011A8   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x0011B0   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(play-sound-window, 1)
            0006   0x0011B8   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0011C0    function: go
            0001   0x0011C8    sid: play-sound-window
          }
        }

      }
      ON event player-enter-upstairs-ambush-apartment-secret-apt {
        TRACK main {
          {
            0000   0x001D68   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x001D70   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <play-sound-secret-apt>
            0002   0x001D78   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001D80   43 31 01 00   Move                 r49, r1       r49 = play-sound-secret-apt
            0004   0x001D88   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x001D90   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(play-sound-secret-apt, 1)
            0006   0x001D98   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001DA0    function: go
            0001   0x001DA8    sid: play-sound-secret-apt
          }
        }

      }
      ON event task-complete {
        TRACK main {
          {
            0000   0x001420   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-complete?>
            0001   0x001428   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <find-nora>
            0002   0x001430   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <nor-ellie-alone-streets>
            0003   0x001438   43 31 01 00   Move                 r49, r1       r49 = find-nora
            0004   0x001440   43 32 02 00   Move                 r50, r2       r50 = nor-ellie-alone-streets
            0005   0x001448   1B 00 00 02   Call                 r0, r0, 2     r0 = task-complete?(find-nora, nor-ellie-alone-streets)
            0006   0x001450   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 => L_RETURN_0
            0007   0x001458   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x001460   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <complete>
            0009   0x001468   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x001470   43 31 01 00   Move                 r49, r1       r49 = complete
            000B   0x001478   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x001480   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            000D   0x001488   2D 0F 00 00   Branch               0xF           GOTO => L_RETURN
          L_RETURN_0:
            000E   0x001490   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            000F   0x001498   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0014A0    function: task-complete?
            0001   0x0014A8    sid: find-nora
            0002   0x0014B0    sid: nor-ellie-alone-streets
            0003   0x0014B8    function: go
            0004   0x0014C0    sid: complete
          }
        }

      }
    } END STATE wait-interact

    STATE play-sound-window {
      ON start {
        TRACK main {
          {
            0000   0x001D30   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait>
            0001   0x001D38   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <1.000000>
            0002   0x001D40   43 31 01 00   Move                 r49, r1       r49 = 1.000000
            0003   0x001D48   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait(1.000000)
            0004   0x001D50   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001D58    function: wait
            0001   0x001D60    float: 1.000000
          }
          {
            0000   0x001980   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <play-sound-at-position>
            0001   0x001988   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <sfx-igc-nor-ambush-door-upstairs>
            0002   0x001990   15 02 02 00   LookupPointer        r2, 2         r2 = ST[2] -> <get-spawner-position>
            0003   0x001998   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <snd-pos-nor-apartment-door-close-1>
            0004   0x0019A0   0C 04 01 00   LoadU16Imm           r4, 1         r4 = 1
            0005   0x0019A8   43 31 03 00   Move                 r49, r3       r49 = snd-pos-nor-apartment-door-close-1
            0006   0x0019B0   43 32 04 00   Move                 r50, r4       r50 = 1
            0007   0x0019B8   1C 02 02 02   CallFf               r2, r2, 2     r2 = get-spawner-position(snd-pos-nor-apartment-door-close-1, 1)
            0008   0x0019C0   0C 03 00 00   LoadU16Imm           r3, 0         r3 = 0
            0009   0x0019C8   0C 04 00 00   LoadU16Imm           r4, 0         r4 = 0
            000A   0x0019D0   43 31 01 00   Move                 r49, r1       r49 = sfx-igc-nor-ambush-door-upstairs
            000B   0x0019D8   43 32 02 00   Move                 r50, r2       r50 = RET_get-spawner-position
            000C   0x0019E0   43 33 03 00   Move                 r51, r3       r51 = 0
            000D   0x0019E8   43 34 04 00   Move                 r52, r4       r52 = 0
            000E   0x0019F0   1C 00 00 04   CallFf               r0, r0, 4     r0 = play-sound-at-position(sfx-igc-nor-ambush-door-upstairs, RET_get-spawner-position, 0, 0)
            000F   0x0019F8   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001A00    function: play-sound-at-position
            0001   0x001A08    sid: sfx-igc-nor-ambush-door-upstairs
            0002   0x001A10    function: get-spawner-position
            0003   0x001A18    sid: snd-pos-nor-apartment-door-close-1
          }
          {
            0000   0x0011D0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x0011D8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <complete>
            0002   0x0011E0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x0011E8   43 31 01 00   Move                 r49, r1       r49 = complete
            0004   0x0011F0   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x0011F8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            0006   0x001200   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001208    function: go
            0001   0x001210    sid: complete
          }
        }

      }
    } END STATE play-sound-window

    STATE play-sound-stairwell {
      ON start {
        TRACK main {
          {
            0000   0x001AE8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <send-event>
            0001   0x001AF0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <vox-hear-ambush-door>
            0002   0x001AF8   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <ss-vox-nor-ellie-alone-streets-1>
            0003   0x001B00   43 31 01 00   Move                 r49, r1       r49 = vox-hear-ambush-door
            0004   0x001B08   43 32 02 00   Move                 r50, r2       r50 = ss-vox-nor-ellie-alone-streets-1
            0005   0x001B10   1C 00 00 02   CallFf               r0, r0, 2     r0 = send-event(vox-hear-ambush-door, ss-vox-nor-ellie-alone-streets-1)
            0006   0x001B18   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001B20    function: send-event
            0001   0x001B28    sid: vox-hear-ambush-door
            0002   0x001B30    sid: ss-vox-nor-ellie-alone-streets-1
          }
          {
            0000   0x001250   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <play-sound-at-position>
            0001   0x001258   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <sfx-igc-nor-ambush-door-upstairs-staircase>
            0002   0x001260   15 02 02 00   LookupPointer        r2, 2         r2 = ST[2] -> <get-spawner-position>
            0003   0x001268   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <snd-pos-nor-apartment-door-close-1>
            0004   0x001270   0C 04 01 00   LoadU16Imm           r4, 1         r4 = 1
            0005   0x001278   43 31 03 00   Move                 r49, r3       r49 = snd-pos-nor-apartment-door-close-1
            0006   0x001280   43 32 04 00   Move                 r50, r4       r50 = 1
            0007   0x001288   1C 02 02 02   CallFf               r2, r2, 2     r2 = get-spawner-position(snd-pos-nor-apartment-door-close-1, 1)
            0008   0x001290   0C 03 00 00   LoadU16Imm           r3, 0         r3 = 0
            0009   0x001298   0C 04 00 00   LoadU16Imm           r4, 0         r4 = 0
            000A   0x0012A0   43 31 01 00   Move                 r49, r1       r49 = sfx-igc-nor-ambush-door-upstairs-staircase
            000B   0x0012A8   43 32 02 00   Move                 r50, r2       r50 = RET_get-spawner-position
            000C   0x0012B0   43 33 03 00   Move                 r51, r3       r51 = 0
            000D   0x0012B8   43 34 04 00   Move                 r52, r4       r52 = 0
            000E   0x0012C0   1C 00 00 04   CallFf               r0, r0, 4     r0 = play-sound-at-position(sfx-igc-nor-ambush-door-upstairs-staircase, RET_get-spawner-position, 0, 0)
            000F   0x0012C8   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x0012D0    function: play-sound-at-position
            0001   0x0012D8    sid: sfx-igc-nor-ambush-door-upstairs-staircase
            0002   0x0012E0    function: get-spawner-position
            0003   0x0012E8    sid: snd-pos-nor-apartment-door-close-1
          }
          {
            0000   0x001218   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait>
            0001   0x001220   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <1.750000>
            0002   0x001228   43 31 01 00   Move                 r49, r1       r49 = 1.750000
            0003   0x001230   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait(1.750000)
            0004   0x001238   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001240    function: wait
            0001   0x001248    float: 1.750000
          }
          {
            0000   0x001920   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <set-boolean>
            0001   0x001928   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <uneasy-at-door-sound>
            0002   0x001930   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001938   4A 03 02 00   LoadStaticU64Imm     r3, 2         r3 = ST[2] -> <self>
            0004   0x001940   43 31 01 00   Move                 r49, r1       r49 = uneasy-at-door-sound
            0005   0x001948   43 32 02 00   Move                 r50, r2       r50 = 1
            0006   0x001950   43 33 03 00   Move                 r51, r3       r51 = self
            0007   0x001958   1C 00 00 03   CallFf               r0, r0, 3     r0 = set-boolean(uneasy-at-door-sound, 1, self)
            0008   0x001960   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001968    function: set-boolean
            0001   0x001970    sid: uneasy-at-door-sound
            0002   0x001978    sid: self
          }
          {
            0000   0x001780   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <get-player-weapon-id>
            0001   0x001788   1C 00 00 00   CallFf               r0, r0, 0     r0 = get-player-weapon-id()
            0002   0x001790   0C 01 00 00   LoadU16Imm           r1, 0         r1 = 0
            0003   0x001798   1D 00 00 01   IEqual               r0, r0, r1    r0 = r0 == r1
            0004   0x0017A0   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 => L_RETURN_0
            0005   0x0017A8   15 00 01 00   LookupPointer        r0, 1         r0 = ST[1] -> <player-unholster-weapon-by-slot>
            0006   0x0017B0   0C 01 02 00   LoadU16Imm           r1, 2         r1 = 2
            0007   0x0017B8   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0008   0x0017C0   40 03 02 00   LoadStaticFloatImm   r3, 2         r3 = ST[2] -> <0.000000>
            0009   0x0017C8   43 31 01 00   Move                 r49, r1       r49 = 2
            000A   0x0017D0   43 32 02 00   Move                 r50, r2       r50 = 0
            000B   0x0017D8   43 33 03 00   Move                 r51, r3       r51 = 0.000000
            000C   0x0017E0   1B 00 00 03   Call                 r0, r0, 3     r0 = player-unholster-weapon-by-slot(2, 0, 0.000000)
            000D   0x0017E8   2D 0F 00 00   Branch               0xF           GOTO => L_RETURN
          L_RETURN_0:
            000E   0x0017F0   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            000F   0x0017F8   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001800    function: get-player-weapon-id
            0001   0x001808    function: player-unholster-weapon-by-slot
            0002   0x001810    float: 0.000000
          }
          {
            0000   0x001CF8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait>
            0001   0x001D00   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <10.000000>
            0002   0x001D08   43 31 01 00   Move                 r49, r1       r49 = 10.000000
            0003   0x001D10   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait(10.000000)
            0004   0x001D18   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001D20    function: wait
            0001   0x001D28    float: 10.000000
          }
          {
            0000   0x001818   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <set-boolean>
            0001   0x001820   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <uneasy-at-door-sound>
            0002   0x001828   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0003   0x001830   4A 03 02 00   LoadStaticU64Imm     r3, 2         r3 = ST[2] -> <self>
            0004   0x001838   43 31 01 00   Move                 r49, r1       r49 = uneasy-at-door-sound
            0005   0x001840   43 32 02 00   Move                 r50, r2       r50 = 0
            0006   0x001848   43 33 03 00   Move                 r51, r3       r51 = self
            0007   0x001850   1C 00 00 03   CallFf               r0, r0, 3     r0 = set-boolean(uneasy-at-door-sound, 0, self)
            0008   0x001858   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001860    function: set-boolean
            0001   0x001868    sid: uneasy-at-door-sound
            0002   0x001870    sid: self
          }
          {
            0000   0x0011D0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x0011D8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <complete>
            0002   0x0011E0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x0011E8   43 31 01 00   Move                 r49, r1       r49 = complete
            0004   0x0011F0   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x0011F8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            0006   0x001200   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001208    function: go
            0001   0x001210    sid: complete
          }
        }

      }
      ON update {
        TRACK main {
          {
            0000   0x001C78   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <get-boolean>
            0001   0x001C80   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <uneasy-at-door-sound>
            0002   0x001C88   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <self>
            0003   0x001C90   43 31 01 00   Move                 r49, r1       r49 = uneasy-at-door-sound
            0004   0x001C98   43 32 02 00   Move                 r50, r2       r50 = self
            0005   0x001CA0   1C 00 00 02   CallFf               r0, r0, 2     r0 = get-boolean(symbol: uneasy-at-door-sound, location: self)
            0006   0x001CA8   2F 0A 00 00   BranchIfNot          r0, 0xA       IF NOT r0 => L_RETURN_0
            0007   0x001CB0   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <disallow-normal-tension>
            0008   0x001CB8   1C 00 00 00   CallFf               r0, r0, 0     r0 = disallow-normal-tension()
            0009   0x001CC0   2D 0B 00 00   Branch               0xB           GOTO => L_RETURN
          L_RETURN_0:
            000A   0x001CC8   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
          L_RETURN:
            000B   0x001CD0   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001CD8    function: get-boolean(sid, sid) -> bool
            0001   0x001CE0    sid: uneasy-at-door-sound
            0002   0x001CE8    sid: self
            0003   0x001CF0    function: disallow-normal-tension
          }
        }

      }
    } END STATE play-sound-stairwell

    STATE play-sound-secret-apt {
      ON start {
        TRACK main {
          {
            0000   0x001C40   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait>
            0001   0x001C48   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <0.900000>
            0002   0x001C50   43 31 01 00   Move                 r49, r1       r49 = 0.900000
            0003   0x001C58   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait(0.900000)
            0004   0x001C60   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001C68    function: wait
            0001   0x001C70    float: 0.900000
          }
          {
            0000   0x001980   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <play-sound-at-position>
            0001   0x001988   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <sfx-igc-nor-ambush-door-upstairs>
            0002   0x001990   15 02 02 00   LookupPointer        r2, 2         r2 = ST[2] -> <get-spawner-position>
            0003   0x001998   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <snd-pos-nor-apartment-door-close-1>
            0004   0x0019A0   0C 04 01 00   LoadU16Imm           r4, 1         r4 = 1
            0005   0x0019A8   43 31 03 00   Move                 r49, r3       r49 = snd-pos-nor-apartment-door-close-1
            0006   0x0019B0   43 32 04 00   Move                 r50, r4       r50 = 1
            0007   0x0019B8   1C 02 02 02   CallFf               r2, r2, 2     r2 = get-spawner-position(snd-pos-nor-apartment-door-close-1, 1)
            0008   0x0019C0   0C 03 00 00   LoadU16Imm           r3, 0         r3 = 0
            0009   0x0019C8   0C 04 00 00   LoadU16Imm           r4, 0         r4 = 0
            000A   0x0019D0   43 31 01 00   Move                 r49, r1       r49 = sfx-igc-nor-ambush-door-upstairs
            000B   0x0019D8   43 32 02 00   Move                 r50, r2       r50 = RET_get-spawner-position
            000C   0x0019E0   43 33 03 00   Move                 r51, r3       r51 = 0
            000D   0x0019E8   43 34 04 00   Move                 r52, r4       r52 = 0
            000E   0x0019F0   1C 00 00 04   CallFf               r0, r0, 4     r0 = play-sound-at-position(sfx-igc-nor-ambush-door-upstairs, RET_get-spawner-position, 0, 0)
            000F   0x0019F8   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001A00    function: play-sound-at-position
            0001   0x001A08    sid: sfx-igc-nor-ambush-door-upstairs
            0002   0x001A10    function: get-spawner-position
            0003   0x001A18    sid: snd-pos-nor-apartment-door-close-1
          }
          {
            0000   0x0011D0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x0011D8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <complete>
            0002   0x0011E0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x0011E8   43 31 01 00   Move                 r49, r1       r49 = complete
            0004   0x0011F0   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x0011F8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            0006   0x001200   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x001208    function: go
            0001   0x001210    sid: complete
          }
        }

      }
    } END STATE play-sound-secret-apt

    STATE complete {
    } END STATE complete

}
