####################################################################################################
#                                                                                                  #
#   generated by dconstruct ver. 1.52.0                                                            #
#   listing for file: .\game_dumps\t2r\dc1\part-module\part-level-flo-flooded-street-skybridge-wide.bin#
#   filesize: 36884 bytes                                                                          #
#   total entries: 20                                                                              #
#   functions: 0                                                                                   #
#   has state script: false                                                                        #
#   game type: t2r                                                                                 #
#   optimizations enabled: true                                                                    #
#                                                                                                  #
####################################################################################################



##############################  ENTRY 0  ##############################

waterfall-base-lg/full_optimization = particle-effect-desc [0x00220] {
  [0] int: 2776
  [1] int: 1267459234
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: waterfall-base-lg/full_optimization
  [7] int: 0
  [8] int: 0
  [9] sid: waterfall-base-lg
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 393346
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 8
  [26] int: 512
  [27] sid: general/particles/smoke-steam/steam-mist-swirl:default
  [28] int: 0
  [29] int: 1572864
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 196611
  [44] sid: #00160000000E007B
  [45] int: 797
  [46] int: 1507351
  [47] int: 83
  [48] int: 0
  [49] array [0x300] {size: 83} {
    [0] anonymous struct [0x4d8] {
    }
    [1] anonymous struct [0x4d8] {
    }
    [2] anonymous struct [0x4d8] {
    }
    [3] anonymous struct [0x4d8] {
    }
    [4] anonymous struct [0x4d8] {
    }
    [5] anonymous struct [0x4d8] {
    }
    [6] anonymous struct [0x4d8] {
    }
    [7] anonymous struct [0x4d8] {
    }
    [8] anonymous struct [0x4d8] {
    }
    [9] anonymous struct [0x4d8] {
    }
    [10] anonymous struct [0x4d8] {
    }
    [11] anonymous struct [0x4d8] {
    }
    [12] anonymous struct [0x4d8] {
    }
    [13] anonymous struct [0x4d8] {
    }
    [14] anonymous struct [0x4d8] {
    }
    [15] anonymous struct [0x4d8] {
    }
    [16] anonymous struct [0x4d8] {
    }
    [17] anonymous struct [0x4d8] {
    }
    [18] anonymous struct [0x4d8] {
    }
    [19] anonymous struct [0x4d8] {
    }
    [20] anonymous struct [0x4d8] {
    }
    [21] anonymous struct [0x4d8] {
    }
    [22] anonymous struct [0x4d8] {
    }
    [23] anonymous struct [0x4d8] {
    }
    [24] anonymous struct [0x4d8] {
    }
    [25] anonymous struct [0x4d8] {
    }
    [26] anonymous struct [0x4d8] {
    }
    [27] anonymous struct [0x4d8] {
    }
    [28] anonymous struct [0x4d8] {
    }
    [29] anonymous struct [0x4d8] {
    }
    [30] anonymous struct [0x4d8] {
    }
    [31] anonymous struct [0x4d8] {
    }
    [32] anonymous struct [0x4d8] {
    }
    [33] anonymous struct [0x4d8] {
    }
    [34] anonymous struct [0x4d8] {
    }
    [35] anonymous struct [0x4d8] {
    }
    [36] anonymous struct [0x4d8] {
    }
    [37] anonymous struct [0x4d8] {
    }
    [38] anonymous struct [0x4d8] {
    }
    [39] anonymous struct [0x4d8] {
    }
    [40] anonymous struct [0x4d8] {
    }
    [41] anonymous struct [0x4d8] {
    }
    [42] anonymous struct [0x4d8] {
    }
    [43] anonymous struct [0x4d8] {
    }
    [44] anonymous struct [0x4d8] {
    }
    [45] anonymous struct [0x4d8] {
    }
    [46] anonymous struct [0x4d8] {
    }
    [47] anonymous struct [0x4d8] {
    }
    [48] anonymous struct [0x4d8] {
    }
    [49] anonymous struct [0x4d8] {
    }
    [50] anonymous struct [0x4d8] {
    }
    [51] anonymous struct [0x4d8] {
    }
    [52] anonymous struct [0x4d8] {
    }
    [53] anonymous struct [0x4d8] {
    }
    [54] anonymous struct [0x4d8] {
    }
    [55] anonymous struct [0x4d8] {
    }
    [56] anonymous struct [0x4d8] {
    }
    [57] anonymous struct [0x4d8] {
    }
    [58] anonymous struct [0x4d8] {
    }
    [59] anonymous struct [0x4d8] {
    }
    [60] anonymous struct [0x4d8] {
    }
    [61] anonymous struct [0x4d8] {
    }
    [62] anonymous struct [0x4d8] {
    }
    [63] anonymous struct [0x4d8] {
    }
    [64] anonymous struct [0x4d8] {
    }
    [65] anonymous struct [0x4d8] {
    }
    [66] anonymous struct [0x4d8] {
    }
    [67] anonymous struct [0x4d8] {
    }
    [68] anonymous struct [0x4d8] {
    }
    [69] anonymous struct [0x4d8] {
    }
    [70] anonymous struct [0x4d8] {
    }
    [71] anonymous struct [0x4d8] {
    }
    [72] anonymous struct [0x4d8] {
    }
    [73] anonymous struct [0x4d8] {
    }
    [74] anonymous struct [0x4d8] {
    }
    [75] anonymous struct [0x4d8] {
    }
    [76] anonymous struct [0x4d8] {
    }
    [77] anonymous struct [0x4d8] {
    }
    [78] anonymous struct [0x4d8] {
    }
    [79] anonymous struct [0x4d8] {
    }
    [80] anonymous struct [0x4d8] {
    }
    [81] anonymous struct [0x4d8] {
    }
    [82] anonymous struct [0x4d8] {
    }
  }
  [50] array [0x308] {size: (125916520, 125916504) (*invalid*)} {  }
  [51] array [0x310] {size: (125916544, 125916512) (*invalid*)} {  }
  [52] array [0x318] {size: (125916672, 125916520) (*invalid*)} {  }
  [53] array [0x320] {size: (125917176, 125916544) (*invalid*)} {  }
  [54] array [0x328] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x340] {size: 0} {
  }
  [60] array [0x348] {size: (125917904, 125917240) (*invalid*)} {  }
  [61] volume-emitter-node [0x00A50] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 852074
    [5] int: 2
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] float: 1.00
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 2.00
    [17] float: 1.00
    [18] float: 2.00
    [19] float: 1.00
    [20] int: 0
    [21] float: -1.00
    [22] int: 0
    [23] int: 0
    [24] float: 0.20
    [25] int: 0
    [26] float: 4.00
    [27] int: 0
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125918136, returning
  [63] array* [0x00B38] {
    [0] anonymous array with invalid size 125918288, returning
    [1] volume-axis-field-node [0x00BD0] {
      [0] int: 6
      [1] int: 33555200
      [2] float: 1.00
      [3] float: 1.00
      [4] float: -1.00
      [5] int: 0
      [6] int: 0
      [7] int: 0
      [8] int: 0
      [9] float: -1.00
      [10] int: 0
      [11] float: 1.00
      [12] int: 0
      [13] int: 0
      [14] int: 0
      [15] int: 0
      [16] float: 3.00
      [17] float: 1.00
      [18] float: 3.00
      [19] int: 0
      [20] float: 1.00
      [21] int: 0
      [22] int: 0
      [23] int: 0
      [24] int: 0
      [25] int: 0
      [26] int: 0
      [27] float: 3.00
      [28] int: 0
      [29] int: 0
      [30] int: 0
      [31] int: 0
      [32] int: 0
      [33] int: 0
    }
    [2] volume-axis-field-node [0x00C60] {
      [0] int: 6
      [1] int: 33555200
      [2] float: 1.00
      [3] float: 1.00
      [4] float: -1.00
      [5] int: 131193
      [6] int: 0
      [7] int: 0
      [8] int: 0
      [9] float: -2.00
      [10] int: 0
      [11] float: 1.00
      [12] int: 0
      [13] int: 0
      [14] int: 0
      [15] int: 0
      [16] float: 4.00
      [17] float: 2.00
      [18] float: 4.00
      [19] int: 0
      [20] int: 0
      [21] float: 1.00
      [22] int: 0
      [23] int: 0
      [24] int: 0
      [25] float: 2.00
      [26] int: 0
      [27] int: 0
      [28] int: 0
      [29] int: 0
      [30] int: 0
      [31] int: 0
    }
    [3] int: 0
    [4] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 516
  [111] int: 66562
  [112] int: 0
  [113] int: 0
  [114] float: 150.00
  [115] float: 165.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 1.00
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] float: 150.00
  [142] float: 165.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 1  ##############################

**exclude-from-global-namespace** = boolean [0x00CE8] {
  [0] int: 1
  [1] int: 0
  [2] int: 0
  [3] int: 0
}


##############################  ENTRY 2  ##############################

waterfall-base-lg/main_mist_no_optimization = particle-effect-desc [0x00D00] {
  [0] int: 2775
  [1] int: 1420193067
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: waterfall-base-lg/main_mist_no_optimization
  [7] int: 0
  [8] int: 0
  [9] sid: waterfall-base-lg
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 393346
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 8
  [26] int: 512
  [27] sid: general/particles/smoke-steam/steam-mist-swirl:default
  [28] int: 0
  [29] int: 1572864
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 196611
  [44] sid: #00160000000D007B
  [45] int: 797
  [46] int: 1507351
  [47] int: 83
  [48] int: 0
  [49] array [0xde0] {size: 83} {
    [0] anonymous struct [0xfb8] {
    }
    [1] anonymous struct [0xfb8] {
    }
    [2] anonymous struct [0xfb8] {
    }
    [3] anonymous struct [0xfb8] {
    }
    [4] anonymous struct [0xfb8] {
    }
    [5] anonymous struct [0xfb8] {
    }
    [6] anonymous struct [0xfb8] {
    }
    [7] anonymous struct [0xfb8] {
    }
    [8] anonymous struct [0xfb8] {
    }
    [9] anonymous struct [0xfb8] {
    }
    [10] anonymous struct [0xfb8] {
    }
    [11] anonymous struct [0xfb8] {
    }
    [12] anonymous struct [0xfb8] {
    }
    [13] anonymous struct [0xfb8] {
    }
    [14] anonymous struct [0xfb8] {
    }
    [15] anonymous struct [0xfb8] {
    }
    [16] anonymous struct [0xfb8] {
    }
    [17] anonymous struct [0xfb8] {
    }
    [18] anonymous struct [0xfb8] {
    }
    [19] anonymous struct [0xfb8] {
    }
    [20] anonymous struct [0xfb8] {
    }
    [21] anonymous struct [0xfb8] {
    }
    [22] anonymous struct [0xfb8] {
    }
    [23] anonymous struct [0xfb8] {
    }
    [24] anonymous struct [0xfb8] {
    }
    [25] anonymous struct [0xfb8] {
    }
    [26] anonymous struct [0xfb8] {
    }
    [27] anonymous struct [0xfb8] {
    }
    [28] anonymous struct [0xfb8] {
    }
    [29] anonymous struct [0xfb8] {
    }
    [30] anonymous struct [0xfb8] {
    }
    [31] anonymous struct [0xfb8] {
    }
    [32] anonymous struct [0xfb8] {
    }
    [33] anonymous struct [0xfb8] {
    }
    [34] anonymous struct [0xfb8] {
    }
    [35] anonymous struct [0xfb8] {
    }
    [36] anonymous struct [0xfb8] {
    }
    [37] anonymous struct [0xfb8] {
    }
    [38] anonymous struct [0xfb8] {
    }
    [39] anonymous struct [0xfb8] {
    }
    [40] anonymous struct [0xfb8] {
    }
    [41] anonymous struct [0xfb8] {
    }
    [42] anonymous struct [0xfb8] {
    }
    [43] anonymous struct [0xfb8] {
    }
    [44] anonymous struct [0xfb8] {
    }
    [45] anonymous struct [0xfb8] {
    }
    [46] anonymous struct [0xfb8] {
    }
    [47] anonymous struct [0xfb8] {
    }
    [48] anonymous struct [0xfb8] {
    }
    [49] anonymous struct [0xfb8] {
    }
    [50] anonymous struct [0xfb8] {
    }
    [51] anonymous struct [0xfb8] {
    }
    [52] anonymous struct [0xfb8] {
    }
    [53] anonymous struct [0xfb8] {
    }
    [54] anonymous struct [0xfb8] {
    }
    [55] anonymous struct [0xfb8] {
    }
    [56] anonymous struct [0xfb8] {
    }
    [57] anonymous struct [0xfb8] {
    }
    [58] anonymous struct [0xfb8] {
    }
    [59] anonymous struct [0xfb8] {
    }
    [60] anonymous struct [0xfb8] {
    }
    [61] anonymous struct [0xfb8] {
    }
    [62] anonymous struct [0xfb8] {
    }
    [63] anonymous struct [0xfb8] {
    }
    [64] anonymous struct [0xfb8] {
    }
    [65] anonymous struct [0xfb8] {
    }
    [66] anonymous struct [0xfb8] {
    }
    [67] anonymous struct [0xfb8] {
    }
    [68] anonymous struct [0xfb8] {
    }
    [69] anonymous struct [0xfb8] {
    }
    [70] anonymous struct [0xfb8] {
    }
    [71] anonymous struct [0xfb8] {
    }
    [72] anonymous struct [0xfb8] {
    }
    [73] anonymous struct [0xfb8] {
    }
    [74] anonymous struct [0xfb8] {
    }
    [75] anonymous struct [0xfb8] {
    }
    [76] anonymous struct [0xfb8] {
    }
    [77] anonymous struct [0xfb8] {
    }
    [78] anonymous struct [0xfb8] {
    }
    [79] anonymous struct [0xfb8] {
    }
    [80] anonymous struct [0xfb8] {
    }
    [81] anonymous struct [0xfb8] {
    }
    [82] anonymous struct [0xfb8] {
    }
  }
  [50] array [0xde8] {size: (125919304, 125919288) (*invalid*)} {  }
  [51] array [0xdf0] {size: (125919328, 125919296) (*invalid*)} {  }
  [52] array [0xdf8] {size: (125919456, 125919304) (*invalid*)} {  }
  [53] array [0xe00] {size: (125919960, 125919328) (*invalid*)} {  }
  [54] array [0xe08] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0xe20] {size: 0} {
  }
  [60] array [0xe28] {size: (125920688, 125920024) (*invalid*)} {  }
  [61] volume-emitter-node [0x01530] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 852074
    [5] int: 2
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] float: 1.00
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 2.00
    [17] float: 1.00
    [18] float: 2.00
    [19] float: 1.00
    [20] int: 0
    [21] float: -1.00
    [22] int: 0
    [23] int: 0
    [24] float: 0.20
    [25] int: 0
    [26] float: 4.00
    [27] int: 0
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125920920, returning
  [63] array* [0x01618] {
    [0] anonymous array with invalid size 125921072, returning
    [1] volume-axis-field-node [0x016B0] {
      [0] int: 6
      [1] int: 33555200
      [2] float: 1.00
      [3] float: 1.00
      [4] float: -1.00
      [5] int: 0
      [6] int: 0
      [7] int: 0
      [8] int: 0
      [9] float: -1.00
      [10] int: 0
      [11] float: 1.00
      [12] int: 0
      [13] int: 0
      [14] int: 0
      [15] int: 0
      [16] float: 3.00
      [17] float: 1.00
      [18] float: 3.00
      [19] int: 0
      [20] float: 1.00
      [21] int: 0
      [22] int: 0
      [23] int: 0
      [24] int: 0
      [25] int: 0
      [26] int: 0
      [27] float: 3.00
      [28] int: 0
      [29] int: 0
      [30] int: 0
      [31] int: 0
      [32] int: 0
      [33] int: 0
    }
    [2] volume-axis-field-node [0x01740] {
      [0] int: 6
      [1] int: 33555200
      [2] float: 1.00
      [3] float: 1.00
      [4] float: -1.00
      [5] int: 131193
      [6] int: 0
      [7] int: 0
      [8] int: 0
      [9] float: -2.00
      [10] int: 0
      [11] float: 1.00
      [12] int: 0
      [13] int: 0
      [14] int: 0
      [15] int: 0
      [16] float: 4.00
      [17] float: 2.00
      [18] float: 4.00
      [19] int: 0
      [20] int: 0
      [21] float: 1.00
      [22] int: 0
      [23] int: 0
      [24] int: 0
      [25] float: 2.00
      [26] int: 0
      [27] int: 0
      [28] int: 0
      [29] int: 0
      [30] int: 0
      [31] int: 0
      [32] int: 0
      [33] int: 0
    }
    [3] int: 0
    [4] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 1028
  [111] int: 66561
  [112] int: 0
  [113] int: 0
  [114] float: 150.00
  [115] float: 165.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 1.00
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] float: 150.00
  [142] float: 165.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 3  ##############################

waterfall-variable-density/wave_splash_half_res = particle-effect-desc [0x017D0] {
  [0] int: 2864
  [1] int: -2087293176
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: waterfall-variable-density/wave_splash_half_res
  [7] int: 0
  [8] int: 0
  [9] sid: waterfall-variable-density
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 393346
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 9
  [26] int: 512
  [27] sid: general/particles/water/water-burst-04:default
  [28] int: 0
  [29] int: 1703936
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] float: 1.00
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 458758
  [44] sid: #001900000011009D
  [45] int: 288
  [46] int: 3145776
  [47] int: 74
  [48] int: 0
  [49] array [0x18b0] {size: 74} {
    [0] anonymous struct [0x1a88] {
    }
    [1] anonymous struct [0x1a88] {
    }
    [2] anonymous struct [0x1a88] {
    }
    [3] anonymous struct [0x1a88] {
    }
    [4] anonymous struct [0x1a88] {
    }
    [5] anonymous struct [0x1a88] {
    }
    [6] anonymous struct [0x1a88] {
    }
    [7] anonymous struct [0x1a88] {
    }
    [8] anonymous struct [0x1a88] {
    }
    [9] anonymous struct [0x1a88] {
    }
    [10] anonymous struct [0x1a88] {
    }
    [11] anonymous struct [0x1a88] {
    }
    [12] anonymous struct [0x1a88] {
    }
    [13] anonymous struct [0x1a88] {
    }
    [14] anonymous struct [0x1a88] {
    }
    [15] anonymous struct [0x1a88] {
    }
    [16] anonymous struct [0x1a88] {
    }
    [17] anonymous struct [0x1a88] {
    }
    [18] anonymous struct [0x1a88] {
    }
    [19] anonymous struct [0x1a88] {
    }
    [20] anonymous struct [0x1a88] {
    }
    [21] anonymous struct [0x1a88] {
    }
    [22] anonymous struct [0x1a88] {
    }
    [23] anonymous struct [0x1a88] {
    }
    [24] anonymous struct [0x1a88] {
    }
    [25] anonymous struct [0x1a88] {
    }
    [26] anonymous struct [0x1a88] {
    }
    [27] anonymous struct [0x1a88] {
    }
    [28] anonymous struct [0x1a88] {
    }
    [29] anonymous struct [0x1a88] {
    }
    [30] anonymous struct [0x1a88] {
    }
    [31] anonymous struct [0x1a88] {
    }
    [32] anonymous struct [0x1a88] {
    }
    [33] anonymous struct [0x1a88] {
    }
    [34] anonymous struct [0x1a88] {
    }
    [35] anonymous struct [0x1a88] {
    }
    [36] anonymous struct [0x1a88] {
    }
    [37] anonymous struct [0x1a88] {
    }
    [38] anonymous struct [0x1a88] {
    }
    [39] anonymous struct [0x1a88] {
    }
    [40] anonymous struct [0x1a88] {
    }
    [41] anonymous struct [0x1a88] {
    }
    [42] anonymous struct [0x1a88] {
    }
    [43] anonymous struct [0x1a88] {
    }
    [44] anonymous struct [0x1a88] {
    }
    [45] anonymous struct [0x1a88] {
    }
    [46] anonymous struct [0x1a88] {
    }
    [47] anonymous struct [0x1a88] {
    }
    [48] anonymous struct [0x1a88] {
    }
    [49] anonymous struct [0x1a88] {
    }
    [50] anonymous struct [0x1a88] {
    }
    [51] anonymous struct [0x1a88] {
    }
    [52] anonymous struct [0x1a88] {
    }
    [53] anonymous struct [0x1a88] {
    }
    [54] anonymous struct [0x1a88] {
    }
    [55] anonymous struct [0x1a88] {
    }
    [56] anonymous struct [0x1a88] {
    }
    [57] anonymous struct [0x1a88] {
    }
    [58] anonymous struct [0x1a88] {
    }
    [59] anonymous struct [0x1a88] {
    }
    [60] anonymous struct [0x1a88] {
    }
    [61] anonymous struct [0x1a88] {
    }
    [62] anonymous struct [0x1a88] {
    }
    [63] anonymous struct [0x1a88] {
    }
    [64] anonymous struct [0x1a88] {
    }
    [65] anonymous struct [0x1a88] {
    }
    [66] anonymous struct [0x1a88] {
    }
    [67] anonymous struct [0x1a88] {
    }
    [68] anonymous struct [0x1a88] {
    }
    [69] anonymous struct [0x1a88] {
    }
    [70] anonymous struct [0x1a88] {
    }
    [71] anonymous struct [0x1a88] {
    }
    [72] anonymous struct [0x1a88] {
    }
    [73] anonymous struct [0x1a88] {
    }
  }
  [50] array [0x18b8] {size: (125922072, 125922056) (*invalid*)} {  }
  [51] array [0x18c0] {size: (125922104, 125922064) (*invalid*)} {  }
  [52] array [0x18c8] {size: (125922392, 125922072) (*invalid*)} {  }
  [53] array [0x18d0] {size: (125923032, 125922104) (*invalid*)} {  }
  [54] array [0x18d8] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x18f0] {size: 0} {
  }
  [60] array [0x18f8] {size: (125923856, 125923112) (*invalid*)} {  }
  [61] volume-emitter-node [0x02190] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 2031738
    [5] int: 0
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.03
    [17] float: 0.03
    [18] float: 0.03
    [19] float: 1.00
    [20] int: 0
    [21] int: 0
    [22] float: 1.00
    [23] int: 0
    [24] float: 0.50
    [25] int: 0
    [26] float: 2.00
    [27] float: 1.50
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125924088, returning
  [63] array* [0x02278] {
    [0] anonymous array [0x2278] {size: 0} {
    }
    [1] int: 0
    [2] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 1540
  [111] int: 66561
  [112] int: 0
  [113] int: 0
  [114] float: 12.00
  [115] float: 15.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] float: 0.50
  [121] int: 917760
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.50
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] float: 15.00
  [142] float: 15.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 4  ##############################

flo-turbulent-foam-projection/foam = particle-effect-desc [0x02300] {
  [0] int: 1896
  [1] int: -632508401
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: flo-turbulent-foam-projection/foam
  [7] int: 0
  [8] int: 0
  [9] sid: flo-turbulent-foam-projection
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] sid: #0020030090000100
  [22] int: 0
  [23] int: 0
  [24] int: 7
  [25] int: 514
  [26] sid: general/particles/water/foam-proj-current:default
  [27] int: 0
  [28] int: 1703936
  [29] int: 1
  [30] int: 0
  [31] float: 100.00
  [32] float: 1.00
  [33] int: 0
  [34] int: 0
  [35] float: 1.00
  [36] float: 1.00
  [37] int: 0
  [38] int: 0
  [39] int: 0
  [40] float: -1.00
  [41] int: 0
  [42] int: 131074
  [43] sid: #0019000000050023
  [44] int: 27
  [45] int: 917518
  [46] int: 19
  [47] int: 0
  [48] array [0x23e0] {size: 19} {
    [0] anonymous struct [0x25b8] {
    }
    [1] anonymous struct [0x25b8] {
    }
    [2] anonymous struct [0x25b8] {
    }
    [3] anonymous struct [0x25b8] {
    }
    [4] anonymous struct [0x25b8] {
    }
    [5] anonymous struct [0x25b8] {
    }
    [6] anonymous struct [0x25b8] {
    }
    [7] anonymous struct [0x25b8] {
    }
    [8] anonymous struct [0x25b8] {
    }
    [9] anonymous struct [0x25b8] {
    }
    [10] anonymous struct [0x25b8] {
    }
    [11] anonymous struct [0x25b8] {
    }
    [12] anonymous struct [0x25b8] {
    }
    [13] anonymous struct [0x25b8] {
    }
    [14] anonymous struct [0x25b8] {
    }
    [15] anonymous struct [0x25b8] {
    }
    [16] anonymous struct [0x25b8] {
    }
    [17] anonymous struct [0x25b8] {
    }
    [18] anonymous struct [0x25b8] {
    }
  }
  [49] array [0x23e8] {size: (125924936, 125924920) (*invalid*)} {  }
  [50] array [0x23f0] {size: (125924952, 125924928) (*invalid*)} {  }
  [51] array [0x23f8] {size: (125925040, 125924936) (*invalid*)} {  }
  [52] array [0x2400] {size: (125925192, 125924952) (*invalid*)} {  }
  [53] array [0x2408] {size: 0} {
  }
  [54] int: 0
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] array [0x2420] {size: 0} {
  }
  [59] array [0x2428] {size: (125925888, 125925224) (*invalid*)} {  }
  [60] anonymous array with invalid size 125926016, returning
  [61] anonymous array with invalid size 125926104, returning
  [62] array* [0x02A58] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
  }
  [63] int: 0
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 8
  [70] int: 1
  [71] int: 0
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] float: 0.02
  [78] int: 0
  [79] float: 1.00
  [80] float: 1.00
  [81] int: 0
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] float: 1.00
  [88] float: -0.00
  [89] int: 0
  [90] float: 10.00
  [91] int: 0
  [92] int: 0
  [93] float: 0.02
  [94] int: 0
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 259
  [102] int: 0
  [103] int: 0
  [104] float: -1.00
  [105] int: 0
  [106] int: 0
  [107] float: -1.00
  [108] int: 0
  [109] int: 4
  [110] int: 66560
  [111] int: 0
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] float: 1.00
  [116] float: 1.00
  [117] float: -0.50
  [118] int: 0
  [119] int: 0
  [120] int: 917764
  [121] int: 1
  [122] int: 0
  [123] int: 0
  [124] int: 16842752
  [125] int: 0
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] float: -1.00
  [130] int: 65535
  [131] int: 0
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] float: 1.00
  [145] int: 0
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
}


##############################  ENTRY 5  ##############################

waterfall-variable-density/full_optimization = particle-effect-desc [0x02A70] {
  [0] int: 2856
  [1] int: -829473804
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: waterfall-variable-density/full_optimization
  [7] int: 0
  [8] int: 0
  [9] sid: waterfall-variable-density
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 393346
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 9
  [26] int: 512
  [27] sid: general/particles/water/water-burst-04:default
  [28] int: 0
  [29] int: 1703936
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] float: 1.00
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 458758
  [44] sid: #001900000011009A
  [45] int: 288
  [46] int: 3145776
  [47] int: 74
  [48] int: 0
  [49] array [0x2b50] {size: 74} {
    [0] anonymous struct [0x2d28] {
    }
    [1] anonymous struct [0x2d28] {
    }
    [2] anonymous struct [0x2d28] {
    }
    [3] anonymous struct [0x2d28] {
    }
    [4] anonymous struct [0x2d28] {
    }
    [5] anonymous struct [0x2d28] {
    }
    [6] anonymous struct [0x2d28] {
    }
    [7] anonymous struct [0x2d28] {
    }
    [8] anonymous struct [0x2d28] {
    }
    [9] anonymous struct [0x2d28] {
    }
    [10] anonymous struct [0x2d28] {
    }
    [11] anonymous struct [0x2d28] {
    }
    [12] anonymous struct [0x2d28] {
    }
    [13] anonymous struct [0x2d28] {
    }
    [14] anonymous struct [0x2d28] {
    }
    [15] anonymous struct [0x2d28] {
    }
    [16] anonymous struct [0x2d28] {
    }
    [17] anonymous struct [0x2d28] {
    }
    [18] anonymous struct [0x2d28] {
    }
    [19] anonymous struct [0x2d28] {
    }
    [20] anonymous struct [0x2d28] {
    }
    [21] anonymous struct [0x2d28] {
    }
    [22] anonymous struct [0x2d28] {
    }
    [23] anonymous struct [0x2d28] {
    }
    [24] anonymous struct [0x2d28] {
    }
    [25] anonymous struct [0x2d28] {
    }
    [26] anonymous struct [0x2d28] {
    }
    [27] anonymous struct [0x2d28] {
    }
    [28] anonymous struct [0x2d28] {
    }
    [29] anonymous struct [0x2d28] {
    }
    [30] anonymous struct [0x2d28] {
    }
    [31] anonymous struct [0x2d28] {
    }
    [32] anonymous struct [0x2d28] {
    }
    [33] anonymous struct [0x2d28] {
    }
    [34] anonymous struct [0x2d28] {
    }
    [35] anonymous struct [0x2d28] {
    }
    [36] anonymous struct [0x2d28] {
    }
    [37] anonymous struct [0x2d28] {
    }
    [38] anonymous struct [0x2d28] {
    }
    [39] anonymous struct [0x2d28] {
    }
    [40] anonymous struct [0x2d28] {
    }
    [41] anonymous struct [0x2d28] {
    }
    [42] anonymous struct [0x2d28] {
    }
    [43] anonymous struct [0x2d28] {
    }
    [44] anonymous struct [0x2d28] {
    }
    [45] anonymous struct [0x2d28] {
    }
    [46] anonymous struct [0x2d28] {
    }
    [47] anonymous struct [0x2d28] {
    }
    [48] anonymous struct [0x2d28] {
    }
    [49] anonymous struct [0x2d28] {
    }
    [50] anonymous struct [0x2d28] {
    }
    [51] anonymous struct [0x2d28] {
    }
    [52] anonymous struct [0x2d28] {
    }
    [53] anonymous struct [0x2d28] {
    }
    [54] anonymous struct [0x2d28] {
    }
    [55] anonymous struct [0x2d28] {
    }
    [56] anonymous struct [0x2d28] {
    }
    [57] anonymous struct [0x2d28] {
    }
    [58] anonymous struct [0x2d28] {
    }
    [59] anonymous struct [0x2d28] {
    }
    [60] anonymous struct [0x2d28] {
    }
    [61] anonymous struct [0x2d28] {
    }
    [62] anonymous struct [0x2d28] {
    }
    [63] anonymous struct [0x2d28] {
    }
    [64] anonymous struct [0x2d28] {
    }
    [65] anonymous struct [0x2d28] {
    }
    [66] anonymous struct [0x2d28] {
    }
    [67] anonymous struct [0x2d28] {
    }
    [68] anonymous struct [0x2d28] {
    }
    [69] anonymous struct [0x2d28] {
    }
    [70] anonymous struct [0x2d28] {
    }
    [71] anonymous struct [0x2d28] {
    }
    [72] anonymous struct [0x2d28] {
    }
    [73] anonymous struct [0x2d28] {
    }
  }
  [50] array [0x2b58] {size: (125926840, 125926824) (*invalid*)} {  }
  [51] array [0x2b60] {size: (125926872, 125926832) (*invalid*)} {  }
  [52] array [0x2b68] {size: (125927160, 125926840) (*invalid*)} {  }
  [53] array [0x2b70] {size: (125927784, 125926872) (*invalid*)} {  }
  [54] array [0x2b78] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x2b90] {size: 0} {
  }
  [60] array [0x2b98] {size: (125928608, 125927864) (*invalid*)} {  }
  [61] volume-emitter-node [0x03420] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 1835130
    [5] int: 0
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.03
    [17] float: 0.03
    [18] float: 0.03
    [19] float: 1.00
    [20] int: 0
    [21] int: 0
    [22] float: 1.00
    [23] int: 0
    [24] float: 0.50
    [25] int: 0
    [26] float: 2.00
    [27] float: 1.50
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125928840, returning
  [63] array* [0x03508] {
    [0] anonymous array [0x3508] {size: 0} {
    }
    [1] int: 0
    [2] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 516
  [111] int: 66561
  [112] int: 0
  [113] int: 0
  [114] float: 150.00
  [115] float: 165.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] float: 0.50
  [121] int: 917760
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.50
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] float: 150.00
  [142] float: 165.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 6  ##############################

waterfall-base-lg/main_mist = particle-effect-desc [0x03590] {
  [0] int: 2784
  [1] int: -2140971518
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: waterfall-base-lg/main_mist
  [7] int: 0
  [8] int: 0
  [9] sid: waterfall-base-lg
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 393346
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 8
  [26] int: 512
  [27] sid: general/particles/smoke-steam/steam-mist-swirl:default
  [28] int: 0
  [29] int: 1572864
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 196611
  [44] sid: #00160000000E0080
  [45] int: 797
  [46] int: 1507351
  [47] int: 83
  [48] int: 0
  [49] array [0x3670] {size: 83} {
    [0] anonymous struct [0x3848] {
    }
    [1] anonymous struct [0x3848] {
    }
    [2] anonymous struct [0x3848] {
    }
    [3] anonymous struct [0x3848] {
    }
    [4] anonymous struct [0x3848] {
    }
    [5] anonymous struct [0x3848] {
    }
    [6] anonymous struct [0x3848] {
    }
    [7] anonymous struct [0x3848] {
    }
    [8] anonymous struct [0x3848] {
    }
    [9] anonymous struct [0x3848] {
    }
    [10] anonymous struct [0x3848] {
    }
    [11] anonymous struct [0x3848] {
    }
    [12] anonymous struct [0x3848] {
    }
    [13] anonymous struct [0x3848] {
    }
    [14] anonymous struct [0x3848] {
    }
    [15] anonymous struct [0x3848] {
    }
    [16] anonymous struct [0x3848] {
    }
    [17] anonymous struct [0x3848] {
    }
    [18] anonymous struct [0x3848] {
    }
    [19] anonymous struct [0x3848] {
    }
    [20] anonymous struct [0x3848] {
    }
    [21] anonymous struct [0x3848] {
    }
    [22] anonymous struct [0x3848] {
    }
    [23] anonymous struct [0x3848] {
    }
    [24] anonymous struct [0x3848] {
    }
    [25] anonymous struct [0x3848] {
    }
    [26] anonymous struct [0x3848] {
    }
    [27] anonymous struct [0x3848] {
    }
    [28] anonymous struct [0x3848] {
    }
    [29] anonymous struct [0x3848] {
    }
    [30] anonymous struct [0x3848] {
    }
    [31] anonymous struct [0x3848] {
    }
    [32] anonymous struct [0x3848] {
    }
    [33] anonymous struct [0x3848] {
    }
    [34] anonymous struct [0x3848] {
    }
    [35] anonymous struct [0x3848] {
    }
    [36] anonymous struct [0x3848] {
    }
    [37] anonymous struct [0x3848] {
    }
    [38] anonymous struct [0x3848] {
    }
    [39] anonymous struct [0x3848] {
    }
    [40] anonymous struct [0x3848] {
    }
    [41] anonymous struct [0x3848] {
    }
    [42] anonymous struct [0x3848] {
    }
    [43] anonymous struct [0x3848] {
    }
    [44] anonymous struct [0x3848] {
    }
    [45] anonymous struct [0x3848] {
    }
    [46] anonymous struct [0x3848] {
    }
    [47] anonymous struct [0x3848] {
    }
    [48] anonymous struct [0x3848] {
    }
    [49] anonymous struct [0x3848] {
    }
    [50] anonymous struct [0x3848] {
    }
    [51] anonymous struct [0x3848] {
    }
    [52] anonymous struct [0x3848] {
    }
    [53] anonymous struct [0x3848] {
    }
    [54] anonymous struct [0x3848] {
    }
    [55] anonymous struct [0x3848] {
    }
    [56] anonymous struct [0x3848] {
    }
    [57] anonymous struct [0x3848] {
    }
    [58] anonymous struct [0x3848] {
    }
    [59] anonymous struct [0x3848] {
    }
    [60] anonymous struct [0x3848] {
    }
    [61] anonymous struct [0x3848] {
    }
    [62] anonymous struct [0x3848] {
    }
    [63] anonymous struct [0x3848] {
    }
    [64] anonymous struct [0x3848] {
    }
    [65] anonymous struct [0x3848] {
    }
    [66] anonymous struct [0x3848] {
    }
    [67] anonymous struct [0x3848] {
    }
    [68] anonymous struct [0x3848] {
    }
    [69] anonymous struct [0x3848] {
    }
    [70] anonymous struct [0x3848] {
    }
    [71] anonymous struct [0x3848] {
    }
    [72] anonymous struct [0x3848] {
    }
    [73] anonymous struct [0x3848] {
    }
    [74] anonymous struct [0x3848] {
    }
    [75] anonymous struct [0x3848] {
    }
    [76] anonymous struct [0x3848] {
    }
    [77] anonymous struct [0x3848] {
    }
    [78] anonymous struct [0x3848] {
    }
    [79] anonymous struct [0x3848] {
    }
    [80] anonymous struct [0x3848] {
    }
    [81] anonymous struct [0x3848] {
    }
    [82] anonymous struct [0x3848] {
    }
  }
  [50] array [0x3678] {size: (125929688, 125929672) (*invalid*)} {  }
  [51] array [0x3680] {size: (125929712, 125929680) (*invalid*)} {  }
  [52] array [0x3688] {size: (125929840, 125929688) (*invalid*)} {  }
  [53] array [0x3690] {size: (125930360, 125929712) (*invalid*)} {  }
  [54] array [0x3698] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x36b0] {size: 0} {
  }
  [60] array [0x36b8] {size: (125931088, 125930424) (*invalid*)} {  }
  [61] volume-emitter-node [0x03DD0] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 1179754
    [5] int: 2
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] float: 1.00
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 2.00
    [17] float: 1.00
    [18] float: 2.00
    [19] float: 1.00
    [20] int: 0
    [21] float: -1.00
    [22] int: 0
    [23] int: 0
    [24] float: 0.20
    [25] int: 0
    [26] float: 4.00
    [27] int: 0
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125931320, returning
  [63] array* [0x03EB8] {
    [0] anonymous array with invalid size 125931472, returning
    [1] volume-axis-field-node [0x03F50] {
      [0] int: 6
      [1] int: 33555200
      [2] float: 1.00
      [3] float: 1.00
      [4] float: -1.00
      [5] int: 0
      [6] int: 0
      [7] int: 0
      [8] int: 0
      [9] float: -1.00
      [10] int: 0
      [11] float: 1.00
      [12] int: 0
      [13] int: 0
      [14] int: 0
      [15] int: 0
      [16] float: 3.00
      [17] float: 1.00
      [18] float: 3.00
      [19] int: 0
      [20] float: 1.00
      [21] int: 0
      [22] int: 0
      [23] int: 0
      [24] int: 0
      [25] int: 0
      [26] int: 0
      [27] float: 3.00
      [28] int: 0
      [29] int: 0
      [30] int: 0
      [31] int: 0
      [32] int: 0
      [33] int: 0
    }
    [2] volume-axis-field-node [0x03FE0] {
      [0] int: 6
      [1] int: 33555200
      [2] float: 1.00
      [3] float: 1.00
      [4] float: -1.00
      [5] int: 131198
      [6] int: 0
      [7] int: 0
      [8] int: 0
      [9] float: -2.00
      [10] int: 0
      [11] float: 1.00
      [12] int: 0
      [13] int: 0
      [14] int: 0
      [15] int: 0
      [16] float: 4.00
      [17] float: 2.00
      [18] float: 4.00
      [19] int: 0
      [20] int: 0
      [21] float: 1.00
      [22] int: 0
      [23] int: 0
      [24] int: 0
      [25] float: 2.00
      [26] int: 0
      [27] int: 0
      [28] int: 0
      [29] int: 0
      [30] int: 0
      [31] int: 0
      [32] int: 0
      [33] int: 0
    }
    [3] int: 0
    [4] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 4
  [111] int: 66561
  [112] float: 12.00
  [113] float: 15.00
  [114] float: 150.00
  [115] float: 165.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 1.00
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] float: 12.00
  [140] float: 12.00
  [141] float: 150.00
  [142] float: 165.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 7  ##############################

waterfall-variable-density/wave_splash_no_optimization = particle-effect-desc [0x04070] {
  [0] int: 2864
  [1] int: 85163509
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: waterfall-variable-density/wave_splash_no_optimization
  [7] int: 0
  [8] int: 0
  [9] sid: waterfall-variable-density
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 393346
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 9
  [26] int: 512
  [27] sid: general/particles/water/water-burst-04:default
  [28] int: 0
  [29] int: 1703936
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] float: 1.00
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 458758
  [44] sid: #001900000011009E
  [45] int: 288
  [46] int: 3145776
  [47] int: 74
  [48] int: 0
  [49] array [0x4150] {size: 74} {
    [0] anonymous struct [0x4328] {
    }
    [1] anonymous struct [0x4328] {
    }
    [2] anonymous struct [0x4328] {
    }
    [3] anonymous struct [0x4328] {
    }
    [4] anonymous struct [0x4328] {
    }
    [5] anonymous struct [0x4328] {
    }
    [6] anonymous struct [0x4328] {
    }
    [7] anonymous struct [0x4328] {
    }
    [8] anonymous struct [0x4328] {
    }
    [9] anonymous struct [0x4328] {
    }
    [10] anonymous struct [0x4328] {
    }
    [11] anonymous struct [0x4328] {
    }
    [12] anonymous struct [0x4328] {
    }
    [13] anonymous struct [0x4328] {
    }
    [14] anonymous struct [0x4328] {
    }
    [15] anonymous struct [0x4328] {
    }
    [16] anonymous struct [0x4328] {
    }
    [17] anonymous struct [0x4328] {
    }
    [18] anonymous struct [0x4328] {
    }
    [19] anonymous struct [0x4328] {
    }
    [20] anonymous struct [0x4328] {
    }
    [21] anonymous struct [0x4328] {
    }
    [22] anonymous struct [0x4328] {
    }
    [23] anonymous struct [0x4328] {
    }
    [24] anonymous struct [0x4328] {
    }
    [25] anonymous struct [0x4328] {
    }
    [26] anonymous struct [0x4328] {
    }
    [27] anonymous struct [0x4328] {
    }
    [28] anonymous struct [0x4328] {
    }
    [29] anonymous struct [0x4328] {
    }
    [30] anonymous struct [0x4328] {
    }
    [31] anonymous struct [0x4328] {
    }
    [32] anonymous struct [0x4328] {
    }
    [33] anonymous struct [0x4328] {
    }
    [34] anonymous struct [0x4328] {
    }
    [35] anonymous struct [0x4328] {
    }
    [36] anonymous struct [0x4328] {
    }
    [37] anonymous struct [0x4328] {
    }
    [38] anonymous struct [0x4328] {
    }
    [39] anonymous struct [0x4328] {
    }
    [40] anonymous struct [0x4328] {
    }
    [41] anonymous struct [0x4328] {
    }
    [42] anonymous struct [0x4328] {
    }
    [43] anonymous struct [0x4328] {
    }
    [44] anonymous struct [0x4328] {
    }
    [45] anonymous struct [0x4328] {
    }
    [46] anonymous struct [0x4328] {
    }
    [47] anonymous struct [0x4328] {
    }
    [48] anonymous struct [0x4328] {
    }
    [49] anonymous struct [0x4328] {
    }
    [50] anonymous struct [0x4328] {
    }
    [51] anonymous struct [0x4328] {
    }
    [52] anonymous struct [0x4328] {
    }
    [53] anonymous struct [0x4328] {
    }
    [54] anonymous struct [0x4328] {
    }
    [55] anonymous struct [0x4328] {
    }
    [56] anonymous struct [0x4328] {
    }
    [57] anonymous struct [0x4328] {
    }
    [58] anonymous struct [0x4328] {
    }
    [59] anonymous struct [0x4328] {
    }
    [60] anonymous struct [0x4328] {
    }
    [61] anonymous struct [0x4328] {
    }
    [62] anonymous struct [0x4328] {
    }
    [63] anonymous struct [0x4328] {
    }
    [64] anonymous struct [0x4328] {
    }
    [65] anonymous struct [0x4328] {
    }
    [66] anonymous struct [0x4328] {
    }
    [67] anonymous struct [0x4328] {
    }
    [68] anonymous struct [0x4328] {
    }
    [69] anonymous struct [0x4328] {
    }
    [70] anonymous struct [0x4328] {
    }
    [71] anonymous struct [0x4328] {
    }
    [72] anonymous struct [0x4328] {
    }
    [73] anonymous struct [0x4328] {
    }
  }
  [50] array [0x4158] {size: (125932472, 125932456) (*invalid*)} {  }
  [51] array [0x4160] {size: (125932504, 125932464) (*invalid*)} {  }
  [52] array [0x4168] {size: (125932792, 125932472) (*invalid*)} {  }
  [53] array [0x4170] {size: (125933432, 125932504) (*invalid*)} {  }
  [54] array [0x4178] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x4190] {size: 0} {
  }
  [60] array [0x4198] {size: (125934256, 125933512) (*invalid*)} {  }
  [61] volume-emitter-node [0x04A30] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 2097274
    [5] int: 0
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.03
    [17] float: 0.03
    [18] float: 0.03
    [19] float: 1.00
    [20] int: 0
    [21] int: 0
    [22] float: 1.00
    [23] int: 0
    [24] float: 0.50
    [25] int: 0
    [26] float: 2.00
    [27] float: 1.50
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125934488, returning
  [63] array* [0x04B18] {
    [0] anonymous array [0x4b18] {size: 0} {
    }
    [1] int: 0
    [2] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 1028
  [111] int: 66560
  [112] int: 0
  [113] int: 0
  [114] float: 150.00
  [115] float: 165.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] float: 0.50
  [121] int: 917760
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.50
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] float: 150.00
  [142] float: 165.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 8  ##############################

flo-turbulent-foam-projection = effect-group-desc [0x04BA0] {
  [0] int: 476
  [1] int: 936949631
  [2] sid: flo-turbulent-foam-projection
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 1
  [10] int: 0
  [11] array [0x4bd0] {size: 1} {
    [0] anonymous struct [0x4c68] {
      [0] sid: game
      [1] sid: levels
      [2] sid: flooded-city
      [3] int: 0
      [4] int: 0
    }
  }
  [12] string: "write some notes here"
  [13] int: 0
  [14] int: 0
  [15] int: 3
  [16] int: 0
  [17] anonymous array with invalid size 125934896, returning
  [18] array [0x4bf8] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x4c10] {size: 0} {
  }
  [24] array* [0x04CD8] {
    [0] int: 0
    [1] int: 0
  }
  [25] array [0x4c20] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 9  ##############################

waterfall-base-lg/main_mist_half_res = particle-effect-desc [0x04D80] {
  [0] int: 2788
  [1] float: 2806.43
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: waterfall-base-lg/main_mist_half_res
  [7] int: 0
  [8] int: 0
  [9] sid: waterfall-base-lg
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 393346
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 8
  [26] int: 512
  [27] sid: general/particles/smoke-steam/steam-mist-swirl:default
  [28] int: 0
  [29] int: 1572864
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 196611
  [44] sid: #00160000000E0080
  [45] int: 797
  [46] int: 1507351
  [47] int: 83
  [48] int: 0
  [49] array [0x4e60] {size: 83} {
    [0] anonymous struct [0x5038] {
    }
    [1] anonymous struct [0x5038] {
    }
    [2] anonymous struct [0x5038] {
    }
    [3] anonymous struct [0x5038] {
    }
    [4] anonymous struct [0x5038] {
    }
    [5] anonymous struct [0x5038] {
    }
    [6] anonymous struct [0x5038] {
    }
    [7] anonymous struct [0x5038] {
    }
    [8] anonymous struct [0x5038] {
    }
    [9] anonymous struct [0x5038] {
    }
    [10] anonymous struct [0x5038] {
    }
    [11] anonymous struct [0x5038] {
    }
    [12] anonymous struct [0x5038] {
    }
    [13] anonymous struct [0x5038] {
    }
    [14] anonymous struct [0x5038] {
    }
    [15] anonymous struct [0x5038] {
    }
    [16] anonymous struct [0x5038] {
    }
    [17] anonymous struct [0x5038] {
    }
    [18] anonymous struct [0x5038] {
    }
    [19] anonymous struct [0x5038] {
    }
    [20] anonymous struct [0x5038] {
    }
    [21] anonymous struct [0x5038] {
    }
    [22] anonymous struct [0x5038] {
    }
    [23] anonymous struct [0x5038] {
    }
    [24] anonymous struct [0x5038] {
    }
    [25] anonymous struct [0x5038] {
    }
    [26] anonymous struct [0x5038] {
    }
    [27] anonymous struct [0x5038] {
    }
    [28] anonymous struct [0x5038] {
    }
    [29] anonymous struct [0x5038] {
    }
    [30] anonymous struct [0x5038] {
    }
    [31] anonymous struct [0x5038] {
    }
    [32] anonymous struct [0x5038] {
    }
    [33] anonymous struct [0x5038] {
    }
    [34] anonymous struct [0x5038] {
    }
    [35] anonymous struct [0x5038] {
    }
    [36] anonymous struct [0x5038] {
    }
    [37] anonymous struct [0x5038] {
    }
    [38] anonymous struct [0x5038] {
    }
    [39] anonymous struct [0x5038] {
    }
    [40] anonymous struct [0x5038] {
    }
    [41] anonymous struct [0x5038] {
    }
    [42] anonymous struct [0x5038] {
    }
    [43] anonymous struct [0x5038] {
    }
    [44] anonymous struct [0x5038] {
    }
    [45] anonymous struct [0x5038] {
    }
    [46] anonymous struct [0x5038] {
    }
    [47] anonymous struct [0x5038] {
    }
    [48] anonymous struct [0x5038] {
    }
    [49] anonymous struct [0x5038] {
    }
    [50] anonymous struct [0x5038] {
    }
    [51] anonymous struct [0x5038] {
    }
    [52] anonymous struct [0x5038] {
    }
    [53] anonymous struct [0x5038] {
    }
    [54] anonymous struct [0x5038] {
    }
    [55] anonymous struct [0x5038] {
    }
    [56] anonymous struct [0x5038] {
    }
    [57] anonymous struct [0x5038] {
    }
    [58] anonymous struct [0x5038] {
    }
    [59] anonymous struct [0x5038] {
    }
    [60] anonymous struct [0x5038] {
    }
    [61] anonymous struct [0x5038] {
    }
    [62] anonymous struct [0x5038] {
    }
    [63] anonymous struct [0x5038] {
    }
    [64] anonymous struct [0x5038] {
    }
    [65] anonymous struct [0x5038] {
    }
    [66] anonymous struct [0x5038] {
    }
    [67] anonymous struct [0x5038] {
    }
    [68] anonymous struct [0x5038] {
    }
    [69] anonymous struct [0x5038] {
    }
    [70] anonymous struct [0x5038] {
    }
    [71] anonymous struct [0x5038] {
    }
    [72] anonymous struct [0x5038] {
    }
    [73] anonymous struct [0x5038] {
    }
    [74] anonymous struct [0x5038] {
    }
    [75] anonymous struct [0x5038] {
    }
    [76] anonymous struct [0x5038] {
    }
    [77] anonymous struct [0x5038] {
    }
    [78] anonymous struct [0x5038] {
    }
    [79] anonymous struct [0x5038] {
    }
    [80] anonymous struct [0x5038] {
    }
    [81] anonymous struct [0x5038] {
    }
    [82] anonymous struct [0x5038] {
    }
  }
  [50] array [0x4e68] {size: (125935816, 125935800) (*invalid*)} {  }
  [51] array [0x4e70] {size: (125935840, 125935808) (*invalid*)} {  }
  [52] array [0x4e78] {size: (125935968, 125935816) (*invalid*)} {  }
  [53] array [0x4e80] {size: (125936488, 125935840) (*invalid*)} {  }
  [54] array [0x4e88] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x4ea0] {size: 0} {
  }
  [60] array [0x4ea8] {size: (125937216, 125936552) (*invalid*)} {  }
  [61] volume-emitter-node [0x055C0] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 1179754
    [5] int: 2
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] float: 1.00
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 2.00
    [17] float: 1.00
    [18] float: 2.00
    [19] float: 1.00
    [20] int: 0
    [21] float: -1.00
    [22] int: 0
    [23] int: 0
    [24] float: 0.20
    [25] int: 0
    [26] float: 4.00
    [27] int: 0
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125937448, returning
  [63] array* [0x056A8] {
    [0] anonymous array with invalid size 125937600, returning
    [1] volume-axis-field-node [0x05740] {
      [0] int: 6
      [1] int: 33555200
      [2] float: 1.00
      [3] float: 1.00
      [4] float: -1.00
      [5] int: 0
      [6] int: 0
      [7] int: 0
      [8] int: 0
      [9] float: -1.00
      [10] int: 0
      [11] float: 1.00
      [12] int: 0
      [13] int: 0
      [14] int: 0
      [15] int: 0
      [16] float: 3.00
      [17] float: 1.00
      [18] float: 3.00
      [19] int: 0
      [20] float: 1.00
      [21] int: 0
      [22] int: 0
      [23] int: 0
      [24] int: 0
      [25] int: 0
      [26] int: 0
      [27] float: 3.00
      [28] int: 0
      [29] int: 0
      [30] int: 0
      [31] int: 0
      [32] int: 0
      [33] int: 0
    }
    [2] volume-axis-field-node [0x057D0] {
      [0] int: 6
      [1] int: 33555200
      [2] float: 1.00
      [3] float: 1.00
      [4] float: -1.00
      [5] int: 131198
      [6] int: 0
      [7] int: 0
      [8] int: 0
      [9] float: -2.00
      [10] int: 0
      [11] float: 1.00
      [12] int: 0
      [13] int: 0
      [14] int: 0
      [15] int: 0
      [16] float: 4.00
      [17] float: 2.00
      [18] float: 4.00
      [19] int: 0
      [20] int: 0
      [21] float: 1.00
      [22] int: 0
      [23] int: 0
      [24] int: 0
      [25] float: 2.00
      [26] int: 0
      [27] int: 0
      [28] int: 0
      [29] int: 0
      [30] int: 0
      [31] int: 0
      [32] int: 0
      [33] int: 0
    }
    [3] int: 0
    [4] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 1540
  [111] int: 66562
  [112] int: 0
  [113] int: 0
  [114] float: 12.00
  [115] float: 15.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 1.00
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] float: 15.00
  [142] float: 15.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 10  ##############################

water-splash-amorphous/water_splash_amorphous = particle-effect-desc [0x05860] {
  [0] int: 2232
  [1] float: 61.46
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: water-splash-amorphous/water_splash_amorphous
  [7] int: 0
  [8] int: 0
  [9] sid: water-splash-amorphous
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 128
  [22] int: 0
  [23] int: 4
  [24] int: 0
  [25] int: 6
  [26] int: 514
  [27] sid: general/particles/water/water-splash-amorphous:default
  [28] int: 0
  [29] int: 524288
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 262147
  [44] sid: #00120000000B006F
  [45] int: 25
  [46] int: 3997757
  [47] int: 46
  [48] int: 0
  [49] array [0x5940] {size: 46} {
    [0] anonymous struct [0x5b18] {
    }
    [1] anonymous struct [0x5b18] {
    }
    [2] anonymous struct [0x5b18] {
    }
    [3] anonymous struct [0x5b18] {
    }
    [4] anonymous struct [0x5b18] {
    }
    [5] anonymous struct [0x5b18] {
    }
    [6] anonymous struct [0x5b18] {
    }
    [7] anonymous struct [0x5b18] {
    }
    [8] anonymous struct [0x5b18] {
    }
    [9] anonymous struct [0x5b18] {
    }
    [10] anonymous struct [0x5b18] {
    }
    [11] anonymous struct [0x5b18] {
    }
    [12] anonymous struct [0x5b18] {
    }
    [13] anonymous struct [0x5b18] {
    }
    [14] anonymous struct [0x5b18] {
    }
    [15] anonymous struct [0x5b18] {
    }
    [16] anonymous struct [0x5b18] {
    }
    [17] anonymous struct [0x5b18] {
    }
    [18] anonymous struct [0x5b18] {
    }
    [19] anonymous struct [0x5b18] {
    }
    [20] anonymous struct [0x5b18] {
    }
    [21] anonymous struct [0x5b18] {
    }
    [22] anonymous struct [0x5b18] {
    }
    [23] anonymous struct [0x5b18] {
    }
    [24] anonymous struct [0x5b18] {
    }
    [25] anonymous struct [0x5b18] {
    }
    [26] anonymous struct [0x5b18] {
    }
    [27] anonymous struct [0x5b18] {
    }
    [28] anonymous struct [0x5b18] {
    }
    [29] anonymous struct [0x5b18] {
    }
    [30] anonymous struct [0x5b18] {
    }
    [31] anonymous struct [0x5b18] {
    }
    [32] anonymous struct [0x5b18] {
    }
    [33] anonymous struct [0x5b18] {
    }
    [34] anonymous struct [0x5b18] {
    }
    [35] anonymous struct [0x5b18] {
    }
    [36] anonymous struct [0x5b18] {
    }
    [37] anonymous struct [0x5b18] {
    }
    [38] anonymous struct [0x5b18] {
    }
    [39] anonymous struct [0x5b18] {
    }
    [40] anonymous struct [0x5b18] {
    }
    [41] anonymous struct [0x5b18] {
    }
    [42] anonymous struct [0x5b18] {
    }
    [43] anonymous struct [0x5b18] {
    }
    [44] anonymous struct [0x5b18] {
    }
    [45] anonymous struct [0x5b18] {
    }
  }
  [50] array [0x5948] {size: (125938600, 125938584) (*invalid*)} {  }
  [51] array [0x5950] {size: (125938624, 125938592) (*invalid*)} {  }
  [52] array [0x5958] {size: (125938792, 125938600) (*invalid*)} {  }
  [53] array [0x5960] {size: (125939248, 125938624) (*invalid*)} {  }
  [54] array [0x5968] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x5980] {size: 0} {
  }
  [60] array [0x5988] {size: (125939872, 125939304) (*invalid*)} {  }
  [61] volume-emitter-node [0x06020] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 262251
    [5] int: 0
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.50
    [17] float: 0.01
    [18] float: 0.50
    [19] float: 1.00
    [20] int: 0
    [21] float: 1.00
    [22] int: 0
    [23] int: 0
    [24] float: 0.50
    [25] int: 0
    [26] float: 1.00
    [27] int: 0
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125940104, returning
  [63] array* [0x06108] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 4
  [111] int: 66561
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] int: 0
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] float: 0.25
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: -1.00
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 11  ##############################

water-burst-01-sparse/wave_splash = particle-effect-desc [0x06120] {
  [0] int: 2456
  [1] int: -684092524
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: water-burst-01-sparse/wave_splash
  [7] int: 0
  [8] int: 0
  [9] sid: water-burst-01-sparse
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 130
  [22] int: 0
  [23] int: 4
  [24] int: 0
  [25] int: 8
  [26] int: 514
  [27] sid: general/particles/water/water-burst-01-sparse:default
  [28] int: 0
  [29] int: 524288
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] float: 1.00
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 458756
  [44] sid: #00120000000E0057
  [45] int: 285
  [46] int: 1835036
  [47] int: 24
  [48] int: 0
  [49] array [0x6200] {size: 24} {
    [0] anonymous struct [0x63d8] {
    }
    [1] anonymous struct [0x63d8] {
    }
    [2] anonymous struct [0x63d8] {
    }
    [3] anonymous struct [0x63d8] {
    }
    [4] anonymous struct [0x63d8] {
    }
    [5] anonymous struct [0x63d8] {
    }
    [6] anonymous struct [0x63d8] {
    }
    [7] anonymous struct [0x63d8] {
    }
    [8] anonymous struct [0x63d8] {
    }
    [9] anonymous struct [0x63d8] {
    }
    [10] anonymous struct [0x63d8] {
    }
    [11] anonymous struct [0x63d8] {
    }
    [12] anonymous struct [0x63d8] {
    }
    [13] anonymous struct [0x63d8] {
    }
    [14] anonymous struct [0x63d8] {
    }
    [15] anonymous struct [0x63d8] {
    }
    [16] anonymous struct [0x63d8] {
    }
    [17] anonymous struct [0x63d8] {
    }
    [18] anonymous struct [0x63d8] {
    }
    [19] anonymous struct [0x63d8] {
    }
    [20] anonymous struct [0x63d8] {
    }
    [21] anonymous struct [0x63d8] {
    }
    [22] anonymous struct [0x63d8] {
    }
    [23] anonymous struct [0x63d8] {
    }
  }
  [50] array [0x6208] {size: (125940840, 125940824) (*invalid*)} {  }
  [51] array [0x6210] {size: (125940864, 125940832) (*invalid*)} {  }
  [52] array [0x6218] {size: (125941152, 125940840) (*invalid*)} {  }
  [53] array [0x6220] {size: (125941512, 125940864) (*invalid*)} {  }
  [54] array [0x6228] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x6240] {size: 0} {
  }
  [60] array [0x6248] {size: (125942208, 125941576) (*invalid*)} {  }
  [61] volume-emitter-node [0x06940] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 2031668
    [5] int: 0
    [6] float: 3.14
    [7] float: 0.50
    [8] int: 0
    [9] float: -0.15
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.10
    [17] float: 0.10
    [18] float: 0.10
    [19] float: 1.00
    [20] int: 0
    [21] float: 1.00
    [22] int: 0
    [23] int: 0
    [24] float: 1.00
    [25] int: 0
    [26] float: 2.00
    [27] float: 1.50
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125942440, returning
  [63] array* [0x06A28] {
    [0] anonymous array [0x6a28] {size: 0} {
    }
    [1] int: 0
    [2] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 4
  [111] int: 66561
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] int: 0
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 65792
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.50
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 12  ##############################

water-burst-01-sparse = effect-group-desc [0x06AB0] {
  [0] int: 796
  [1] int: -1209354634
  [2] sid: water-burst-01-sparse
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 1
  [10] int: 0
  [11] array [0x6ae0] {size: 1} {
    [0] anonymous struct [0x6b78] {
      [0] sid: game
      [1] sid: water
      [2] int: 0
      [3] int: 0
    }
  }
  [12] string: "write some notes here"
  [13] int: 0
  [14] int: 0
  [15] int: 10
  [16] int: 0
  [17] anonymous array with invalid size 125942840, returning
  [18] array [0x6b08] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x6b20] {size: 0} {
  }
  [24] array* [0x06BF8] {
    [0] int: 0
    [1] int: 0
  }
  [25] array [0x6b30] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 13  ##############################

splashes-river-2 = effect-group-desc [0x06DD0] {
  [0] int: 760
  [1] int: 24909252
  [2] sid: splashes-river-2
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 1
  [10] int: 0
  [11] array [0x6e00] {size: 1} {
    [0] anonymous struct [0x6e98] {
      [0] sid: game
      [1] sid: water
      [2] int: 0
      [3] int: 0
    }
  }
  [12] string: ""
  [13] int: 0
  [14] int: 0
  [15] int: 8
  [16] int: 0
  [17] anonymous array with invalid size 125943640, returning
  [18] array [0x6e28] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x6e40] {size: 0} {
  }
  [24] array* [0x06F10] {
    [0] int: 0
    [1] int: 0
  }
  [25] array [0x6e50] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 14  ##############################

disable-relocation = boolean [0x070C0] {
  [0] int: 1
  [1] int: 0
}


##############################  ENTRY 15  ##############################

water-splash-amorphous = effect-group-desc [0x070D0] {
  [0] int: 571
  [1] int: -1850168686
  [2] sid: water-splash-amorphous
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 1
  [10] int: 0
  [11] array [0x7100] {size: 1} {
    [0] anonymous struct [0x7198] {
      [0] sid: game
      [1] sid: water
      [2] int: 0
      [3] int: 0
    }
  }
  [12] string: "write some notes here"
  [13] int: 0
  [14] int: 0
  [15] int: 5
  [16] int: 0
  [17] anonymous array with invalid size 125944408, returning
  [18] array [0x7128] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x7140] {size: 0} {
  }
  [24] array* [0x07208] {
    [0] int: 0
    [1] int: 0
  }
  [25] array [0x7150] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 16  ##############################

waterfall-variable-density/wave_splash = particle-effect-desc [0x07310] {
  [0] int: 2868
  [1] int: -1355294976
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: waterfall-variable-density/wave_splash
  [7] int: 0
  [8] int: 0
  [9] sid: waterfall-variable-density
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 393346
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 9
  [26] int: 512
  [27] sid: general/particles/water/water-burst-04:default
  [28] int: 0
  [29] int: 1703936
  [30] int: 1
  [31] int: 0
  [32] float: 100.00
  [33] float: 1.00
  [34] int: 0
  [35] float: 1.00
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 458758
  [44] sid: #001900000011009D
  [45] int: 288
  [46] int: 3145776
  [47] int: 74
  [48] int: 0
  [49] array [0x73f0] {size: 74} {
    [0] anonymous struct [0x75c8] {
    }
    [1] anonymous struct [0x75c8] {
    }
    [2] anonymous struct [0x75c8] {
    }
    [3] anonymous struct [0x75c8] {
    }
    [4] anonymous struct [0x75c8] {
    }
    [5] anonymous struct [0x75c8] {
    }
    [6] anonymous struct [0x75c8] {
    }
    [7] anonymous struct [0x75c8] {
    }
    [8] anonymous struct [0x75c8] {
    }
    [9] anonymous struct [0x75c8] {
    }
    [10] anonymous struct [0x75c8] {
    }
    [11] anonymous struct [0x75c8] {
    }
    [12] anonymous struct [0x75c8] {
    }
    [13] anonymous struct [0x75c8] {
    }
    [14] anonymous struct [0x75c8] {
    }
    [15] anonymous struct [0x75c8] {
    }
    [16] anonymous struct [0x75c8] {
    }
    [17] anonymous struct [0x75c8] {
    }
    [18] anonymous struct [0x75c8] {
    }
    [19] anonymous struct [0x75c8] {
    }
    [20] anonymous struct [0x75c8] {
    }
    [21] anonymous struct [0x75c8] {
    }
    [22] anonymous struct [0x75c8] {
    }
    [23] anonymous struct [0x75c8] {
    }
    [24] anonymous struct [0x75c8] {
    }
    [25] anonymous struct [0x75c8] {
    }
    [26] anonymous struct [0x75c8] {
    }
    [27] anonymous struct [0x75c8] {
    }
    [28] anonymous struct [0x75c8] {
    }
    [29] anonymous struct [0x75c8] {
    }
    [30] anonymous struct [0x75c8] {
    }
    [31] anonymous struct [0x75c8] {
    }
    [32] anonymous struct [0x75c8] {
    }
    [33] anonymous struct [0x75c8] {
    }
    [34] anonymous struct [0x75c8] {
    }
    [35] anonymous struct [0x75c8] {
    }
    [36] anonymous struct [0x75c8] {
    }
    [37] anonymous struct [0x75c8] {
    }
    [38] anonymous struct [0x75c8] {
    }
    [39] anonymous struct [0x75c8] {
    }
    [40] anonymous struct [0x75c8] {
    }
    [41] anonymous struct [0x75c8] {
    }
    [42] anonymous struct [0x75c8] {
    }
    [43] anonymous struct [0x75c8] {
    }
    [44] anonymous struct [0x75c8] {
    }
    [45] anonymous struct [0x75c8] {
    }
    [46] anonymous struct [0x75c8] {
    }
    [47] anonymous struct [0x75c8] {
    }
    [48] anonymous struct [0x75c8] {
    }
    [49] anonymous struct [0x75c8] {
    }
    [50] anonymous struct [0x75c8] {
    }
    [51] anonymous struct [0x75c8] {
    }
    [52] anonymous struct [0x75c8] {
    }
    [53] anonymous struct [0x75c8] {
    }
    [54] anonymous struct [0x75c8] {
    }
    [55] anonymous struct [0x75c8] {
    }
    [56] anonymous struct [0x75c8] {
    }
    [57] anonymous struct [0x75c8] {
    }
    [58] anonymous struct [0x75c8] {
    }
    [59] anonymous struct [0x75c8] {
    }
    [60] anonymous struct [0x75c8] {
    }
    [61] anonymous struct [0x75c8] {
    }
    [62] anonymous struct [0x75c8] {
    }
    [63] anonymous struct [0x75c8] {
    }
    [64] anonymous struct [0x75c8] {
    }
    [65] anonymous struct [0x75c8] {
    }
    [66] anonymous struct [0x75c8] {
    }
    [67] anonymous struct [0x75c8] {
    }
    [68] anonymous struct [0x75c8] {
    }
    [69] anonymous struct [0x75c8] {
    }
    [70] anonymous struct [0x75c8] {
    }
    [71] anonymous struct [0x75c8] {
    }
    [72] anonymous struct [0x75c8] {
    }
    [73] anonymous struct [0x75c8] {
    }
  }
  [50] array [0x73f8] {size: (125945432, 125945416) (*invalid*)} {  }
  [51] array [0x7400] {size: (125945464, 125945424) (*invalid*)} {  }
  [52] array [0x7408] {size: (125945752, 125945432) (*invalid*)} {  }
  [53] array [0x7410] {size: (125946392, 125945464) (*invalid*)} {  }
  [54] array [0x7418] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x7430] {size: 0} {
  }
  [60] array [0x7438] {size: (125947216, 125946472) (*invalid*)} {  }
  [61] volume-emitter-node [0x07CD0] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 2031738
    [5] int: 0
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.03
    [17] float: 0.03
    [18] float: 0.03
    [19] float: 1.00
    [20] int: 0
    [21] int: 0
    [22] float: 1.00
    [23] int: 0
    [24] float: 0.50
    [25] int: 0
    [26] float: 2.00
    [27] float: 1.50
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125947448, returning
  [63] array* [0x07DB8] {
    [0] anonymous array [0x7db8] {size: 0} {
    }
    [1] int: 0
    [2] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 4
  [111] int: 66560
  [112] float: 12.00
  [113] float: 15.00
  [114] float: 150.00
  [115] float: 165.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] float: 0.50
  [121] int: 917760
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.50
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] float: 12.00
  [140] float: 12.00
  [141] float: 150.00
  [142] float: 165.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 17  ##############################

waterfall-variable-density = effect-group-desc [0x07E40] {
  [0] int: 964
  [1] float: -0.00
  [2] sid: waterfall-variable-density
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 4
  [10] int: 0
  [11] array [0x7e70] {size: 4} {
    [0] anonymous struct [0x7f08] {
      [0] sid: game
    }
    [1] anonymous struct [0x7f10] {
      [0] sid: water
    }
    [2] anonymous struct [0x7f18] {
      [0] sid: waterfalls
    }
    [3] anonymous struct [0x7f20] {
      [0] int: 0
      [1] int: 0
    }
  }
  [12] string: "write some notes here"
  [13] int: 0
  [14] int: 0
  [15] int: 15
  [16] int: 0
  [17] anonymous array with invalid size 125947856, returning
  [18] array [0x7e98] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x7eb0] {size: 0} {
  }
  [24] array* [0x07FC0] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
    [4] int: 0
    [5] int: 0
    [6] int: 0
    [7] int: 0
  }
  [25] array [0x7ec0] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 18  ##############################

waterfall-base-lg = effect-group-desc [0x08200] {
  [0] int: 648
  [1] float: 11.25
  [2] sid: waterfall-base-lg
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 4
  [10] int: 0
  [11] array [0x8230] {size: 4} {
    [0] anonymous struct [0x82c8] {
      [0] sid: game
    }
    [1] anonymous struct [0x82d0] {
      [0] sid: water
    }
    [2] anonymous struct [0x82d8] {
      [0] sid: waterfalls
    }
    [3] anonymous struct [0x82e0] {
      [0] int: 0
      [1] int: 0
    }
  }
  [12] string: "comments go here"
  [13] int: 0
  [14] int: 0
  [15] int: 6
  [16] int: 0
  [17] anonymous array with invalid size 125948816, returning
  [18] array [0x8258] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x8270] {size: 0} {
  }
  [24] array* [0x08358] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
    [4] int: 0
    [5] int: 0
    [6] int: 0
    [7] int: 0
  }
  [25] array [0x8280] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 19  ##############################

splashes-river-2/creek_river_splashes_1 = particle-effect-desc [0x08490] {
  [0] int: 2356
  [1] float: -39.11
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: splashes-river-2/creek_river_splashes_1
  [7] int: 0
  [8] int: 0
  [9] sid: splashes-river-2
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 393346
  [22] int: 32
  [23] int: 0
  [24] int: 0
  [25] int: 7
  [26] int: 512
  [27] sid: general/particles/water/splash-creek-river-threshold:default
  [28] int: 0
  [29] int: 524288
  [30] int: 1
  [31] int: 0
  [32] float: 8.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 458758
  [44] sid: #00120000000A0049
  [45] int: 283
  [46] int: 2359332
  [47] int: 18
  [48] int: 0
  [49] array [0x8570] {size: 18} {
    [0] anonymous struct [0x8748] {
    }
    [1] anonymous struct [0x8748] {
    }
    [2] anonymous struct [0x8748] {
    }
    [3] anonymous struct [0x8748] {
    }
    [4] anonymous struct [0x8748] {
    }
    [5] anonymous struct [0x8748] {
    }
    [6] anonymous struct [0x8748] {
    }
    [7] anonymous struct [0x8748] {
    }
    [8] anonymous struct [0x8748] {
    }
    [9] anonymous struct [0x8748] {
    }
    [10] anonymous struct [0x8748] {
    }
    [11] anonymous struct [0x8748] {
    }
    [12] anonymous struct [0x8748] {
    }
    [13] anonymous struct [0x8748] {
    }
    [14] anonymous struct [0x8748] {
    }
    [15] anonymous struct [0x8748] {
    }
    [16] anonymous struct [0x8748] {
    }
    [17] anonymous struct [0x8748] {
    }
  }
  [50] array [0x8578] {size: (125949912, 125949896) (*invalid*)} {  }
  [51] array [0x8580] {size: (125949944, 125949904) (*invalid*)} {  }
  [52] array [0x8588] {size: (125950232, 125949912) (*invalid*)} {  }
  [53] array [0x8590] {size: (125950536, 125949944) (*invalid*)} {  }
  [54] array [0x8598] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x85b0] {size: 0} {
  }
  [60] array [0x85b8] {size: (125951184, 125950584) (*invalid*)} {  }
  [61] volume-emitter-node [0x08C50] {
    [0] int: 1
    [1] int: 1
    [2] float: 0.55
    [3] float: 0.10
    [4] int: 1245238
    [5] int: 0
    [6] float: 2.79
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.10
    [17] float: 0.10
    [18] float: 0.10
    [19] float: 1.00
    [20] int: 0
    [21] float: 0.20
    [22] float: 0.10
    [23] int: 0
    [24] float: 1.04
    [25] int: 0
    [26] int: 0
    [27] float: 1.00
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 125951416, returning
  [63] array* [0x08D38] {
    [0] anonymous array [0x8d38] {size: 0} {
    }
    [1] int: 0
    [2] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 4
  [111] int: 66561
  [112] float: 1.00
  [113] float: 2.00
  [114] float: 60.00
  [115] float: 65.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 1.00
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] float: 20.00
  [142] float: 30.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}
