####################################################################################################
#                                                                                                  #
#   generated by dconstruct ver. 1.52.0                                                            #
#   listing for file: .\game_dumps\t2r\dc1\part-module\part-actor-anim-efm-nat-history.bin         #
#   filesize: 29401 bytes                                                                          #
#   total entries: 15                                                                              #
#   functions: 0                                                                                   #
#   has state script: false                                                                        #
#   game type: t2r                                                                                 #
#   optimizations enabled: true                                                                    #
#                                                                                                  #
####################################################################################################



##############################  ENTRY 0  ##############################

efm-water-ripples = effect-group-desc [0x001A0] {
  [0] int: 900
  [1] int: -2052222045
  [2] sid: efm-water-ripples
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 1
  [10] int: 0
  [11] array [0x1d0] {size: 1} {
    [0] anonymous struct [0x268] {
      [0] sid: game
      [1] sid: levels
      [2] sid: efm
      [3] int: 0
      [4] int: 0
    }
  }
  [12] string: "write some notes here"
  [13] int: 0
  [14] int: 0
  [15] int: 18
  [16] int: 0
  [17] anonymous array with invalid size 112438768, returning
  [18] array [0x1f8] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x210] {size: 0} {
  }
  [24] array* [0x00310] {
    [0] int: 0
    [1] int: 0
  }
  [25] array [0x220] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 1  ##############################

efm-water-splash-cam-facing/surface_bubbles_uw = particle-effect-desc [0x00520] {
  [0] int: 2236
  [1] int: -1990320050
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: efm-water-splash-cam-facing/surface_bubbles_uw
  [7] int: 0
  [8] int: 0
  [9] sid: efm-water-splash-cam-facing
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 262272
  [22] int: 128
  [23] int: 0
  [24] int: 0
  [25] int: 7
  [26] int: 512
  [27] sid: general/particles/water/splash-creek-river-nav:default
  [28] int: 0
  [29] int: 1572864
  [30] int: 1
  [31] int: 0
  [32] float: 8.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 131074
  [44] sid: #0016000000100036
  [45] int: 539
  [46] int: 1900573
  [47] int: 25
  [48] int: 0
  [49] array [0x600] {size: 25} {
    [0] anonymous struct [0x7d8] {
    }
    [1] anonymous struct [0x7d8] {
    }
    [2] anonymous struct [0x7d8] {
    }
    [3] anonymous struct [0x7d8] {
    }
    [4] anonymous struct [0x7d8] {
    }
    [5] anonymous struct [0x7d8] {
    }
    [6] anonymous struct [0x7d8] {
    }
    [7] anonymous struct [0x7d8] {
    }
    [8] anonymous struct [0x7d8] {
    }
    [9] anonymous struct [0x7d8] {
    }
    [10] anonymous struct [0x7d8] {
    }
    [11] anonymous struct [0x7d8] {
    }
    [12] anonymous struct [0x7d8] {
    }
    [13] anonymous struct [0x7d8] {
    }
    [14] anonymous struct [0x7d8] {
    }
    [15] anonymous struct [0x7d8] {
    }
    [16] anonymous struct [0x7d8] {
    }
    [17] anonymous struct [0x7d8] {
    }
    [18] anonymous struct [0x7d8] {
    }
    [19] anonymous struct [0x7d8] {
    }
    [20] anonymous struct [0x7d8] {
    }
    [21] anonymous struct [0x7d8] {
    }
    [22] anonymous struct [0x7d8] {
    }
    [23] anonymous struct [0x7d8] {
    }
    [24] anonymous struct [0x7d8] {
    }
  }
  [50] array [0x608] {size: (112440104, 112440088) (*invalid*)} {  }
  [51] array [0x610] {size: (112440120, 112440096) (*invalid*)} {  }
  [52] array [0x618] {size: (112440208, 112440104) (*invalid*)} {  }
  [53] array [0x620] {size: (112440432, 112440120) (*invalid*)} {  }
  [54] array [0x628] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x640] {size: 0} {
  }
  [60] array [0x648] {size: (112441136, 112440504) (*invalid*)} {  }
  [61] volume-emitter-node [0x00BF0] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 0
    [5] int: 1
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.50
    [17] float: 0.01
    [18] float: 0.50
    [19] float: 1.00
    [20] int: 0
    [21] int: 0
    [22] int: 0
    [23] int: 0
    [24] float: 1.00
    [25] int: 0
    [26] int: 0
    [27] float: 0.50
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 112441368, returning
  [63] array* [0x00CD8] {
    [0] anonymous array with invalid size 112441520, returning
    [1] anonymous array [0xce0] {size: 0} {
    }
    [2] int: 0
    [3] int: 0
    [4] int: 0
    [5] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 1028
  [111] int: 66561
  [112] int: 0
  [113] float: 0.50
  [114] float: 50.00
  [115] float: 100.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.50
  [131] int: 131071
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 2  ##############################

nav-boar-dirt-kickup/dust = particle-effect-desc [0x00DE0] {
  [0] int: 2168
  [1] int: -1404864833
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: nav-boar-dirt-kickup/dust
  [7] int: 0
  [8] int: 0
  [9] sid: nav-boar-dirt-kickup
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 8
  [26] int: 0
  [27] sid: general/particles/smoke-steam/smoke-puffy-flipbook:default
  [28] int: 0
  [29] int: 524288
  [30] int: 1
  [31] int: 0
  [32] float: 1.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 393222
  [44] sid: #00120000000C0041
  [45] int: 28
  [46] int: 2359332
  [47] int: 27
  [48] int: 0
  [49] array [0xec0] {size: 27} {
    [0] anonymous struct [0x1098] {
    }
    [1] anonymous struct [0x1098] {
    }
    [2] anonymous struct [0x1098] {
    }
    [3] anonymous struct [0x1098] {
    }
    [4] anonymous struct [0x1098] {
    }
    [5] anonymous struct [0x1098] {
    }
    [6] anonymous struct [0x1098] {
    }
    [7] anonymous struct [0x1098] {
    }
    [8] anonymous struct [0x1098] {
    }
    [9] anonymous struct [0x1098] {
    }
    [10] anonymous struct [0x1098] {
    }
    [11] anonymous struct [0x1098] {
    }
    [12] anonymous struct [0x1098] {
    }
    [13] anonymous struct [0x1098] {
    }
    [14] anonymous struct [0x1098] {
    }
    [15] anonymous struct [0x1098] {
    }
    [16] anonymous struct [0x1098] {
    }
    [17] anonymous struct [0x1098] {
    }
    [18] anonymous struct [0x1098] {
    }
    [19] anonymous struct [0x1098] {
    }
    [20] anonymous struct [0x1098] {
    }
    [21] anonymous struct [0x1098] {
    }
    [22] anonymous struct [0x1098] {
    }
    [23] anonymous struct [0x1098] {
    }
    [24] anonymous struct [0x1098] {
    }
    [25] anonymous struct [0x1098] {
    }
    [26] anonymous struct [0x1098] {
    }
  }
  [50] array [0xec8] {size: (112442344, 112442328) (*invalid*)} {  }
  [51] array [0xed0] {size: (112442376, 112442336) (*invalid*)} {  }
  [52] array [0xed8] {size: (112442624, 112442344) (*invalid*)} {  }
  [53] array [0xee0] {size: (112442896, 112442376) (*invalid*)} {  }
  [54] array [0xee8] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0xf00] {size: 0} {
  }
  [60] array [0xf08] {size: (112443568, 112442952) (*invalid*)} {  }
  [61] anonymous array with invalid size 112443696, returning
  [62] anonymous array with invalid size 112443784, returning
  [63] array* [0x01648] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 4
  [111] int: 66561
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] int: 0
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] float: 0.25
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 1.00
  [131] int: 131071
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 3  ##############################

efm-water-splash-cam-facing/-distance_droplets-distance_droplets = particle-effect-desc [0x01660] {
  [0] int: 1752
  [1] int: -1641967406
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: efm-water-splash-cam-facing/-distance_droplets-distance_droplets
  [7] int: 0
  [8] int: 0
  [9] sid: efm-water-splash-cam-facing
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 262272
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 6
  [26] int: 514
  [27] sid: general/particles/dot:default
  [28] int: 0
  [29] int: 0
  [30] int: 1
  [31] int: 0
  [32] float: 1500.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 0
  [44] sid: #000E000000060013
  [45] int: 280
  [46] int: 19
  [47] int: 0
  [48] int: 0
  [49] array [0x1740] {size: 0} {
  }
  [50] array [0x1748] {size: (112444520, 112444504) (*invalid*)} {  }
  [51] array [0x1750] {size: (112444528, 112444512) (*invalid*)} {  }
  [52] array [0x1758] {size: (112444536, 112444520) (*invalid*)} {  }
  [53] array [0x1760] {size: (112444624, 112444528) (*invalid*)} {  }
  [54] array [0x1768] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x1780] {size: 0} {
  }
  [60] array [0x1788] {size: (112445184, 112444656) (*invalid*)} {  }
  [61] volume-emitter-node [0x01BC0] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 0
    [5] int: 1
    [6] float: 3.14
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] float: -1.57
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.20
    [17] float: 0.20
    [18] float: 0.20
    [19] float: 1.00
    [20] int: 0
    [21] int: 0
    [22] float: 1.00
    [23] int: 0
    [24] float: 0.50
    [25] int: 0
    [26] float: 2.50
    [27] float: 2.50
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 112445416, returning
  [63] array* [0x01CA8] {
    [0] anonymous array [0x1ca8] {size: 0} {
    }
    [1] int: 0
    [2] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 516
  [111] int: 66561
  [112] float: 6.00
  [113] float: 20.00
  [114] float: 60.00
  [115] float: 75.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.25
  [131] int: 65535
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 4  ##############################

nav-boar-dirt-kickup/squib_stones_FAR = particle-effect-desc [0x01D30] {
  [0] int: 2248
  [1] int: 160164183
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: nav-boar-dirt-kickup/squib_stones_FAR
  [7] int: 0
  [8] int: 0
  [9] sid: nav-boar-dirt-kickup
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 6422592
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 9
  [26] int: 0
  [27] sid: art/particles/geometry/debris-rubble-chunky.ma
  [28] int: 0
  [29] int: 0
  [30] int: 1
  [31] int: 0
  [32] float: 999.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 393219
  [44] sid: #000E0000000E0059
  [45] int: 29
  [46] int: 2883628
  [47] int: 35
  [48] int: 0
  [49] array [0x1e10] {size: 35} {
    [0] anonymous struct [0x1fe8] {
    }
    [1] anonymous struct [0x1fe8] {
    }
    [2] anonymous struct [0x1fe8] {
    }
    [3] anonymous struct [0x1fe8] {
    }
    [4] anonymous struct [0x1fe8] {
    }
    [5] anonymous struct [0x1fe8] {
    }
    [6] anonymous struct [0x1fe8] {
    }
    [7] anonymous struct [0x1fe8] {
    }
    [8] anonymous struct [0x1fe8] {
    }
    [9] anonymous struct [0x1fe8] {
    }
    [10] anonymous struct [0x1fe8] {
    }
    [11] anonymous struct [0x1fe8] {
    }
    [12] anonymous struct [0x1fe8] {
    }
    [13] anonymous struct [0x1fe8] {
    }
    [14] anonymous struct [0x1fe8] {
    }
    [15] anonymous struct [0x1fe8] {
    }
    [16] anonymous struct [0x1fe8] {
    }
    [17] anonymous struct [0x1fe8] {
    }
    [18] anonymous struct [0x1fe8] {
    }
    [19] anonymous struct [0x1fe8] {
    }
    [20] anonymous struct [0x1fe8] {
    }
    [21] anonymous struct [0x1fe8] {
    }
    [22] anonymous struct [0x1fe8] {
    }
    [23] anonymous struct [0x1fe8] {
    }
    [24] anonymous struct [0x1fe8] {
    }
    [25] anonymous struct [0x1fe8] {
    }
    [26] anonymous struct [0x1fe8] {
    }
    [27] anonymous struct [0x1fe8] {
    }
    [28] anonymous struct [0x1fe8] {
    }
    [29] anonymous struct [0x1fe8] {
    }
    [30] anonymous struct [0x1fe8] {
    }
    [31] anonymous struct [0x1fe8] {
    }
    [32] anonymous struct [0x1fe8] {
    }
    [33] anonymous struct [0x1fe8] {
    }
    [34] anonymous struct [0x1fe8] {
    }
  }
  [50] array [0x1e18] {size: (112446264, 112446248) (*invalid*)} {  }
  [51] array [0x1e20] {size: (112446288, 112446256) (*invalid*)} {  }
  [52] array [0x1e28] {size: (112446536, 112446264) (*invalid*)} {  }
  [53] array [0x1e30] {size: (112446904, 112446288) (*invalid*)} {  }
  [54] array [0x1e38] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x1e50] {size: 0} {
  }
  [60] array [0x1e58] {size: (112447568, 112446968) (*invalid*)} {  }
  [61] anonymous array with invalid size 112447696, returning
  [62] anonymous array with invalid size 112447784, returning
  [63] array* [0x025E8] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 516
  [111] int: 65537
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] int: 0
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.20
  [131] int: 131071
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] float: 8.00
  [140] float: 8.10
  [141] float: 49.99
  [142] float: 50.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 5  ##############################

efm-water-splash-cam-facing-sm/splash_geo_main = particle-effect-desc [0x02600] {
  [0] int: 2440
  [1] int: -1211304118
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: efm-water-splash-cam-facing-sm/splash_geo_main
  [7] int: 0
  [8] int: 0
  [9] sid: efm-water-splash-cam-facing-sm
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 64
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 7
  [26] int: 512
  [27] sid: art/particles/geometry/levels/efm/efm-tiny-droplets-cam-facing-sm.ma
  [28] int: 0
  [29] int: 524288
  [30] int: 1
  [31] int: 0
  [32] float: 3.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 131074
  [44] sid: #00120000000E006C
  [45] int: 540
  [46] int: 5308497
  [47] int: 27
  [48] int: 0
  [49] array [0x26e0] {size: 27} {
    [0] anonymous struct [0x28b8] {
    }
    [1] anonymous struct [0x28b8] {
    }
    [2] anonymous struct [0x28b8] {
    }
    [3] anonymous struct [0x28b8] {
    }
    [4] anonymous struct [0x28b8] {
    }
    [5] anonymous struct [0x28b8] {
    }
    [6] anonymous struct [0x28b8] {
    }
    [7] anonymous struct [0x28b8] {
    }
    [8] anonymous struct [0x28b8] {
    }
    [9] anonymous struct [0x28b8] {
    }
    [10] anonymous struct [0x28b8] {
    }
    [11] anonymous struct [0x28b8] {
    }
    [12] anonymous struct [0x28b8] {
    }
    [13] anonymous struct [0x28b8] {
    }
    [14] anonymous struct [0x28b8] {
    }
    [15] anonymous struct [0x28b8] {
    }
    [16] anonymous struct [0x28b8] {
    }
    [17] anonymous struct [0x28b8] {
    }
    [18] anonymous struct [0x28b8] {
    }
    [19] anonymous struct [0x28b8] {
    }
    [20] anonymous struct [0x28b8] {
    }
    [21] anonymous struct [0x28b8] {
    }
    [22] anonymous struct [0x28b8] {
    }
    [23] anonymous struct [0x28b8] {
    }
    [24] anonymous struct [0x28b8] {
    }
    [25] anonymous struct [0x28b8] {
    }
    [26] anonymous struct [0x28b8] {
    }
  }
  [50] array [0x26e8] {size: (112448520, 112448504) (*invalid*)} {  }
  [51] array [0x26f0] {size: (112448536, 112448512) (*invalid*)} {  }
  [52] array [0x26f8] {size: (112448624, 112448520) (*invalid*)} {  }
  [53] array [0x2700] {size: (112449064, 112448536) (*invalid*)} {  }
  [54] array [0x2708] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x2720] {size: 0} {
  }
  [60] array [0x2728] {size: (112449744, 112449128) (*invalid*)} {  }
  [61] volume-emitter-node [0x02D90] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 0
    [5] int: 2
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] float: 0.20
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.10
    [17] float: 0.05
    [18] float: 0.10
    [19] float: 1.00
    [20] int: 0
    [21] float: 1.00
    [22] int: 0
    [23] int: 0
    [24] int: 0
    [25] int: 0
    [26] float: 2.00
    [27] int: 0
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 112449976, returning
  [63] array* [0x02E78] {
    [0] anonymous array with invalid size 112450128, returning
    [1] anonymous array [0x2e80] {size: 0} {
    }
    [2] int: 0
    [3] int: 0
    [4] int: 0
    [5] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 1028
  [111] int: 65536
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] int: 0
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 262405
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 1.00
  [131] int: 131071
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 6  ##############################

efm-water-splash-cam-facing-sm = effect-group-desc [0x02F80] {
  [0] int: 1196
  [1] int: -2012755075
  [2] sid: efm-water-splash-cam-facing-sm
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 1
  [10] int: 0
  [11] array [0x2fb0] {size: 1} {
    [0] anonymous struct [0x3048] {
      [0] sid: game
      [1] sid: levels
      [2] sid: efm
      [3] int: 0
      [4] int: 0
    }
  }
  [12] string: "comments go here"
  [13] int: 0
  [14] int: 0
  [15] int: 20
  [16] int: 0
  [17] anonymous array with invalid size 112450512, returning
  [18] array [0x2fd8] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x2ff0] {size: 0} {
  }
  [24] array* [0x030F8] {
    [0] int: 0
    [1] int: 0
  }
  [25] array [0x3000] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 7  ##############################

efm-water-ripples/ripple1 = particle-effect-desc [0x03430] {
  [0] int: 1884
  [1] int: -813300055
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: efm-water-ripples/ripple1
  [7] int: 0
  [8] int: 0
  [9] sid: efm-water-ripples
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: water-gbuffer
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] sid: #0020000080040100
  [22] int: 0
  [23] int: 0
  [24] int: 7
  [25] int: 512
  [26] sid: general/particles/water/water-normals/nav-ripple-treading:default
  [27] int: 0
  [28] int: 524288
  [29] int: 1
  [30] int: 0
  [31] float: 10.00
  [32] float: 1.00
  [33] int: 0
  [34] int: 0
  [35] float: 1.00
  [36] float: 1.00
  [37] int: 0
  [38] int: 0
  [39] int: 0
  [40] float: -1.00
  [41] int: 0
  [42] int: 131074
  [43] sid: #0012000000090030
  [44] int: 25
  [45] int: 1835036
  [46] int: 18
  [47] int: 0
  [48] array [0x3510] {size: 18} {
    [0] anonymous struct [0x36e8] {
    }
    [1] anonymous struct [0x36e8] {
    }
    [2] anonymous struct [0x36e8] {
    }
    [3] anonymous struct [0x36e8] {
    }
    [4] anonymous struct [0x36e8] {
    }
    [5] anonymous struct [0x36e8] {
    }
    [6] anonymous struct [0x36e8] {
    }
    [7] anonymous struct [0x36e8] {
    }
    [8] anonymous struct [0x36e8] {
    }
    [9] anonymous struct [0x36e8] {
    }
    [10] anonymous struct [0x36e8] {
    }
    [11] anonymous struct [0x36e8] {
    }
    [12] anonymous struct [0x36e8] {
    }
    [13] anonymous struct [0x36e8] {
    }
    [14] anonymous struct [0x36e8] {
    }
    [15] anonymous struct [0x36e8] {
    }
    [16] anonymous struct [0x36e8] {
    }
    [17] anonymous struct [0x36e8] {
    }
  }
  [49] array [0x3518] {size: (112452152, 112452136) (*invalid*)} {  }
  [50] array [0x3520] {size: (112452168, 112452144) (*invalid*)} {  }
  [51] array [0x3528] {size: (112452256, 112452152) (*invalid*)} {  }
  [52] array [0x3530] {size: (112452456, 112452168) (*invalid*)} {  }
  [53] array [0x3538] {size: 0} {
  }
  [54] int: 0
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] array [0x3550] {size: 0} {
  }
  [59] array [0x3558] {size: (112453072, 112452504) (*invalid*)} {  }
  [60] volume-emitter-node [0x03A90] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 131118
    [5] int: 2
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.02
    [17] float: 0.00
    [18] float: 0.02
    [19] float: 1.00
    [20] float: 1.00
    [21] int: 0
    [22] int: 0
    [23] int: 0
    [24] int: 0
    [25] int: 0
    [26] int: 0
    [27] int: 0
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [61] anonymous array with invalid size 112453304, returning
  [62] array* [0x03B78] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
  }
  [63] int: 0
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 8
  [70] int: 1
  [71] int: 0
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] float: 0.02
  [78] int: 0
  [79] float: 1.00
  [80] float: 1.00
  [81] int: 0
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] float: 1.00
  [88] float: -0.00
  [89] int: 0
  [90] float: 10.00
  [91] int: 0
  [92] int: 0
  [93] float: 0.02
  [94] int: 0
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 259
  [102] int: 0
  [103] int: 0
  [104] float: -1.00
  [105] int: 0
  [106] int: 0
  [107] float: -1.00
  [108] int: 0
  [109] int: 1282
  [110] int: 66560
  [111] int: 0
  [112] int: 0
  [113] float: 20.00
  [114] float: 25.00
  [115] float: 1.00
  [116] float: 1.00
  [117] int: 0
  [118] int: 0
  [119] int: 0
  [120] int: 196868
  [121] int: 1
  [122] int: 0
  [123] int: 0
  [124] int: 16842752
  [125] int: 0
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] float: 1.50
  [130] int: 65535
  [131] int: 0
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] float: 1.00
  [145] int: 0
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
}


##############################  ENTRY 8  ##############################

nav-boar-dirt-kickup/small_dirt_emitter = particle-effect-desc [0x03B90] {
  [0] int: 2296
  [1] int: -97358434
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: nav-boar-dirt-kickup/small_dirt_emitter
  [7] int: 0
  [8] int: 0
  [9] sid: nav-boar-dirt-kickup
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 8
  [26] int: 0
  [27] sid: general/particles/misc/debris-underwater-sm:default
  [28] int: 0
  [29] int: 524288
  [30] int: 1
  [31] int: 0
  [32] float: 999.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 196611
  [44] sid: #0012000000100054
  [45] int: 285
  [46] int: 3145776
  [47] int: 28
  [48] int: 0
  [49] array [0x3c70] {size: 28} {
    [0] anonymous struct [0x3e48] {
    }
    [1] anonymous struct [0x3e48] {
    }
    [2] anonymous struct [0x3e48] {
    }
    [3] anonymous struct [0x3e48] {
    }
    [4] anonymous struct [0x3e48] {
    }
    [5] anonymous struct [0x3e48] {
    }
    [6] anonymous struct [0x3e48] {
    }
    [7] anonymous struct [0x3e48] {
    }
    [8] anonymous struct [0x3e48] {
    }
    [9] anonymous struct [0x3e48] {
    }
    [10] anonymous struct [0x3e48] {
    }
    [11] anonymous struct [0x3e48] {
    }
    [12] anonymous struct [0x3e48] {
    }
    [13] anonymous struct [0x3e48] {
    }
    [14] anonymous struct [0x3e48] {
    }
    [15] anonymous struct [0x3e48] {
    }
    [16] anonymous struct [0x3e48] {
    }
    [17] anonymous struct [0x3e48] {
    }
    [18] anonymous struct [0x3e48] {
    }
    [19] anonymous struct [0x3e48] {
    }
    [20] anonymous struct [0x3e48] {
    }
    [21] anonymous struct [0x3e48] {
    }
    [22] anonymous struct [0x3e48] {
    }
    [23] anonymous struct [0x3e48] {
    }
    [24] anonymous struct [0x3e48] {
    }
    [25] anonymous struct [0x3e48] {
    }
    [26] anonymous struct [0x3e48] {
    }
    [27] anonymous struct [0x3e48] {
    }
  }
  [50] array [0x3c78] {size: (112454040, 112454024) (*invalid*)} {  }
  [51] array [0x3c80] {size: (112454064, 112454032) (*invalid*)} {  }
  [52] array [0x3c88] {size: (112454192, 112454040) (*invalid*)} {  }
  [53] array [0x3c90] {size: (112454536, 112454064) (*invalid*)} {  }
  [54] array [0x3c98] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x3cb0] {size: 0} {
  }
  [60] array [0x3cb8] {size: (112455248, 112454608) (*invalid*)} {  }
  [61] anonymous array with invalid size 112455376, returning
  [62] anonymous array with invalid size 112455464, returning
  [63] array* [0x043E8] {
    [0] anonymous array [0x43e8] {size: 0} {
    }
    [1] int: 0
    [2] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 260
  [111] int: 66561
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] int: 0
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 786688
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.20
  [131] int: 131071
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 9  ##############################

nav-boar-dirt-kickup = effect-group-desc [0x04480] {
  [0] int: 820
  [1] float: 0.00
  [2] sid: nav-boar-dirt-kickup
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 4
  [10] int: 0
  [11] array [0x44b0] {size: 4} {
    [0] anonymous struct [0x4548] {
      [0] sid: game
    }
    [1] anonymous struct [0x4550] {
      [0] sid: navigation
    }
    [2] anonymous struct [0x4558] {
      [0] sid: boar
    }
    [3] anonymous struct [0x4560] {
      [0] int: 0
      [1] int: 0
    }
  }
  [12] string: "write some notes here"
  [13] int: 0
  [14] int: 0
  [15] int: 8
  [16] int: 0
  [17] anonymous array with invalid size 112455888, returning
  [18] array [0x44d8] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x44f0] {size: 0} {
  }
  [24] array* [0x045E0] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
    [4] int: 0
    [5] int: 0
    [6] int: 0
    [7] int: 0
  }
  [25] array [0x4500] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 10  ##############################

efm-water-splash-cam-facing/foam_proj1 = particle-effect-desc [0x047B0] {
  [0] int: 1956
  [1] int: 333699101
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: efm-water-splash-cam-facing/foam_proj1
  [7] int: 0
  [8] int: 0
  [9] sid: efm-water-splash-cam-facing
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: -2147483392
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 7
  [26] int: 512
  [27] sid: general/particles/water/foam-splash-proj-nav:default
  [28] int: 0
  [29] int: 524288
  [30] int: 1
  [31] int: 0
  [32] float: 1.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 196611
  [44] sid: #0012000000080037
  [45] int: 25
  [46] int: 1966110
  [47] int: 25
  [48] int: 0
  [49] array [0x4890] {size: 25} {
    [0] anonymous struct [0x4a68] {
    }
    [1] anonymous struct [0x4a68] {
    }
    [2] anonymous struct [0x4a68] {
    }
    [3] anonymous struct [0x4a68] {
    }
    [4] anonymous struct [0x4a68] {
    }
    [5] anonymous struct [0x4a68] {
    }
    [6] anonymous struct [0x4a68] {
    }
    [7] anonymous struct [0x4a68] {
    }
    [8] anonymous struct [0x4a68] {
    }
    [9] anonymous struct [0x4a68] {
    }
    [10] anonymous struct [0x4a68] {
    }
    [11] anonymous struct [0x4a68] {
    }
    [12] anonymous struct [0x4a68] {
    }
    [13] anonymous struct [0x4a68] {
    }
    [14] anonymous struct [0x4a68] {
    }
    [15] anonymous struct [0x4a68] {
    }
    [16] anonymous struct [0x4a68] {
    }
    [17] anonymous struct [0x4a68] {
    }
    [18] anonymous struct [0x4a68] {
    }
    [19] anonymous struct [0x4a68] {
    }
    [20] anonymous struct [0x4a68] {
    }
    [21] anonymous struct [0x4a68] {
    }
    [22] anonymous struct [0x4a68] {
    }
    [23] anonymous struct [0x4a68] {
    }
    [24] anonymous struct [0x4a68] {
    }
  }
  [50] array [0x4898] {size: (112457144, 112457128) (*invalid*)} {  }
  [51] array [0x48a0] {size: (112457168, 112457136) (*invalid*)} {  }
  [52] array [0x48a8] {size: (112457296, 112457144) (*invalid*)} {  }
  [53] array [0x48b0] {size: (112457528, 112457168) (*invalid*)} {  }
  [54] array [0x48b8] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x48d0] {size: 0} {
  }
  [60] array [0x48d8] {size: (112458144, 112457568) (*invalid*)} {  }
  [61] volume-emitter-node [0x04E60] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 0
    [5] int: 0
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.10
    [17] float: 0.01
    [18] float: 0.10
    [19] float: 1.00
    [20] float: 1.00
    [21] int: 0
    [22] int: 0
    [23] int: 0
    [24] int: 0
    [25] int: 0
    [26] int: 0
    [27] int: 0
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 112458376, returning
  [63] array* [0x04F48] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 1796
  [111] int: 66561
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] int: 0
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 196868
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 1.00
  [131] int: 131071
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 11  ##############################

efm-water-splash-cam-facing/splash_geo_main = particle-effect-desc [0x04F60] {
  [0] int: 2456
  [1] int: -231902944
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: efm-water-splash-cam-facing/splash_geo_main
  [7] int: 0
  [8] int: 0
  [9] sid: efm-water-splash-cam-facing
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 262208
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 7
  [26] int: 512
  [27] sid: art/particles/geometry/levels/efm/efm-tiny-droplets-cam-facing.ma
  [28] int: 0
  [29] int: 524288
  [30] int: 1
  [31] int: 0
  [32] float: 3.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 131074
  [44] sid: #00120000000D006D
  [45] int: 540
  [46] int: 5374034
  [47] int: 27
  [48] int: 0
  [49] array [0x5040] {size: 27} {
    [0] anonymous struct [0x5218] {
    }
    [1] anonymous struct [0x5218] {
    }
    [2] anonymous struct [0x5218] {
    }
    [3] anonymous struct [0x5218] {
    }
    [4] anonymous struct [0x5218] {
    }
    [5] anonymous struct [0x5218] {
    }
    [6] anonymous struct [0x5218] {
    }
    [7] anonymous struct [0x5218] {
    }
    [8] anonymous struct [0x5218] {
    }
    [9] anonymous struct [0x5218] {
    }
    [10] anonymous struct [0x5218] {
    }
    [11] anonymous struct [0x5218] {
    }
    [12] anonymous struct [0x5218] {
    }
    [13] anonymous struct [0x5218] {
    }
    [14] anonymous struct [0x5218] {
    }
    [15] anonymous struct [0x5218] {
    }
    [16] anonymous struct [0x5218] {
    }
    [17] anonymous struct [0x5218] {
    }
    [18] anonymous struct [0x5218] {
    }
    [19] anonymous struct [0x5218] {
    }
    [20] anonymous struct [0x5218] {
    }
    [21] anonymous struct [0x5218] {
    }
    [22] anonymous struct [0x5218] {
    }
    [23] anonymous struct [0x5218] {
    }
    [24] anonymous struct [0x5218] {
    }
    [25] anonymous struct [0x5218] {
    }
    [26] anonymous struct [0x5218] {
    }
  }
  [50] array [0x5048] {size: (112459112, 112459096) (*invalid*)} {  }
  [51] array [0x5050] {size: (112459128, 112459104) (*invalid*)} {  }
  [52] array [0x5058] {size: (112459216, 112459112) (*invalid*)} {  }
  [53] array [0x5060] {size: (112459664, 112459128) (*invalid*)} {  }
  [54] array [0x5068] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x5080] {size: 104} {
    [0] anonymous struct [0x5490] {
      [0] int: 0
    }
    [1] anonymous struct [0x5491] {
      [0] int: 0
    }
    [2] anonymous struct [0x5492] {
      [0] int: 0
    }
    [3] anonymous struct [0x5493] {
      [0] int: 0
    }
    [4] anonymous struct [0x5494] {
      [0] int: 0
    }
    [5] anonymous struct [0x5495] {
      [0] int: 0
    }
    [6] anonymous struct [0x5496] {
      [0] int: 0
    }
    [7] anonymous struct [0x5497] {
      [0] int: 0
    }
    [8] anonymous struct [0x5498] {
      [0] int: 0
    }
    [9] anonymous struct [0x5499] {
      [0] int: 0
    }
    [10] anonymous struct [0x549a] {
      [0] int: 0
    }
    [11] anonymous struct [0x549b] {
      [0] int: 0
    }
    [12] anonymous struct [0x549c] {
      [0] int: 0
    }
    [13] anonymous struct [0x549d] {
      [0] int: 0
    }
    [14] anonymous struct [0x549e] {
      [0] int: 0
    }
    [15] anonymous struct [0x549f] {
      [0] int: 0
    }
    [16] anonymous struct [0x54a0] {
      [0] int: 0
    }
    [17] anonymous struct [0x54a1] {
      [0] int: 0
    }
    [18] anonymous struct [0x54a2] {
      [0] int: 0
    }
    [19] anonymous struct [0x54a3] {
      [0] int: 0
    }
    [20] anonymous struct [0x54a4] {
      [0] int: 0
    }
    [21] anonymous struct [0x54a5] {
      [0] int: 0
    }
    [22] anonymous struct [0x54a6] {
      [0] int: 0
    }
    [23] anonymous struct [0x54a7] {
      [0] int: 0
    }
    [24] anonymous struct [0x54a8] {
      [0] float: 19.00
    }
    [25] anonymous struct [0x54a9] {
      [0] float: 19.00
    }
    [26] anonymous struct [0x54aa] {
      [0] float: 19.00
    }
    [27] anonymous struct [0x54ab] {
      [0] float: 19.00
    }
    [28] anonymous struct [0x54ac] {
      [0] float: 19.00
    }
    [29] anonymous struct [0x54ad] {
      [0] float: 19.00
    }
    [30] anonymous struct [0x54ae] {
      [0] float: 19.00
    }
    [31] anonymous struct [0x54af] {
      [0] float: 19.00
    }
    [32] anonymous struct [0x54b0] {
      [0] float: 20.00
    }
    [33] anonymous struct [0x54b1] {
      [0] float: 20.00
    }
    [34] anonymous struct [0x54b2] {
      [0] float: 20.00
    }
    [35] anonymous struct [0x54b3] {
      [0] float: 20.00
    }
    [36] anonymous struct [0x54b4] {
      [0] float: 20.00
    }
    [37] anonymous struct [0x54b5] {
      [0] float: 20.00
    }
    [38] anonymous struct [0x54b6] {
      [0] float: 20.00
    }
    [39] anonymous struct [0x54b7] {
      [0] float: 20.00
    }
    [40] anonymous struct [0x54b8] {
      [0] float: 21.00
    }
    [41] anonymous struct [0x54b9] {
      [0] float: 21.00
    }
    [42] anonymous struct [0x54ba] {
      [0] float: 21.00
    }
    [43] anonymous struct [0x54bb] {
      [0] float: 21.00
    }
    [44] anonymous struct [0x54bc] {
      [0] float: 21.00
    }
    [45] anonymous struct [0x54bd] {
      [0] float: 21.00
    }
    [46] anonymous struct [0x54be] {
      [0] float: 21.00
    }
    [47] anonymous struct [0x54bf] {
      [0] float: 21.00
    }
    [48] anonymous struct [0x54c0] {
      [0] float: 1.00
    }
    [49] anonymous struct [0x54c1] {
      [0] float: 1.00
    }
    [50] anonymous struct [0x54c2] {
      [0] float: 1.00
    }
    [51] anonymous struct [0x54c3] {
      [0] float: 1.00
    }
    [52] anonymous struct [0x54c4] {
      [0] float: 1.00
    }
    [53] anonymous struct [0x54c5] {
      [0] float: 1.00
    }
    [54] anonymous struct [0x54c6] {
      [0] float: 1.00
    }
    [55] anonymous struct [0x54c7] {
      [0] float: 1.00
    }
    [56] anonymous struct [0x54c8] {
      [0] float: 1.00
    }
    [57] anonymous struct [0x54c9] {
      [0] float: 1.00
    }
    [58] anonymous struct [0x54ca] {
      [0] float: 1.00
    }
    [59] anonymous struct [0x54cb] {
      [0] float: 1.00
    }
    [60] anonymous struct [0x54cc] {
      [0] float: 1.00
    }
    [61] anonymous struct [0x54cd] {
      [0] float: 1.00
    }
    [62] anonymous struct [0x54ce] {
      [0] float: 1.00
    }
    [63] anonymous struct [0x54cf] {
      [0] float: 1.00
    }
    [64] anonymous struct [0x54d0] {
      [0] float: 1.00
    }
    [65] anonymous struct [0x54d1] {
      [0] float: 1.00
    }
    [66] anonymous struct [0x54d2] {
      [0] float: 1.00
    }
    [67] anonymous struct [0x54d3] {
      [0] float: 1.00
    }
    [68] anonymous struct [0x54d4] {
      [0] float: 1.00
    }
    [69] anonymous struct [0x54d5] {
      [0] float: 1.00
    }
    [70] anonymous struct [0x54d6] {
      [0] float: 1.00
    }
    [71] anonymous struct [0x54d7] {
      [0] float: 1.00
    }
    [72] anonymous struct [0x54d8] {
      [0] float: 1.00
    }
    [73] anonymous struct [0x54d9] {
      [0] float: 1.00
    }
    [74] anonymous struct [0x54da] {
      [0] float: 1.00
    }
    [75] anonymous struct [0x54db] {
      [0] float: 1.00
    }
    [76] anonymous struct [0x54dc] {
      [0] float: 1.00
    }
    [77] anonymous struct [0x54dd] {
      [0] float: 1.00
    }
    [78] anonymous struct [0x54de] {
      [0] float: 1.00
    }
    [79] anonymous struct [0x54df] {
      [0] float: 1.00
    }
    [80] anonymous struct [0x54e0] {
      [0] float: 16.00
    }
    [81] anonymous struct [0x54e1] {
      [0] float: 16.00
    }
    [82] anonymous struct [0x54e2] {
      [0] float: 16.00
    }
    [83] anonymous struct [0x54e3] {
      [0] float: 16.00
    }
    [84] anonymous struct [0x54e4] {
      [0] float: 16.00
    }
    [85] anonymous struct [0x54e5] {
      [0] float: 16.00
    }
    [86] anonymous struct [0x54e6] {
      [0] float: 16.00
    }
    [87] anonymous struct [0x54e7] {
      [0] float: 16.00
    }
    [88] anonymous struct [0x54e8] {
      [0] float: 17.00
    }
    [89] anonymous struct [0x54e9] {
      [0] float: 17.00
    }
    [90] anonymous struct [0x54ea] {
      [0] float: 17.00
    }
    [91] anonymous struct [0x54eb] {
      [0] float: 17.00
    }
    [92] anonymous struct [0x54ec] {
      [0] float: 17.00
    }
    [93] anonymous struct [0x54ed] {
      [0] float: 17.00
    }
    [94] anonymous struct [0x54ee] {
      [0] float: 17.00
    }
    [95] anonymous struct [0x54ef] {
      [0] float: 17.00
    }
    [96] anonymous struct [0x54f0] {
      [0] float: 18.00
    }
    [97] anonymous struct [0x54f1] {
      [0] float: 18.00
    }
    [98] anonymous struct [0x54f2] {
      [0] float: 18.00
    }
    [99] anonymous struct [0x54f3] {
      [0] float: 18.00
    }
    [100] anonymous struct [0x54f4] {
      [0] float: 18.00
    }
    [101] anonymous struct [0x54f5] {
      [0] float: 18.00
    }
    [102] anonymous struct [0x54f6] {
      [0] float: 18.00
    }
    [103] anonymous struct [0x54f7] {
      [0] float: 18.00
    }
  }
  [60] array [0x5088] {size: 576} {
    [0] anonymous struct [0x5528] {
    }
    [1] anonymous struct [0x5528] {
    }
    [2] anonymous struct [0x5528] {
    }
    [3] anonymous struct [0x5528] {
    }
    [4] anonymous struct [0x5528] {
    }
    [5] anonymous struct [0x5528] {
    }
    [6] anonymous struct [0x5528] {
    }
    [7] anonymous struct [0x5528] {
    }
    [8] anonymous struct [0x5528] {
    }
    [9] anonymous struct [0x5528] {
    }
    [10] anonymous struct [0x5528] {
    }
    [11] anonymous struct [0x5528] {
    }
    [12] anonymous struct [0x5528] {
    }
    [13] anonymous struct [0x5528] {
    }
    [14] anonymous struct [0x5528] {
    }
    [15] anonymous struct [0x5528] {
    }
    [16] anonymous struct [0x5528] {
    }
    [17] anonymous struct [0x5528] {
    }
    [18] anonymous struct [0x5528] {
    }
    [19] anonymous struct [0x5528] {
    }
    [20] anonymous struct [0x5528] {
    }
    [21] anonymous struct [0x5528] {
    }
    [22] anonymous struct [0x5528] {
    }
    [23] anonymous struct [0x5528] {
    }
    [24] anonymous struct [0x5528] {
    }
    [25] anonymous struct [0x5528] {
    }
    [26] anonymous struct [0x5528] {
    }
    [27] anonymous struct [0x5528] {
    }
    [28] anonymous struct [0x5528] {
    }
    [29] anonymous struct [0x5528] {
    }
    [30] anonymous struct [0x5528] {
    }
    [31] anonymous struct [0x5528] {
    }
    [32] anonymous struct [0x5528] {
    }
    [33] anonymous struct [0x5528] {
    }
    [34] anonymous struct [0x5528] {
    }
    [35] anonymous struct [0x5528] {
    }
    [36] anonymous struct [0x5528] {
    }
    [37] anonymous struct [0x5528] {
    }
    [38] anonymous struct [0x5528] {
    }
    [39] anonymous struct [0x5528] {
    }
    [40] anonymous struct [0x5528] {
    }
    [41] anonymous struct [0x5528] {
    }
    [42] anonymous struct [0x5528] {
    }
    [43] anonymous struct [0x5528] {
    }
    [44] anonymous struct [0x5528] {
    }
    [45] anonymous struct [0x5528] {
    }
    [46] anonymous struct [0x5528] {
    }
    [47] anonymous struct [0x5528] {
    }
    [48] anonymous struct [0x5528] {
    }
    [49] anonymous struct [0x5528] {
    }
    [50] anonymous struct [0x5528] {
    }
    [51] anonymous struct [0x5528] {
    }
    [52] anonymous struct [0x5528] {
    }
    [53] anonymous struct [0x5528] {
    }
    [54] anonymous struct [0x5528] {
    }
    [55] anonymous struct [0x5528] {
    }
    [56] anonymous struct [0x5528] {
    }
    [57] anonymous struct [0x5528] {
    }
    [58] anonymous struct [0x5528] {
    }
    [59] anonymous struct [0x5528] {
    }
    [60] anonymous struct [0x5528] {
    }
    [61] anonymous struct [0x5528] {
    }
    [62] anonymous struct [0x5528] {
    }
    [63] anonymous struct [0x5528] {
    }
    [64] anonymous struct [0x5528] {
    }
    [65] anonymous struct [0x5528] {
    }
    [66] anonymous struct [0x5528] {
    }
    [67] anonymous struct [0x5528] {
    }
    [68] anonymous struct [0x5528] {
    }
    [69] anonymous struct [0x5528] {
    }
    [70] anonymous struct [0x5528] {
    }
    [71] anonymous struct [0x5528] {
    }
    [72] anonymous struct [0x5528] {
    }
    [73] anonymous struct [0x5528] {
    }
    [74] anonymous struct [0x5528] {
    }
    [75] anonymous struct [0x5528] {
    }
    [76] anonymous struct [0x5528] {
    }
    [77] anonymous struct [0x5528] {
    }
    [78] anonymous struct [0x5528] {
    }
    [79] anonymous struct [0x5528] {
    }
    [80] anonymous struct [0x5528] {
    }
    [81] anonymous struct [0x5528] {
    }
    [82] anonymous struct [0x5528] {
    }
    [83] anonymous struct [0x5528] {
    }
    [84] anonymous struct [0x5528] {
    }
    [85] anonymous struct [0x5528] {
    }
    [86] anonymous struct [0x5528] {
    }
    [87] anonymous struct [0x5528] {
    }
    [88] anonymous struct [0x5528] {
    }
    [89] anonymous struct [0x5528] {
    }
    [90] anonymous struct [0x5528] {
    }
    [91] anonymous struct [0x5528] {
    }
    [92] anonymous struct [0x5528] {
    }
    [93] anonymous struct [0x5528] {
    }
    [94] anonymous struct [0x5528] {
    }
    [95] anonymous struct [0x5528] {
    }
    [96] anonymous struct [0x5528] {
    }
    [97] anonymous struct [0x5528] {
    }
    [98] anonymous struct [0x5528] {
    }
    [99] anonymous struct [0x5528] {
    }
    [100] anonymous struct [0x5528] {
    }
    [101] anonymous struct [0x5528] {
    }
    [102] anonymous struct [0x5528] {
    }
    [103] anonymous struct [0x5528] {
    }
    [104] anonymous struct [0x5528] {
    }
    [105] anonymous struct [0x5528] {
    }
    [106] anonymous struct [0x5528] {
    }
    [107] anonymous struct [0x5528] {
    }
    [108] anonymous struct [0x5528] {
    }
    [109] anonymous struct [0x5528] {
    }
    [110] anonymous struct [0x5528] {
    }
    [111] anonymous struct [0x5528] {
    }
    [112] anonymous struct [0x5528] {
    }
    [113] anonymous struct [0x5528] {
    }
    [114] anonymous struct [0x5528] {
    }
    [115] anonymous struct [0x5528] {
    }
    [116] anonymous struct [0x5528] {
    }
    [117] anonymous struct [0x5528] {
    }
    [118] anonymous struct [0x5528] {
    }
    [119] anonymous struct [0x5528] {
    }
    [120] anonymous struct [0x5528] {
    }
    [121] anonymous struct [0x5528] {
    }
    [122] anonymous struct [0x5528] {
    }
    [123] anonymous struct [0x5528] {
    }
    [124] anonymous struct [0x5528] {
    }
    [125] anonymous struct [0x5528] {
    }
    [126] anonymous struct [0x5528] {
    }
    [127] anonymous struct [0x5528] {
    }
    [128] anonymous struct [0x5528] {
    }
    [129] anonymous struct [0x5528] {
    }
    [130] anonymous struct [0x5528] {
    }
    [131] anonymous struct [0x5528] {
    }
    [132] anonymous struct [0x5528] {
    }
    [133] anonymous struct [0x5528] {
    }
    [134] anonymous struct [0x5528] {
    }
    [135] anonymous struct [0x5528] {
    }
    [136] anonymous struct [0x5528] {
    }
    [137] anonymous struct [0x5528] {
    }
    [138] anonymous struct [0x5528] {
    }
    [139] anonymous struct [0x5528] {
    }
    [140] anonymous struct [0x5528] {
    }
    [141] anonymous struct [0x5528] {
    }
    [142] anonymous struct [0x5528] {
    }
    [143] anonymous struct [0x5528] {
    }
    [144] anonymous struct [0x5528] {
    }
    [145] anonymous struct [0x5528] {
    }
    [146] anonymous struct [0x5528] {
    }
    [147] anonymous struct [0x5528] {
    }
    [148] anonymous struct [0x5528] {
    }
    [149] anonymous struct [0x5528] {
    }
    [150] anonymous struct [0x5528] {
    }
    [151] anonymous struct [0x5528] {
    }
    [152] anonymous struct [0x5528] {
    }
    [153] anonymous struct [0x5528] {
    }
    [154] anonymous struct [0x5528] {
    }
    [155] anonymous struct [0x5528] {
    }
    [156] anonymous struct [0x5528] {
    }
    [157] anonymous struct [0x5528] {
    }
    [158] anonymous struct [0x5528] {
    }
    [159] anonymous struct [0x5528] {
    }
    [160] anonymous struct [0x5528] {
    }
    [161] anonymous struct [0x5528] {
    }
    [162] anonymous struct [0x5528] {
    }
    [163] anonymous struct [0x5528] {
    }
    [164] anonymous struct [0x5528] {
    }
    [165] anonymous struct [0x5528] {
    }
    [166] anonymous struct [0x5528] {
    }
    [167] anonymous struct [0x5528] {
    }
    [168] anonymous struct [0x5528] {
    }
    [169] anonymous struct [0x5528] {
    }
    [170] anonymous struct [0x5528] {
    }
    [171] anonymous struct [0x5528] {
    }
    [172] anonymous struct [0x5528] {
    }
    [173] anonymous struct [0x5528] {
    }
    [174] anonymous struct [0x5528] {
    }
    [175] anonymous struct [0x5528] {
    }
    [176] anonymous struct [0x5528] {
    }
    [177] anonymous struct [0x5528] {
    }
    [178] anonymous struct [0x5528] {
    }
    [179] anonymous struct [0x5528] {
    }
    [180] anonymous struct [0x5528] {
    }
    [181] anonymous struct [0x5528] {
    }
    [182] anonymous struct [0x5528] {
    }
    [183] anonymous struct [0x5528] {
    }
    [184] anonymous struct [0x5528] {
    }
    [185] anonymous struct [0x5528] {
    }
    [186] anonymous struct [0x5528] {
    }
    [187] anonymous struct [0x5528] {
    }
    [188] anonymous struct [0x5528] {
    }
    [189] anonymous struct [0x5528] {
    }
    [190] anonymous struct [0x5528] {
    }
    [191] anonymous struct [0x5528] {
    }
    [192] anonymous struct [0x5528] {
    }
    [193] anonymous struct [0x5528] {
    }
    [194] anonymous struct [0x5528] {
    }
    [195] anonymous struct [0x5528] {
    }
    [196] anonymous struct [0x5528] {
    }
    [197] anonymous struct [0x5528] {
    }
    [198] anonymous struct [0x5528] {
    }
    [199] anonymous struct [0x5528] {
    }
    [200] anonymous struct [0x5528] {
    }
    [201] anonymous struct [0x5528] {
    }
    [202] anonymous struct [0x5528] {
    }
    [203] anonymous struct [0x5528] {
    }
    [204] anonymous struct [0x5528] {
    }
    [205] anonymous struct [0x5528] {
    }
    [206] anonymous struct [0x5528] {
    }
    [207] anonymous struct [0x5528] {
    }
    [208] anonymous struct [0x5528] {
    }
    [209] anonymous struct [0x5528] {
    }
    [210] anonymous struct [0x5528] {
    }
    [211] anonymous struct [0x5528] {
    }
    [212] anonymous struct [0x5528] {
    }
    [213] anonymous struct [0x5528] {
    }
    [214] anonymous struct [0x5528] {
    }
    [215] anonymous struct [0x5528] {
    }
    [216] anonymous struct [0x5528] {
    }
    [217] anonymous struct [0x5528] {
    }
    [218] anonymous struct [0x5528] {
    }
    [219] anonymous struct [0x5528] {
    }
    [220] anonymous struct [0x5528] {
    }
    [221] anonymous struct [0x5528] {
    }
    [222] anonymous struct [0x5528] {
    }
    [223] anonymous struct [0x5528] {
    }
    [224] anonymous struct [0x5528] {
    }
    [225] anonymous struct [0x5528] {
    }
    [226] anonymous struct [0x5528] {
    }
    [227] anonymous struct [0x5528] {
    }
    [228] anonymous struct [0x5528] {
    }
    [229] anonymous struct [0x5528] {
    }
    [230] anonymous struct [0x5528] {
    }
    [231] anonymous struct [0x5528] {
    }
    [232] anonymous struct [0x5528] {
    }
    [233] anonymous struct [0x5528] {
    }
    [234] anonymous struct [0x5528] {
    }
    [235] anonymous struct [0x5528] {
    }
    [236] anonymous struct [0x5528] {
    }
    [237] anonymous struct [0x5528] {
    }
    [238] anonymous struct [0x5528] {
    }
    [239] anonymous struct [0x5528] {
    }
    [240] anonymous struct [0x5528] {
    }
    [241] anonymous struct [0x5528] {
    }
    [242] anonymous struct [0x5528] {
    }
    [243] anonymous struct [0x5528] {
    }
    [244] anonymous struct [0x5528] {
    }
    [245] anonymous struct [0x5528] {
    }
    [246] anonymous struct [0x5528] {
    }
    [247] anonymous struct [0x5528] {
    }
    [248] anonymous struct [0x5528] {
    }
    [249] anonymous struct [0x5528] {
    }
    [250] anonymous struct [0x5528] {
    }
    [251] anonymous struct [0x5528] {
    }
    [252] anonymous struct [0x5528] {
    }
    [253] anonymous struct [0x5528] {
    }
    [254] anonymous struct [0x5528] {
    }
    [255] anonymous struct [0x5528] {
    }
    [256] anonymous struct [0x5528] {
    }
    [257] anonymous struct [0x5528] {
    }
    [258] anonymous struct [0x5528] {
    }
    [259] anonymous struct [0x5528] {
    }
    [260] anonymous struct [0x5528] {
    }
    [261] anonymous struct [0x5528] {
    }
    [262] anonymous struct [0x5528] {
    }
    [263] anonymous struct [0x5528] {
    }
    [264] anonymous struct [0x5528] {
    }
    [265] anonymous struct [0x5528] {
    }
    [266] anonymous struct [0x5528] {
    }
    [267] anonymous struct [0x5528] {
    }
    [268] anonymous struct [0x5528] {
    }
    [269] anonymous struct [0x5528] {
    }
    [270] anonymous struct [0x5528] {
    }
    [271] anonymous struct [0x5528] {
    }
    [272] anonymous struct [0x5528] {
    }
    [273] anonymous struct [0x5528] {
    }
    [274] anonymous struct [0x5528] {
    }
    [275] anonymous struct [0x5528] {
    }
    [276] anonymous struct [0x5528] {
    }
    [277] anonymous struct [0x5528] {
    }
    [278] anonymous struct [0x5528] {
    }
    [279] anonymous struct [0x5528] {
    }
    [280] anonymous struct [0x5528] {
    }
    [281] anonymous struct [0x5528] {
    }
    [282] anonymous struct [0x5528] {
    }
    [283] anonymous struct [0x5528] {
    }
    [284] anonymous struct [0x5528] {
    }
    [285] anonymous struct [0x5528] {
    }
    [286] anonymous struct [0x5528] {
    }
    [287] anonymous struct [0x5528] {
    }
    [288] anonymous struct [0x5528] {
    }
    [289] anonymous struct [0x5528] {
    }
    [290] anonymous struct [0x5528] {
    }
    [291] anonymous struct [0x5528] {
    }
    [292] anonymous struct [0x5528] {
    }
    [293] anonymous struct [0x5528] {
    }
    [294] anonymous struct [0x5528] {
    }
    [295] anonymous struct [0x5528] {
    }
    [296] anonymous struct [0x5528] {
    }
    [297] anonymous struct [0x5528] {
    }
    [298] anonymous struct [0x5528] {
    }
    [299] anonymous struct [0x5528] {
    }
    [300] anonymous struct [0x5528] {
    }
    [301] anonymous struct [0x5528] {
    }
    [302] anonymous struct [0x5528] {
    }
    [303] anonymous struct [0x5528] {
    }
    [304] anonymous struct [0x5528] {
    }
    [305] anonymous struct [0x5528] {
    }
    [306] anonymous struct [0x5528] {
    }
    [307] anonymous struct [0x5528] {
    }
    [308] anonymous struct [0x5528] {
    }
    [309] anonymous struct [0x5528] {
    }
    [310] anonymous struct [0x5528] {
    }
    [311] anonymous struct [0x5528] {
    }
    [312] anonymous struct [0x5528] {
    }
    [313] anonymous struct [0x5528] {
    }
    [314] anonymous struct [0x5528] {
    }
    [315] anonymous struct [0x5528] {
    }
    [316] anonymous struct [0x5528] {
    }
    [317] anonymous struct [0x5528] {
    }
    [318] anonymous struct [0x5528] {
    }
    [319] anonymous struct [0x5528] {
    }
    [320] anonymous struct [0x5528] {
    }
    [321] anonymous struct [0x5528] {
    }
    [322] anonymous struct [0x5528] {
    }
    [323] anonymous struct [0x5528] {
    }
    [324] anonymous struct [0x5528] {
    }
    [325] anonymous struct [0x5528] {
    }
    [326] anonymous struct [0x5528] {
    }
    [327] anonymous struct [0x5528] {
    }
    [328] anonymous struct [0x5528] {
    }
    [329] anonymous struct [0x5528] {
    }
    [330] anonymous struct [0x5528] {
    }
    [331] anonymous struct [0x5528] {
    }
    [332] anonymous struct [0x5528] {
    }
    [333] anonymous struct [0x5528] {
    }
    [334] anonymous struct [0x5528] {
    }
    [335] anonymous struct [0x5528] {
    }
    [336] anonymous struct [0x5528] {
    }
    [337] anonymous struct [0x5528] {
    }
    [338] anonymous struct [0x5528] {
    }
    [339] anonymous struct [0x5528] {
    }
    [340] anonymous struct [0x5528] {
    }
    [341] anonymous struct [0x5528] {
    }
    [342] anonymous struct [0x5528] {
    }
    [343] anonymous struct [0x5528] {
    }
    [344] anonymous struct [0x5528] {
    }
    [345] anonymous struct [0x5528] {
    }
    [346] anonymous struct [0x5528] {
    }
    [347] anonymous struct [0x5528] {
    }
    [348] anonymous struct [0x5528] {
    }
    [349] anonymous struct [0x5528] {
    }
    [350] anonymous struct [0x5528] {
    }
    [351] anonymous struct [0x5528] {
    }
    [352] anonymous struct [0x5528] {
    }
    [353] anonymous struct [0x5528] {
    }
    [354] anonymous struct [0x5528] {
    }
    [355] anonymous struct [0x5528] {
    }
    [356] anonymous struct [0x5528] {
    }
    [357] anonymous struct [0x5528] {
    }
    [358] anonymous struct [0x5528] {
    }
    [359] anonymous struct [0x5528] {
    }
    [360] anonymous struct [0x5528] {
    }
    [361] anonymous struct [0x5528] {
    }
    [362] anonymous struct [0x5528] {
    }
    [363] anonymous struct [0x5528] {
    }
    [364] anonymous struct [0x5528] {
    }
    [365] anonymous struct [0x5528] {
    }
    [366] anonymous struct [0x5528] {
    }
    [367] anonymous struct [0x5528] {
    }
    [368] anonymous struct [0x5528] {
    }
    [369] anonymous struct [0x5528] {
    }
    [370] anonymous struct [0x5528] {
    }
    [371] anonymous struct [0x5528] {
    }
    [372] anonymous struct [0x5528] {
    }
    [373] anonymous struct [0x5528] {
    }
    [374] anonymous struct [0x5528] {
    }
    [375] anonymous struct [0x5528] {
    }
    [376] anonymous struct [0x5528] {
    }
    [377] anonymous struct [0x5528] {
    }
    [378] anonymous struct [0x5528] {
    }
    [379] anonymous struct [0x5528] {
    }
    [380] anonymous struct [0x5528] {
    }
    [381] anonymous struct [0x5528] {
    }
    [382] anonymous struct [0x5528] {
    }
    [383] anonymous struct [0x5528] {
    }
    [384] anonymous struct [0x5528] {
    }
    [385] anonymous struct [0x5528] {
    }
    [386] anonymous struct [0x5528] {
    }
    [387] anonymous struct [0x5528] {
    }
    [388] anonymous struct [0x5528] {
    }
    [389] anonymous struct [0x5528] {
    }
    [390] anonymous struct [0x5528] {
    }
    [391] anonymous struct [0x5528] {
    }
    [392] anonymous struct [0x5528] {
    }
    [393] anonymous struct [0x5528] {
    }
    [394] anonymous struct [0x5528] {
    }
    [395] anonymous struct [0x5528] {
    }
    [396] anonymous struct [0x5528] {
    }
    [397] anonymous struct [0x5528] {
    }
    [398] anonymous struct [0x5528] {
    }
    [399] anonymous struct [0x5528] {
    }
    [400] anonymous struct [0x5528] {
    }
    [401] anonymous struct [0x5528] {
    }
    [402] anonymous struct [0x5528] {
    }
    [403] anonymous struct [0x5528] {
    }
    [404] anonymous struct [0x5528] {
    }
    [405] anonymous struct [0x5528] {
    }
    [406] anonymous struct [0x5528] {
    }
    [407] anonymous struct [0x5528] {
    }
    [408] anonymous struct [0x5528] {
    }
    [409] anonymous struct [0x5528] {
    }
    [410] anonymous struct [0x5528] {
    }
    [411] anonymous struct [0x5528] {
    }
    [412] anonymous struct [0x5528] {
    }
    [413] anonymous struct [0x5528] {
    }
    [414] anonymous struct [0x5528] {
    }
    [415] anonymous struct [0x5528] {
    }
    [416] anonymous struct [0x5528] {
    }
    [417] anonymous struct [0x5528] {
    }
    [418] anonymous struct [0x5528] {
    }
    [419] anonymous struct [0x5528] {
    }
    [420] anonymous struct [0x5528] {
    }
    [421] anonymous struct [0x5528] {
    }
    [422] anonymous struct [0x5528] {
    }
    [423] anonymous struct [0x5528] {
    }
    [424] anonymous struct [0x5528] {
    }
    [425] anonymous struct [0x5528] {
    }
    [426] anonymous struct [0x5528] {
    }
    [427] anonymous struct [0x5528] {
    }
    [428] anonymous struct [0x5528] {
    }
    [429] anonymous struct [0x5528] {
    }
    [430] anonymous struct [0x5528] {
    }
    [431] anonymous struct [0x5528] {
    }
    [432] anonymous struct [0x5528] {
    }
    [433] anonymous struct [0x5528] {
    }
    [434] anonymous struct [0x5528] {
    }
    [435] anonymous struct [0x5528] {
    }
    [436] anonymous struct [0x5528] {
    }
    [437] anonymous struct [0x5528] {
    }
    [438] anonymous struct [0x5528] {
    }
    [439] anonymous struct [0x5528] {
    }
    [440] anonymous struct [0x5528] {
    }
    [441] anonymous struct [0x5528] {
    }
    [442] anonymous struct [0x5528] {
    }
    [443] anonymous struct [0x5528] {
    }
    [444] anonymous struct [0x5528] {
    }
    [445] anonymous struct [0x5528] {
    }
    [446] anonymous struct [0x5528] {
    }
    [447] anonymous struct [0x5528] {
    }
    [448] anonymous struct [0x5528] {
    }
    [449] anonymous struct [0x5528] {
    }
    [450] anonymous struct [0x5528] {
    }
    [451] anonymous struct [0x5528] {
    }
    [452] anonymous struct [0x5528] {
    }
    [453] anonymous struct [0x5528] {
    }
    [454] anonymous struct [0x5528] {
    }
    [455] anonymous struct [0x5528] {
    }
    [456] anonymous struct [0x5528] {
    }
    [457] anonymous struct [0x5528] {
    }
    [458] anonymous struct [0x5528] {
    }
    [459] anonymous struct [0x5528] {
    }
    [460] anonymous struct [0x5528] {
    }
    [461] anonymous struct [0x5528] {
    }
    [462] anonymous struct [0x5528] {
    }
    [463] anonymous struct [0x5528] {
    }
    [464] anonymous struct [0x5528] {
    }
    [465] anonymous struct [0x5528] {
    }
    [466] anonymous struct [0x5528] {
    }
    [467] anonymous struct [0x5528] {
    }
    [468] anonymous struct [0x5528] {
    }
    [469] anonymous struct [0x5528] {
    }
    [470] anonymous struct [0x5528] {
    }
    [471] anonymous struct [0x5528] {
    }
    [472] anonymous struct [0x5528] {
    }
    [473] anonymous struct [0x5528] {
    }
    [474] anonymous struct [0x5528] {
    }
    [475] anonymous struct [0x5528] {
    }
    [476] anonymous struct [0x5528] {
    }
    [477] anonymous struct [0x5528] {
    }
    [478] anonymous struct [0x5528] {
    }
    [479] anonymous struct [0x5528] {
    }
    [480] anonymous struct [0x5528] {
    }
    [481] anonymous struct [0x5528] {
    }
    [482] anonymous struct [0x5528] {
    }
    [483] anonymous struct [0x5528] {
    }
    [484] anonymous struct [0x5528] {
    }
    [485] anonymous struct [0x5528] {
    }
    [486] anonymous struct [0x5528] {
    }
    [487] anonymous struct [0x5528] {
    }
    [488] anonymous struct [0x5528] {
    }
    [489] anonymous struct [0x5528] {
    }
    [490] anonymous struct [0x5528] {
    }
    [491] anonymous struct [0x5528] {
    }
    [492] anonymous struct [0x5528] {
    }
    [493] anonymous struct [0x5528] {
    }
    [494] anonymous struct [0x5528] {
    }
    [495] anonymous struct [0x5528] {
    }
    [496] anonymous struct [0x5528] {
    }
    [497] anonymous struct [0x5528] {
    }
    [498] anonymous struct [0x5528] {
    }
    [499] anonymous struct [0x5528] {
    }
    [500] anonymous struct [0x5528] {
    }
    [501] anonymous struct [0x5528] {
    }
    [502] anonymous struct [0x5528] {
    }
    [503] anonymous struct [0x5528] {
    }
    [504] anonymous struct [0x5528] {
    }
    [505] anonymous struct [0x5528] {
    }
    [506] anonymous struct [0x5528] {
    }
    [507] anonymous struct [0x5528] {
    }
    [508] anonymous struct [0x5528] {
    }
    [509] anonymous struct [0x5528] {
    }
    [510] anonymous struct [0x5528] {
    }
    [511] anonymous struct [0x5528] {
    }
    [512] anonymous struct [0x5528] {
    }
    [513] anonymous struct [0x5528] {
    }
    [514] anonymous struct [0x5528] {
    }
    [515] anonymous struct [0x5528] {
    }
    [516] anonymous struct [0x5528] {
    }
    [517] anonymous struct [0x5528] {
    }
    [518] anonymous struct [0x5528] {
    }
    [519] anonymous struct [0x5528] {
    }
    [520] anonymous struct [0x5528] {
    }
    [521] anonymous struct [0x5528] {
    }
    [522] anonymous struct [0x5528] {
    }
    [523] anonymous struct [0x5528] {
    }
    [524] anonymous struct [0x5528] {
    }
    [525] anonymous struct [0x5528] {
    }
    [526] anonymous struct [0x5528] {
    }
    [527] anonymous struct [0x5528] {
    }
    [528] anonymous struct [0x5528] {
    }
    [529] anonymous struct [0x5528] {
    }
    [530] anonymous struct [0x5528] {
    }
    [531] anonymous struct [0x5528] {
    }
    [532] anonymous struct [0x5528] {
    }
    [533] anonymous struct [0x5528] {
    }
    [534] anonymous struct [0x5528] {
    }
    [535] anonymous struct [0x5528] {
    }
    [536] anonymous struct [0x5528] {
    }
    [537] anonymous struct [0x5528] {
    }
    [538] anonymous struct [0x5528] {
    }
    [539] anonymous struct [0x5528] {
    }
    [540] anonymous struct [0x5528] {
    }
    [541] anonymous struct [0x5528] {
    }
    [542] anonymous struct [0x5528] {
    }
    [543] anonymous struct [0x5528] {
    }
    [544] anonymous struct [0x5528] {
    }
    [545] anonymous struct [0x5528] {
    }
    [546] anonymous struct [0x5528] {
    }
    [547] anonymous struct [0x5528] {
    }
    [548] anonymous struct [0x5528] {
    }
    [549] anonymous struct [0x5528] {
    }
    [550] anonymous struct [0x5528] {
    }
    [551] anonymous struct [0x5528] {
    }
    [552] anonymous struct [0x5528] {
    }
    [553] anonymous struct [0x5528] {
    }
    [554] anonymous struct [0x5528] {
    }
    [555] anonymous struct [0x5528] {
    }
    [556] anonymous struct [0x5528] {
    }
    [557] anonymous struct [0x5528] {
    }
    [558] anonymous struct [0x5528] {
    }
    [559] anonymous struct [0x5528] {
    }
    [560] anonymous struct [0x5528] {
    }
    [561] anonymous struct [0x5528] {
    }
    [562] anonymous struct [0x5528] {
    }
    [563] anonymous struct [0x5528] {
    }
    [564] anonymous struct [0x5528] {
    }
    [565] anonymous struct [0x5528] {
    }
    [566] anonymous struct [0x5528] {
    }
    [567] anonymous struct [0x5528] {
    }
    [568] anonymous struct [0x5528] {
    }
    [569] anonymous struct [0x5528] {
    }
    [570] anonymous struct [0x5528] {
    }
    [571] anonymous struct [0x5528] {
    }
    [572] anonymous struct [0x5528] {
    }
    [573] anonymous struct [0x5528] {
    }
    [574] anonymous struct [0x5528] {
    }
    [575] anonymous struct [0x5528] {
    }
  }
  [61] volume-emitter-node [0x05700] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 0
    [5] int: 2
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] float: 0.20
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.10
    [17] float: 0.05
    [18] float: 0.10
    [19] float: 1.00
    [20] int: 0
    [21] float: 1.00
    [22] int: 0
    [23] int: 0
    [24] int: 0
    [25] int: 0
    [26] float: 2.00
    [27] int: 0
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 112460584, returning
  [63] array* [0x057E8] {
    [0] anonymous array with invalid size 112460736, returning
    [1] anonymous array [0x57f0] {size: 0} {
    }
    [2] int: 0
    [3] int: 0
    [4] int: 0
    [5] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 2564
  [111] int: 65536
  [112] int: 0
  [113] int: 0
  [114] float: 100.00
  [115] float: 120.00
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 262405
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 1.00
  [131] int: 131071
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 12  ##############################

efm-water-splash-cam-facing/spray = particle-effect-desc [0x058F0] {
  [0] int: 2336
  [1] int: -879207454
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: efm-water-splash-cam-facing/spray
  [7] int: 0
  [8] int: 0
  [9] sid: efm-water-splash-cam-facing
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 128
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 7
  [26] int: 514
  [27] sid: general/particles/water/spray-mist-2:default
  [28] int: 0
  [29] int: 524288
  [30] int: 1
  [31] int: 0
  [32] float: 40.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 196611
  [44] sid: #00120000000E004F
  [45] int: 538
  [46] int: 2883628
  [47] int: 29
  [48] int: 0
  [49] array [0x59d0] {size: 29} {
    [0] anonymous struct [0x5ba8] {
    }
    [1] anonymous struct [0x5ba8] {
    }
    [2] anonymous struct [0x5ba8] {
    }
    [3] anonymous struct [0x5ba8] {
    }
    [4] anonymous struct [0x5ba8] {
    }
    [5] anonymous struct [0x5ba8] {
    }
    [6] anonymous struct [0x5ba8] {
    }
    [7] anonymous struct [0x5ba8] {
    }
    [8] anonymous struct [0x5ba8] {
    }
    [9] anonymous struct [0x5ba8] {
    }
    [10] anonymous struct [0x5ba8] {
    }
    [11] anonymous struct [0x5ba8] {
    }
    [12] anonymous struct [0x5ba8] {
    }
    [13] anonymous struct [0x5ba8] {
    }
    [14] anonymous struct [0x5ba8] {
    }
    [15] anonymous struct [0x5ba8] {
    }
    [16] anonymous struct [0x5ba8] {
    }
    [17] anonymous struct [0x5ba8] {
    }
    [18] anonymous struct [0x5ba8] {
    }
    [19] anonymous struct [0x5ba8] {
    }
    [20] anonymous struct [0x5ba8] {
    }
    [21] anonymous struct [0x5ba8] {
    }
    [22] anonymous struct [0x5ba8] {
    }
    [23] anonymous struct [0x5ba8] {
    }
    [24] anonymous struct [0x5ba8] {
    }
    [25] anonymous struct [0x5ba8] {
    }
    [26] anonymous struct [0x5ba8] {
    }
    [27] anonymous struct [0x5ba8] {
    }
    [28] anonymous struct [0x5ba8] {
    }
  }
  [50] array [0x59d8] {size: (112461560, 112461544) (*invalid*)} {  }
  [51] array [0x59e0] {size: (112461584, 112461552) (*invalid*)} {  }
  [52] array [0x59e8] {size: (112461712, 112461560) (*invalid*)} {  }
  [53] array [0x59f0] {size: (112462040, 112461584) (*invalid*)} {  }
  [54] array [0x59f8] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x5a10] {size: 0} {
  }
  [60] array [0x5a18] {size: (112462688, 112462104) (*invalid*)} {  }
  [61] volume-emitter-node [0x06020] {
    [0] int: 1
    [1] int: 1
    [2] float: 1.00
    [3] int: 0
    [4] int: 393289
    [5] int: 0
    [6] float: 6.28
    [7] float: 0.50
    [8] int: 0
    [9] int: 0
    [10] int: 0
    [11] int: 0
    [12] int: 0
    [13] int: 0
    [14] int: 0
    [15] int: 0
    [16] float: 0.08
    [17] float: 0.10
    [18] float: 0.08
    [19] float: 1.00
    [20] int: 0
    [21] float: 1.00
    [22] int: 0
    [23] int: 0
    [24] float: 0.37
    [25] float: 0.05
    [26] float: 3.00
    [27] float: 1.50
    [28] int: 0
    [29] int: 0
    [30] int: 0
    [31] int: 0
    [32] int: 0
    [33] int: 0
  }
  [62] anonymous array with invalid size 112462920, returning
  [63] array* [0x06108] {
    [0] anonymous array with invalid size 112463072, returning
    [1] anonymous array [0x6110] {size: 0} {
    }
    [2] int: 0
    [3] int: 0
    [4] int: 0
    [5] int: 0
  }
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 1540
  [111] int: 66561
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] int: 0
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.20
  [131] int: 131071
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] int: 0
  [141] int: 0
  [142] int: 0
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}


##############################  ENTRY 13  ##############################

efm-water-splash-cam-facing = effect-group-desc [0x06210] {
  [0] int: 1380
  [1] int: -1458240536
  [2] sid: efm-water-splash-cam-facing
  [3] int: 0
  [4] int: 0
  [5] int: 49169
  [6] int: 0
  [7] int: 0
  [8] int: 0
  [9] int: 5
  [10] int: 0
  [11] array [0x6240] {size: 5} {
    [0] anonymous struct [0x62d8] {
      [0] sid: game
    }
    [1] anonymous struct [0x62de] {
      [0] sid: game
    }
    [2] anonymous struct [0x62e4] {
      [0] sid: levels
    }
    [3] anonymous struct [0x62ea] {
      [0] sid: efm
    }
    [4] anonymous struct [0x62f0] {
      [0] int: 0
      [1] int: 0
    }
  }
  [12] string: "comments go here"
  [13] int: 0
  [14] int: 0
  [15] int: 25
  [16] int: 0
  [17] anonymous array with invalid size 112463456, returning
  [18] array [0x6268] {size: 0} {
  }
  [19] int: 0
  [20] int: 0
  [21] int: 0
  [22] int: 0
  [23] array [0x6280] {size: 0} {
  }
  [24] array* [0x063C0] {
    [0] int: 0
    [1] int: 0
    [2] int: 0
    [3] int: 0
    [4] int: 0
    [5] int: 0
    [6] int: 0
    [7] int: 0
    [8] int: 0
    [9] int: 0
  }
  [25] array [0x6290] {size: 0} {
  }
  [26] int: 0
  [27] int: 0
  [28] int: 0
  [29] int: 0
  [30] int: 0
  [31] int: 0
  [32] int: 0
  [33] int: 0
  [34] int: 0
  [35] int: 0
  [36] int: 0
  [37] int: 0
  [38] int: 0
  [39] int: 0
}


##############################  ENTRY 14  ##############################

nav-boar-dirt-kickup/squib_stones_NEAR = particle-effect-desc [0x06770] {
  [0] int: 2436
  [1] int: 1660460477
  [2] int: 0
  [3] int: 0
  [4] int: 3595868
  [5] int: 0
  [6] sid: nav-boar-dirt-kickup/squib_stones_NEAR
  [7] int: 0
  [8] int: 0
  [9] sid: nav-boar-dirt-kickup
  [10] int: 0
  [11] int: 0
  [12] int: 0
  [13] int: 0
  [14] int: 0
  [15] int: 0
  [16] sid: default
  [17] sid: default
  [18] sid: default
  [19] int: 0
  [20] int: 0
  [21] int: 6422592
  [22] int: 0
  [23] int: 0
  [24] int: 0
  [25] int: 9
  [26] int: 0
  [27] sid: art/particles/geometry/debris-rubble-chunky.ma
  [28] int: 0
  [29] int: 0
  [30] int: 1
  [31] int: 0
  [32] float: 999.00
  [33] float: 1.00
  [34] int: 0
  [35] int: 0
  [36] float: 1.00
  [37] float: 1.00
  [38] int: 0
  [39] int: 0
  [40] int: 0
  [41] float: -1.00
  [42] int: 0
  [43] int: 524292
  [44] sid: #000E00000010006A
  [45] int: 31
  [46] int: 4128831
  [47] int: 35
  [48] int: 0
  [49] array [0x6850] {size: 35} {
    [0] anonymous struct [0x6a28] {
    }
    [1] anonymous struct [0x6a28] {
    }
    [2] anonymous struct [0x6a28] {
    }
    [3] anonymous struct [0x6a28] {
    }
    [4] anonymous struct [0x6a28] {
    }
    [5] anonymous struct [0x6a28] {
    }
    [6] anonymous struct [0x6a28] {
    }
    [7] anonymous struct [0x6a28] {
    }
    [8] anonymous struct [0x6a28] {
    }
    [9] anonymous struct [0x6a28] {
    }
    [10] anonymous struct [0x6a28] {
    }
    [11] anonymous struct [0x6a28] {
    }
    [12] anonymous struct [0x6a28] {
    }
    [13] anonymous struct [0x6a28] {
    }
    [14] anonymous struct [0x6a28] {
    }
    [15] anonymous struct [0x6a28] {
    }
    [16] anonymous struct [0x6a28] {
    }
    [17] anonymous struct [0x6a28] {
    }
    [18] anonymous struct [0x6a28] {
    }
    [19] anonymous struct [0x6a28] {
    }
    [20] anonymous struct [0x6a28] {
    }
    [21] anonymous struct [0x6a28] {
    }
    [22] anonymous struct [0x6a28] {
    }
    [23] anonymous struct [0x6a28] {
    }
    [24] anonymous struct [0x6a28] {
    }
    [25] anonymous struct [0x6a28] {
    }
    [26] anonymous struct [0x6a28] {
    }
    [27] anonymous struct [0x6a28] {
    }
    [28] anonymous struct [0x6a28] {
    }
    [29] anonymous struct [0x6a28] {
    }
    [30] anonymous struct [0x6a28] {
    }
    [31] anonymous struct [0x6a28] {
    }
    [32] anonymous struct [0x6a28] {
    }
    [33] anonymous struct [0x6a28] {
    }
    [34] anonymous struct [0x6a28] {
    }
  }
  [50] array [0x6858] {size: (112465272, 112465256) (*invalid*)} {  }
  [51] array [0x6860] {size: (112465296, 112465264) (*invalid*)} {  }
  [52] array [0x6868] {size: (112465624, 112465272) (*invalid*)} {  }
  [53] array [0x6870] {size: (112466056, 112465296) (*invalid*)} {  }
  [54] array [0x6878] {size: 0} {
  }
  [55] int: 0
  [56] int: 0
  [57] int: 0
  [58] int: 0
  [59] array [0x6890] {size: 0} {
  }
  [60] array [0x6898] {size: (112466768, 112466128) (*invalid*)} {  }
  [61] anonymous array with invalid size 112466896, returning
  [62] anonymous array with invalid size 112466984, returning
  [63] string: "comments go here"
  [64] int: 0
  [65] int: 0
  [66] int: 0
  [67] int: 0
  [68] int: 0
  [69] int: 0
  [70] int: 8
  [71] int: 1
  [72] int: 0
  [73] int: 0
  [74] int: 0
  [75] int: 0
  [76] int: 0
  [77] int: 0
  [78] float: 0.02
  [79] int: 0
  [80] float: 1.00
  [81] float: 1.00
  [82] int: 0
  [83] int: 0
  [84] int: 0
  [85] int: 0
  [86] int: 0
  [87] int: 0
  [88] float: 1.00
  [89] float: -0.00
  [90] int: 0
  [91] float: 10.00
  [92] int: 0
  [93] int: 0
  [94] float: 0.02
  [95] int: 0
  [96] int: 0
  [97] int: 0
  [98] int: 0
  [99] int: 0
  [100] int: 0
  [101] int: 0
  [102] int: 259
  [103] int: 0
  [104] int: 0
  [105] float: -1.00
  [106] int: 0
  [107] int: 0
  [108] float: -1.00
  [109] int: 0
  [110] int: 772
  [111] int: 65537
  [112] int: 0
  [113] int: 0
  [114] int: 0
  [115] int: 0
  [116] float: 1.00
  [117] float: 1.00
  [118] int: 0
  [119] int: 0
  [120] int: 0
  [121] int: 66306
  [122] int: 1
  [123] int: 0
  [124] int: 0
  [125] int: 16842752
  [126] int: 0
  [127] int: 0
  [128] int: 0
  [129] int: 0
  [130] float: 0.20
  [131] int: 131071
  [132] int: 0
  [133] int: 0
  [134] int: 0
  [135] int: 0
  [136] int: 0
  [137] int: 0
  [138] int: 0
  [139] int: 0
  [140] float: 0.10
  [141] float: 7.99
  [142] float: 8.00
  [143] int: 0
  [144] int: 0
  [145] float: 1.00
  [146] int: 0
  [147] int: 0
  [148] int: 0
  [149] int: 0
  [150] int: 0
  [151] int: 0
  [152] int: 0
  [153] int: 0
}
