####################################################################################################
#                                                                                                  #
#   generated by dconstruct ver. 2.1.0                                                             #
#   listing for file: ...art II/build/pc/main/bin_unpacked/dc1\ss-floodedcity\ss-flo-see-boat.bin  #
#   filesize: 13679 bytes                                                                          #
#   total entries: 1                                                                               #
#   functions: 33                                                                                  #
#   has state script: true                                                                         #
#   game type: t2r                                                                                 #
#   optimizations enabled: sso var, foreach, match, second var, member access, regex               #
#                                                                                                  #
####################################################################################################



##############################  ENTRY 0  ##############################

ss-flo-see-boat = state-script [0x00048] {
  statescript #ss-flo-see-boat {
    options {
      #player
      #jesse
      #flo-mall-entrance-script
      #cin-flo-see-boat-1
    }
    declarations {
      #player-anim-entry
      #anim-entry-edge-spline-loc
      #adjusted-ap
      #tasked-in?
    }
    state task-check {
      block start {
        track main {
          lambda task-check@start@main@0 {
            0000   0x002D48   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-complete?>
            0001   0x002D50   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <flooded-city>
            0002   0x002D58   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <flo-see-boat>
            0003   0x002D60   43 31 01 00   Move                 r49, r1       r49 = flooded-city
            0004   0x002D68   43 32 02 00   Move                 r50, r2       r50 = flo-see-boat
            0005   0x002D70   1B 00 00 02   Call                 r0, r0, 2     r0 = task-complete?(flooded-city, flo-see-boat)
            0006   0x002D78   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 
            0007   0x002D80   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x002D88   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <complete>
            0009   0x002D90   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x002D98   43 31 01 00   Move                 r49, r1       r49 = complete
            000B   0x002DA0   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x002DA8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            000D   0x002DB0   2D 0F 00 00   Branch               0xF           GOTO 
            000E   0x002DB8   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            000F   0x002DC0   00 00 00 00   Return               r0            Return 
          }
          lambda task-check@start@main@1 {
            0000   0x001928   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-active?>
            0001   0x001930   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <flooded-city>
            0002   0x001938   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <flo-see-boat>
            0003   0x001940   43 31 01 00   Move                 r49, r1       r49 = flooded-city
            0004   0x001948   43 32 02 00   Move                 r50, r2       r50 = flo-see-boat
            0005   0x001950   1B 00 00 02   Call                 r0, r0, 2     r0 = task-active?(flooded-city, flo-see-boat)
            0006   0x001958   2F 16 00 00   BranchIfNot          r0, 0x16      IF NOT r0 
            0007   0x001960   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <set-boolean>
            0008   0x001968   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <tasked-in?>
            0009   0x001970   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x001978   4A 03 05 00   LoadStaticU64Imm     r3, 5         r3 = ST[5] -> <self>
            000B   0x001980   43 31 01 00   Move                 r49, r1       r49 = tasked-in?
            000C   0x001988   43 32 02 00   Move                 r50, r2       r50 = 1
            000D   0x001990   43 33 03 00   Move                 r51, r3       r51 = self
            000E   0x001998   1C 00 00 03   CallFf               r0, r0, 3     r0 = set-boolean(tasked-in?, 1, self)
            000F   0x0019A0   15 00 06 00   LookupPointer        r0, 6         r0 = ST[6] -> <go>
            0010   0x0019A8   4A 01 07 00   LoadStaticU64Imm     r1, 7         r1 = ST[7] -> <cine-start-on-task-in>
            0011   0x0019B0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0012   0x0019B8   43 31 01 00   Move                 r49, r1       r49 = cine-start-on-task-in
            0013   0x0019C0   43 32 02 00   Move                 r50, r2       r50 = 1
            0014   0x0019C8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(cine-start-on-task-in, 1)
            0015   0x0019D0   2D 17 00 00   Branch               0x17          GOTO 
            0016   0x0019D8   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            0017   0x0019E0   00 00 00 00   Return               r0            Return 
          }
          lambda task-check@start@main@2 {
            0000   0x002F88   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-active?>
            0001   0x002F90   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <flooded-city>
            0002   0x002F98   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <flo-flooded-street-building-exit>
            0003   0x002FA0   43 31 01 00   Move                 r49, r1       r49 = flooded-city
            0004   0x002FA8   43 32 02 00   Move                 r50, r2       r50 = flo-flooded-street-building-exit
            0005   0x002FB0   1B 00 00 02   Call                 r0, r0, 2     r0 = task-active?(flooded-city, flo-flooded-street-building-exit)
            0006   0x002FB8   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 
            0007   0x002FC0   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x002FC8   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <wait-for-vault>
            0009   0x002FD0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x002FD8   43 31 01 00   Move                 r49, r1       r49 = wait-for-vault
            000B   0x002FE0   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x002FE8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(wait-for-vault, 1)
            000D   0x002FF0   2D 0F 00 00   Branch               0xF           GOTO 
            000E   0x002FF8   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            000F   0x003000   00 00 00 00   Return               r0            Return 
          }
        }
      }
      block event task-complete {
        track main {
          lambda task-check@event_task-complete@main@0 {
            0000   0x002F88   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-active?>
            0001   0x002F90   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <flooded-city>
            0002   0x002F98   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <flo-flooded-street-building-exit>
            0003   0x002FA0   43 31 01 00   Move                 r49, r1       r49 = flooded-city
            0004   0x002FA8   43 32 02 00   Move                 r50, r2       r50 = flo-flooded-street-building-exit
            0005   0x002FB0   1B 00 00 02   Call                 r0, r0, 2     r0 = task-active?(flooded-city, flo-flooded-street-building-exit)
            0006   0x002FB8   2F 0E 00 00   BranchIfNot          r0, 0xE       IF NOT r0 
            0007   0x002FC0   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <go>
            0008   0x002FC8   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <wait-for-vault>
            0009   0x002FD0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            000A   0x002FD8   43 31 01 00   Move                 r49, r1       r49 = wait-for-vault
            000B   0x002FE0   43 32 02 00   Move                 r50, r2       r50 = 1
            000C   0x002FE8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(wait-for-vault, 1)
            000D   0x002FF0   2D 0F 00 00   Branch               0xF           GOTO 
            000E   0x002FF8   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            000F   0x003000   00 00 00 00   Return               r0            Return 
          }
        }
      }
    }
    state wait-for-vault {
      block start {
        track main {
          lambda wait-for-vault@start@main@0 {
            0000   0x0031A8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <set-bound-frame>
            0001   0x0031B0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <player-anim-entry>
            0002   0x0031B8   15 02 02 00   LookupPointer        r2, 2         r2 = ST[2] -> <get-animation-entry>
            0003   0x0031C0   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <player>
            0004   0x0031C8   4A 04 04 00   LoadStaticU64Imm     r4, 4         r4 = ST[4] -> <ellie=cin-flo-see-boat=010>
            0005   0x0031D0   15 05 05 00   LookupPointer        r5, 5         r5 = ST[5] -> <get-spawner-locator>
            0006   0x0031D8   4A 06 06 00   LoadStaticU64Imm     r6, 6         r6 = ST[6] -> <cin-flo-see-boat-1>
            0007   0x0031E0   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0008   0x0031E8   43 31 06 00   Move                 r49, r6       r49 = cin-flo-see-boat-1
            0009   0x0031F0   43 32 07 00   Move                 r50, r7       r50 = 1
            000A   0x0031F8   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-spawner-locator(cin-flo-see-boat-1, 1)
            000B   0x003200   0C 06 00 00   LoadU16Imm           r6, 0         r6 = 0
            000C   0x003208   40 07 07 00   LoadStaticFloatImm   r7, 7         r7 = ST[7] -> <0.000000>
            000D   0x003210   4A 08 08 00   LoadStaticU64Imm     r8, 8         r8 = ST[8] -> <apReference>
            000E   0x003218   43 31 03 00   Move                 r49, r3       r49 = player
            000F   0x003220   43 32 04 00   Move                 r50, r4       r50 = ellie=cin-flo-see-boat=010
            0010   0x003228   43 33 05 00   Move                 r51, r5       r51 = RET_get-spawner-locator
            0011   0x003230   43 34 06 00   Move                 r52, r6       r52 = 0
            0012   0x003238   43 35 07 00   Move                 r53, r7       r53 = 0.000000
            0013   0x003240   43 36 08 00   Move                 r54, r8       r54 = apReference
            0014   0x003248   1C 02 02 06   CallFf               r2, r2, 6     r2 = get-animation-entry(player, ellie=cin-flo-see-boat=010, RET_get-spawner-locator, 0, 0.000000, apReference)
            0015   0x003250   4A 03 09 00   LoadStaticU64Imm     r3, 9         r3 = ST[9] -> <self>
            0016   0x003258   43 31 01 00   Move                 r49, r1       r49 = player-anim-entry
            0017   0x003260   43 32 02 00   Move                 r50, r2       r50 = RET_get-animation-entry
            0018   0x003268   43 33 03 00   Move                 r51, r3       r51 = self
            0019   0x003270   1C 00 00 03   CallFf               r0, r0, 3     r0 = set-bound-frame(player-anim-entry, RET_get-animation-entry, self)
            001A   0x003278   00 00 00 00   Return               r0            Return 
          }
          lambda wait-for-vault@start@main@1 {
            0000   0x003030   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <set-bound-frame>
            0001   0x003038   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <anim-entry-edge-spline-loc>
            0002   0x003040   15 02 02 00   LookupPointer        r2, 2         r2 = ST[2] -> <spline-locator-closest-to-locator>
            0003   0x003048   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <spl-flo-see-boat-vault-trigger-edge-1>
            0004   0x003050   15 04 04 00   LookupPointer        r4, 4         r4 = ST[4] -> <get-bound-frame>
            0005   0x003058   4A 05 05 00   LoadStaticU64Imm     r5, 5         r5 = ST[5] -> <player-anim-entry>
            0006   0x003060   4A 06 06 00   LoadStaticU64Imm     r6, 6         r6 = ST[6] -> <self>
            0007   0x003068   43 31 05 00   Move                 r49, r5       r49 = player-anim-entry
            0008   0x003070   43 32 06 00   Move                 r50, r6       r50 = self
            0009   0x003078   1C 04 04 02   CallFf               r4, r4, 2     r4 = get-bound-frame(player-anim-entry, self)
            000A   0x003080   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            000B   0x003088   43 31 03 00   Move                 r49, r3       r49 = spl-flo-see-boat-vault-trigger-edge-1
            000C   0x003090   43 32 04 00   Move                 r50, r4       r50 = RET_get-bound-frame
            000D   0x003098   43 33 05 00   Move                 r51, r5       r51 = 1
            000E   0x0030A0   1B 02 02 03   Call                 r2, r2, 3     r2 = spline-locator-closest-to-locator(spl-flo-see-boat-vault-trigger-edge-1, RET_get-bound-frame, 1)
            000F   0x0030A8   4A 03 06 00   LoadStaticU64Imm     r3, 6         r3 = ST[6] -> <self>
            0010   0x0030B0   43 31 01 00   Move                 r49, r1       r49 = anim-entry-edge-spline-loc
            0011   0x0030B8   43 32 02 00   Move                 r50, r2       r50 = RET_spline-locator-closest-to-locator
            0012   0x0030C0   43 33 03 00   Move                 r51, r3       r51 = self
            0013   0x0030C8   1C 00 00 03   CallFf               r0, r0, 3     r0 = set-bound-frame(anim-entry-edge-spline-loc, RET_spline-locator-closest-to-locator, self)
            0014   0x0030D0   00 00 00 00   Return               r0            Return 
          }
        }
      }
      block event inside {
        track main {
          lambda wait-for-vault@event_inside@main@0 {
            0000   0x002DF0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <get-player-weapon-type>
            0001   0x002DF8   1B 00 00 00   Call                 r0, r0, 0     r0 = get-player-weapon-type()
            0002   0x002E00   0C 01 02 00   LoadU16Imm           r1, 2         r1 = 2
            0003   0x002E08   1D 00 00 01   IEqual               r0, r0, r1    r0 = r0 == r1
            0004   0x002E10   2F 13 00 00   BranchIfNot          r0, 0x13      IF NOT r0 
            0005   0x002E18   15 00 01 00   LookupPointer        r0, 1         r0 = ST[1] -> <holster-player-weapon>
            0006   0x002E20   15 01 02 00   LookupPointer        r1, 2         r1 = ST[2] -> <get-player-speed>
            0007   0x002E28   1C 01 01 00   CallFf               r1, r1, 0     r1 = get-player-speed()
            0008   0x002E30   40 02 03 00   LoadStaticFloatImm   r2, 3         r2 = ST[3] -> <3.000000>
            0009   0x002E38   23 01 01 02   FGreaterThan         r1, r1, r2    r1 = r1 > r2
            000A   0x002E40   2F 0D 01 00   BranchIfNot          r1, 0xD       IF NOT r1 
            000B   0x002E48   0C 01 02 00   LoadU16Imm           r1, 2         r1 = 2
            000C   0x002E50   2D 0E 00 00   Branch               0xE           GOTO 
            000D   0x002E58   0C 01 00 00   LoadU16Imm           r1, 0         r1 = 0
            000E   0x002E60   40 02 04 00   LoadStaticFloatImm   r2, 4         r2 = ST[4] -> <1.000000>
            000F   0x002E68   43 31 01 00   Move                 r49, r1       r49 = 0
            0010   0x002E70   43 32 02 00   Move                 r50, r2       r50 = 1.000000
            0011   0x002E78   1C 00 00 02   CallFf               r0, r0, 2     r0 = holster-player-weapon(0, 1.000000)
            0012   0x002E80   2D 14 00 00   Branch               0x14          GOTO 
            0013   0x002E88   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            0014   0x002E90   00 00 00 00   Return               r0            Return 
          }
          lambda wait-for-vault@event_inside@main@1 {
            0000   0x002828   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <player-disable-unholstering>
            0001   0x002830   1C 00 00 00   CallFf               r0, r0, 0     r0 = player-disable-unholstering()
            0002   0x002838   00 00 00 00   Return               r0            Return 
          }
        }
      }
      block event player-climb-jump {
        track main {
          lambda wait-for-vault@event_player-climb-jump@main@0 {
            0000   0x001E80   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <locator-in-region?>
            0001   0x001E88   15 01 01 00   LookupPointer        r1, 1         r1 = ST[1] -> <event-arg-bound-frame>
            0002   0x001E90   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x001E98   43 31 02 00   Move                 r49, r2       r49 = 1
            0004   0x001EA0   1C 01 01 01   CallFf               r1, r1, 1     r1 = event-arg-bound-frame(1)
            0005   0x001EA8   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <rgn-flo-see-boat-vault-trigger-1>
            0006   0x001EB0   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <player>
            0007   0x001EB8   43 31 01 00   Move                 r49, r1       r49 = RET_event-arg-bound-frame
            0008   0x001EC0   43 32 02 00   Move                 r50, r2       r50 = rgn-flo-see-boat-vault-trigger-1
            0009   0x001EC8   43 33 03 00   Move                 r51, r3       r51 = player
            000A   0x001ED0   1C 00 00 03   CallFf               r0, r0, 3     r0 = locator-in-region?(RET_event-arg-bound-frame, rgn-flo-see-boat-vault-trigger-1, player)
            000B   0x001ED8   2F 3E 00 00   BranchIfNot          r0, 0x3E      IF NOT r0 
            000C   0x001EE0   15 00 04 00   LookupPointer        r0, 4         r0 = ST[4] -> <spline-locator-closest-to-locator>
            000D   0x001EE8   4A 01 05 00   LoadStaticU64Imm     r1, 5         r1 = ST[5] -> <spl-flo-see-boat-vault-trigger-edge-1>
            000E   0x001EF0   15 02 01 00   LookupPointer        r2, 1         r2 = ST[1] -> <event-arg-bound-frame>
            000F   0x001EF8   0C 03 01 00   LoadU16Imm           r3, 1         r3 = 1
            0010   0x001F00   43 31 03 00   Move                 r49, r3       r49 = 1
            0011   0x001F08   1C 02 02 01   CallFf               r2, r2, 1     r2 = event-arg-bound-frame(1)
            0012   0x001F10   0C 03 01 00   LoadU16Imm           r3, 1         r3 = 1
            0013   0x001F18   43 31 01 00   Move                 r49, r1       r49 = spl-flo-see-boat-vault-trigger-edge-1
            0014   0x001F20   43 32 02 00   Move                 r50, r2       r50 = RET_event-arg-bound-frame
            0015   0x001F28   43 33 03 00   Move                 r51, r3       r51 = 1
            0016   0x001F30   1B 00 00 03   Call                 r0, r0, 3     r0 = spline-locator-closest-to-locator(spl-flo-see-boat-vault-trigger-edge-1, RET_event-arg-bound-frame, 1)
            0017   0x001F38   15 01 06 00   LookupPointer        r1, 6         r1 = ST[6] -> <vector-between-locators>
            0018   0x001F40   15 02 07 00   LookupPointer        r2, 7         r2 = ST[7] -> <get-bound-frame>
            0019   0x001F48   4A 03 08 00   LoadStaticU64Imm     r3, 8         r3 = ST[8] -> <anim-entry-edge-spline-loc>
            001A   0x001F50   4A 04 09 00   LoadStaticU64Imm     r4, 9         r4 = ST[9] -> <self>
            001B   0x001F58   43 31 03 00   Move                 r49, r3       r49 = anim-entry-edge-spline-loc
            001C   0x001F60   43 32 04 00   Move                 r50, r4       r50 = self
            001D   0x001F68   1C 02 02 02   CallFf               r2, r2, 2     r2 = get-bound-frame(anim-entry-edge-spline-loc, self)
            001E   0x001F70   43 03 00 00   Move                 r3, r0        r3 = RET_spline-locator-closest-to-locator
            001F   0x001F78   43 31 02 00   Move                 r49, r2       r49 = RET_get-bound-frame
            0020   0x001F80   43 32 03 00   Move                 r50, r3       r50 = RET_spline-locator-closest-to-locator
            0021   0x001F88   1B 01 01 02   Call                 r1, r1, 2     r1 = vector-between-locators(RET_get-bound-frame, RET_spline-locator-closest-to-locator)
            0022   0x001F90   15 02 0A 00   LookupPointer        r2, 10        r2 = ST[10] -> <set-bound-frame>
            0023   0x001F98   4A 03 0B 00   LoadStaticU64Imm     r3, 11        r3 = ST[11] -> <adjusted-ap>
            0024   0x001FA0   15 04 0C 00   LookupPointer        r4, 12        r4 = ST[12] -> <offset-locator-world-space>
            0025   0x001FA8   15 05 0D 00   LookupPointer        r5, 13        r5 = ST[13] -> <get-spawner-locator>
            0026   0x001FB0   4A 06 0E 00   LoadStaticU64Imm     r6, 14        r6 = ST[14] -> <cin-flo-see-boat-1>
            0027   0x001FB8   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0028   0x001FC0   43 31 06 00   Move                 r49, r6       r49 = cin-flo-see-boat-1
            0029   0x001FC8   43 32 07 00   Move                 r50, r7       r50 = 1
            002A   0x001FD0   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-spawner-locator(cin-flo-see-boat-1, 1)
            002B   0x001FD8   43 06 01 00   Move                 r6, r1        r6 = RET_vector-between-locators
            002C   0x001FE0   43 31 05 00   Move                 r49, r5       r49 = RET_get-spawner-locator
            002D   0x001FE8   43 32 06 00   Move                 r50, r6       r50 = RET_vector-between-locators
            002E   0x001FF0   1B 04 04 02   Call                 r4, r4, 2     r4 = offset-locator-world-space(RET_get-spawner-locator, RET_vector-between-locators)
            002F   0x001FF8   4A 05 09 00   LoadStaticU64Imm     r5, 9         r5 = ST[9] -> <self>
            0030   0x002000   43 31 03 00   Move                 r49, r3       r49 = adjusted-ap
            0031   0x002008   43 32 04 00   Move                 r50, r4       r50 = RET_offset-locator-world-space
            0032   0x002010   43 33 05 00   Move                 r51, r5       r51 = self
            0033   0x002018   1C 02 02 03   CallFf               r2, r2, 3     r2 = set-bound-frame(adjusted-ap, RET_offset-locator-world-space, self)
            0034   0x002020   43 02 02 00   Move                 r2, r2        r2 = RET_set-bound-frame
            0035   0x002028   43 01 02 00   Move                 r1, r2        r1 = RET_set-bound-frame
            0036   0x002030   43 00 01 00   Move                 r0, r1        r0 = RET_set-bound-frame
            0037   0x002038   15 00 0F 00   LookupPointer        r0, 15        r0 = ST[15] -> <go>
            0038   0x002040   4A 01 10 00   LoadStaticU64Imm     r1, 16        r1 = ST[16] -> <cine-start-on-progression>
            0039   0x002048   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            003A   0x002050   43 31 01 00   Move                 r49, r1       r49 = cine-start-on-progression
            003B   0x002058   43 32 02 00   Move                 r50, r2       r50 = 1
            003C   0x002060   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(cine-start-on-progression, 1)
            003D   0x002068   2D 3F 00 00   Branch               0x3F          GOTO 
            003E   0x002070   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            003F   0x002078   00 00 00 00   Return               r0            Return 
          }
        }
      }
    }
    state cine-start-on-task-in {
      block start {
        track main {
          lambda cine-start-on-task-in@start@main@0 {
            0000   0x001888   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <camera-enable-animated>
            0001   0x001890   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <0.000000>
            0002   0x001898   40 02 02 00   LoadStaticFloatImm   r2, 2         r2 = ST[2] -> <-1.000000>
            0003   0x0018A0   0C 03 01 00   LoadU16Imm           r3, 1         r3 = 1
            0004   0x0018A8   0C 04 E8 03   LoadU16Imm           r4, 1000      r4 = 1000
            0005   0x0018B0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0006   0x0018B8   0C 06 00 00   LoadU16Imm           r6, 0         r6 = 0
            0007   0x0018C0   0C 07 00 00   LoadU16Imm           r7, 0         r7 = 0
            0008   0x0018C8   43 31 01 00   Move                 r49, r1       r49 = 0.000000
            0009   0x0018D0   43 32 02 00   Move                 r50, r2       r50 = -1.000000
            000A   0x0018D8   43 33 03 00   Move                 r51, r3       r51 = 1
            000B   0x0018E0   43 34 04 00   Move                 r52, r4       r52 = 1000
            000C   0x0018E8   43 35 05 00   Move                 r53, r5       r53 = 0
            000D   0x0018F0   43 36 06 00   Move                 r54, r6       r54 = 0
            000E   0x0018F8   43 37 07 00   Move                 r55, r7       r55 = 0
            000F   0x001900   1C 00 00 07   CallFf               r0, r0, 7     r0 = camera-enable-animated(0.000000, -1.000000, 1, 1000, 0, 0, 0)
            0010   0x001908   00 00 00 00   Return               r0            Return 
          }
          lambda cine-start-on-task-in@start@main@1 {
            0000   0x002848   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x002850   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <play-cine>
            0002   0x002858   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x002860   43 31 01 00   Move                 r49, r1       r49 = play-cine
            0004   0x002868   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x002870   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(play-cine, 1)
            0006   0x002878   00 00 00 00   Return               r0            Return 
          }
        }
      }
    }
    state cine-start-on-progression {
      block start {
        track main {
          lambda cine-start-on-progression@start@main@0 {
            0000   0x003110   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-complete!>
            0001   0x003118   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <flooded-city>
            0002   0x003120   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <flo-flooded-street-building-exit>
            0003   0x003128   43 31 01 00   Move                 r49, r1       r49 = flooded-city
            0004   0x003130   43 32 02 00   Move                 r50, r2       r50 = flo-flooded-street-building-exit
            0005   0x003138   1B 00 00 02   Call                 r0, r0, 2     r0 = task-complete!(flooded-city, flo-flooded-street-building-exit)
            0006   0x003140   00 00 00 00   Return               r0            Return 
          }
          lambda cine-start-on-progression@start@main@1 {
            0000   0x003160   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <holster-player-weapon>
            0001   0x003168   0C 01 02 00   LoadU16Imm           r1, 2         r1 = 2
            0002   0x003170   40 02 01 00   LoadStaticFloatImm   r2, 1         r2 = ST[1] -> <1.000000>
            0003   0x003178   43 31 01 00   Move                 r49, r1       r49 = 2
            0004   0x003180   43 32 02 00   Move                 r50, r2       r50 = 1.000000
            0005   0x003188   1C 00 00 02   CallFf               r0, r0, 2     r0 = holster-player-weapon(2, 1.000000)
            0006   0x003190   00 00 00 00   Return               r0            Return 
          }
          lambda cine-start-on-progression@start@main@2 {
            0000   0x001A28   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <animate_>
            0001   0x001A30   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <player>
            0002   0x001A38   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <ellie=cin-flo-see-boat=010>
            0003   0x001A40   15 03 03 00   LookupPointer        r3, 3         r3 = ST[3] -> <#%alloc-array>
            0004   0x001A48   4A 04 04 00   LoadStaticU64Imm     r4, 4         r4 = ST[4] -> <single-frame>
            0005   0x001A50   0C 05 10 00   LoadU16Imm           r5, 16        r5 = 16
            0006   0x001A58   0C 06 04 00   LoadU16Imm           r6, 4         r6 = 4
            0007   0x001A60   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0008   0x001A68   43 31 04 00   Move                 r49, r4       r49 = single-frame
            0009   0x001A70   43 32 05 00   Move                 r50, r5       r50 = 16
            000A   0x001A78   43 33 06 00   Move                 r51, r6       r51 = 4
            000B   0x001A80   43 34 07 00   Move                 r52, r7       r52 = 1
            000C   0x001A88   1C 03 03 04   CallFf               r3, r3, 4     r3 = #%alloc-array(single-frame, 16, 4, 1)
            000D   0x001A90   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            000E   0x001A98   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            000F   0x001AA0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0010   0x001AA8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0011   0x001AB0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0012   0x001AB8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0013   0x001AC0   0C 05 0A 00   LoadU16Imm           r5, 10        r5 = 10
            0014   0x001AC8   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 65535] = 10
            0015   0x001AD0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0016   0x001AD8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0017   0x001AE0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0018   0x001AE8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0019   0x001AF0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            001A   0x001AF8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            001B   0x001B00   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            001C   0x001B08   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            001D   0x001B10   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = 0
            001E   0x001B18   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            001F   0x001B20   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0020   0x001B28   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0021   0x001B30   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0022   0x001B38   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0023   0x001B40   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0024   0x001B48   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            0025   0x001B50   15 05 05 00   LookupPointer        r5, 5         r5 = ST[5] -> <get-bound-frame>
            0026   0x001B58   4A 06 06 00   LoadStaticU64Imm     r6, 6         r6 = ST[6] -> <adjusted-ap>
            0027   0x001B60   4A 07 07 00   LoadStaticU64Imm     r7, 7         r7 = ST[7] -> <self>
            0028   0x001B68   43 31 06 00   Move                 r49, r6       r49 = adjusted-ap
            0029   0x001B70   43 32 07 00   Move                 r50, r7       r50 = self
            002A   0x001B78   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-bound-frame(adjusted-ap, self)
            002B   0x001B80   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = RET_get-bound-frame
            002C   0x001B88   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            002D   0x001B90   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            002E   0x001B98   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            002F   0x001BA0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0030   0x001BA8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0031   0x001BB0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0032   0x001BB8   0C 05 1C 00   LoadU16Imm           r5, 28        r5 = 28
            0033   0x001BC0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 28
            0034   0x001BC8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0035   0x001BD0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0036   0x001BD8   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0037   0x001BE0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0038   0x001BE8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0039   0x001BF0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003A   0x001BF8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            003B   0x001C00   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            003C   0x001C08   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            003D   0x001C10   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            003E   0x001C18   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003F   0x001C20   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0040   0x001C28   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0041   0x001C30   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0042   0x001C38   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0043   0x001C40   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0044   0x001C48   40 05 08 00   LoadStaticFloatImm   r5, 8         r5 = ST[8] -> <0.500000>
            0045   0x001C50   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 0.500000
            0046   0x001C58   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0047   0x001C60   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0048   0x001C68   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0049   0x001C70   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            004A   0x001C78   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            004B   0x001C80   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            004C   0x001C88   0C 05 1E 00   LoadU16Imm           r5, 30        r5 = 30
            004D   0x001C90   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 30
            004E   0x001C98   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            004F   0x001CA0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0050   0x001CA8   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0051   0x001CB0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0052   0x001CB8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            0053   0x001CC0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0054   0x001CC8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0055   0x001CD0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0056   0x001CD8   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            0057   0x001CE0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0058   0x001CE8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0059   0x001CF0   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            005A   0x001CF8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            005B   0x001D00   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            005C   0x001D08   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            005D   0x001D10   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            005E   0x001D18   40 05 09 00   LoadStaticFloatImm   r5, 9         r5 = ST[9] -> <5.000000>
            005F   0x001D20   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 5.000000
            0060   0x001D28   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0061   0x001D30   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0062   0x001D38   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            0063   0x001D40   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0064   0x001D48   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            0065   0x001D50   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0066   0x001D58   0C 05 1B 00   LoadU16Imm           r5, 27        r5 = 27
            0067   0x001D60   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 27
            0068   0x001D68   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0069   0x001D70   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006A   0x001D78   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            006B   0x001D80   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            006C   0x001D88   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            006D   0x001D90   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006E   0x001D98   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            006F   0x001DA0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0070   0x001DA8   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            0071   0x001DB0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0072   0x001DB8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0073   0x001DC0   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            0074   0x001DC8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0075   0x001DD0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            0076   0x001DD8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0077   0x001DE0   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0078   0x001DE8   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0079   0x001DF0   53 04 04 05   StoreU8              r4, [r4], r5  r4, *(u8*)[RET_#%alloc-array + 8] = 2
            007A   0x001DF8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            007B   0x001E00   43 03 04 00   Move                 r3, r4        r3 = RET_#%alloc-array
            007C   0x001E08   43 31 01 00   Move                 r49, r1       r49 = player
            007D   0x001E10   43 32 02 00   Move                 r50, r2       r50 = ellie=cin-flo-see-boat=010
            007E   0x001E18   43 33 03 00   Move                 r51, r3       r51 = RET_#%alloc-array
            007F   0x001E20   1C 00 00 03   CallFf               r0, r0, 3     r0 = animate_(player, ellie=cin-flo-see-boat=010, RET_#%alloc-array)
            0080   0x001E28   00 00 00 00   Return               r0            Return 
          }
          lambda cine-start-on-progression@start@main@3 {
            0000   0x0017E8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <camera-enable-animated>
            0001   0x0017F0   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <4.000000>
            0002   0x0017F8   40 02 02 00   LoadStaticFloatImm   r2, 2         r2 = ST[2] -> <-1.000000>
            0003   0x001800   0C 03 01 00   LoadU16Imm           r3, 1         r3 = 1
            0004   0x001808   0C 04 E8 03   LoadU16Imm           r4, 1000      r4 = 1000
            0005   0x001810   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0006   0x001818   0C 06 00 00   LoadU16Imm           r6, 0         r6 = 0
            0007   0x001820   0C 07 00 00   LoadU16Imm           r7, 0         r7 = 0
            0008   0x001828   43 31 01 00   Move                 r49, r1       r49 = 4.000000
            0009   0x001830   43 32 02 00   Move                 r50, r2       r50 = -1.000000
            000A   0x001838   43 33 03 00   Move                 r51, r3       r51 = 1
            000B   0x001840   43 34 04 00   Move                 r52, r4       r52 = 1000
            000C   0x001848   43 35 05 00   Move                 r53, r5       r53 = 0
            000D   0x001850   43 36 06 00   Move                 r54, r6       r54 = 0
            000E   0x001858   43 37 07 00   Move                 r55, r7       r55 = 0
            000F   0x001860   1C 00 00 07   CallFf               r0, r0, 7     r0 = camera-enable-animated(4.000000, -1.000000, 1, 1000, 0, 0, 0)
            0010   0x001868   00 00 00 00   Return               r0            Return 
          }
          lambda cine-start-on-progression@start@main@4 {
            0000   0x002848   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x002850   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <play-cine>
            0002   0x002858   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x002860   43 31 01 00   Move                 r49, r1       r49 = play-cine
            0004   0x002868   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x002870   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(play-cine, 1)
            0006   0x002878   00 00 00 00   Return               r0            Return 
          }
        }
      }
    }
    state play-cine {
      block start {
        track player-anim {
          lambda play-cine@start@player-anim@0 {
            0000   0x002890   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-animate_>
            0001   0x002898   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <player>
            0002   0x0028A0   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <ellie=cin-flo-see-boat>
            0003   0x0028A8   15 03 03 00   LookupPointer        r3, 3         r3 = ST[3] -> <#%alloc-array>
            0004   0x0028B0   4A 04 04 00   LoadStaticU64Imm     r4, 4         r4 = ST[4] -> <single-frame>
            0005   0x0028B8   0C 05 10 00   LoadU16Imm           r5, 16        r5 = 16
            0006   0x0028C0   0C 06 04 00   LoadU16Imm           r6, 4         r6 = 4
            0007   0x0028C8   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0008   0x0028D0   43 31 04 00   Move                 r49, r4       r49 = single-frame
            0009   0x0028D8   43 32 05 00   Move                 r50, r5       r50 = 16
            000A   0x0028E0   43 33 06 00   Move                 r51, r6       r51 = 4
            000B   0x0028E8   43 34 07 00   Move                 r52, r7       r52 = 1
            000C   0x0028F0   1C 03 03 04   CallFf               r3, r3, 4     r3 = #%alloc-array(single-frame, 16, 4, 1)
            000D   0x0028F8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            000E   0x002900   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            000F   0x002908   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0010   0x002910   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0011   0x002918   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0012   0x002920   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0013   0x002928   0C 05 0A 00   LoadU16Imm           r5, 10        r5 = 10
            0014   0x002930   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 65535] = 10
            0015   0x002938   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0016   0x002940   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0017   0x002948   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0018   0x002950   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0019   0x002958   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            001A   0x002960   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            001B   0x002968   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            001C   0x002970   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            001D   0x002978   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = 0
            001E   0x002980   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            001F   0x002988   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0020   0x002990   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0021   0x002998   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0022   0x0029A0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0023   0x0029A8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0024   0x0029B0   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            0025   0x0029B8   15 05 05 00   LookupPointer        r5, 5         r5 = ST[5] -> <get-spawner-locator>
            0026   0x0029C0   4A 06 06 00   LoadStaticU64Imm     r6, 6         r6 = ST[6] -> <cin-flo-see-boat-1>
            0027   0x0029C8   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0028   0x0029D0   43 31 06 00   Move                 r49, r6       r49 = cin-flo-see-boat-1
            0029   0x0029D8   43 32 07 00   Move                 r50, r7       r50 = 1
            002A   0x0029E0   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-spawner-locator(cin-flo-see-boat-1, 1)
            002B   0x0029E8   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = RET_get-spawner-locator
            002C   0x0029F0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            002D   0x0029F8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            002E   0x002A00   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            002F   0x002A08   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0030   0x002A10   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0031   0x002A18   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0032   0x002A20   0C 05 1C 00   LoadU16Imm           r5, 28        r5 = 28
            0033   0x002A28   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 28
            0034   0x002A30   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0035   0x002A38   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0036   0x002A40   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0037   0x002A48   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0038   0x002A50   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0039   0x002A58   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003A   0x002A60   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            003B   0x002A68   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            003C   0x002A70   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            003D   0x002A78   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            003E   0x002A80   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003F   0x002A88   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0040   0x002A90   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0041   0x002A98   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0042   0x002AA0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0043   0x002AA8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0044   0x002AB0   15 05 07 00   LookupPointer        r5, 7         r5 = ST[7] -> <get-boolean>
            0045   0x002AB8   4A 06 08 00   LoadStaticU64Imm     r6, 8         r6 = ST[8] -> <tasked-in?>
            0046   0x002AC0   4A 07 09 00   LoadStaticU64Imm     r7, 9         r7 = ST[9] -> <self>
            0047   0x002AC8   43 31 06 00   Move                 r49, r6       r49 = tasked-in?
            0048   0x002AD0   43 32 07 00   Move                 r50, r7       r50 = self
            0049   0x002AD8   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-boolean(tasked-in?, self)
            004A   0x002AE0   2F 4D 05 00   BranchIfNot          r5, 0x4D      IF NOT r5 
            004B   0x002AE8   40 05 0A 00   LoadStaticFloatImm   r5, 10        r5 = ST[10] -> <0.000000>
            004C   0x002AF0   2D 4E 00 00   Branch               0x4E          GOTO 
            004D   0x002AF8   40 05 0B 00   LoadStaticFloatImm   r5, 11        r5 = ST[11] -> <5.000000>
            004E   0x002B00   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 5.000000
            004F   0x002B08   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0050   0x002B10   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0051   0x002B18   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0052   0x002B20   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0053   0x002B28   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            0054   0x002B30   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0055   0x002B38   0C 05 1E 00   LoadU16Imm           r5, 30        r5 = 30
            0056   0x002B40   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 30
            0057   0x002B48   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0058   0x002B50   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0059   0x002B58   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            005A   0x002B60   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            005B   0x002B68   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            005C   0x002B70   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            005D   0x002B78   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            005E   0x002B80   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            005F   0x002B88   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            0060   0x002B90   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0061   0x002B98   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0062   0x002BA0   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0063   0x002BA8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0064   0x002BB0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            0065   0x002BB8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0066   0x002BC0   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0067   0x002BC8   40 05 0C 00   LoadStaticFloatImm   r5, 12        r5 = ST[12] -> <1.000000>
            0068   0x002BD0   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 1.000000
            0069   0x002BD8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            006A   0x002BE0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006B   0x002BE8   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            006C   0x002BF0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            006D   0x002BF8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            006E   0x002C00   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006F   0x002C08   0C 05 47 00   LoadU16Imm           r5, 71        r5 = 71
            0070   0x002C10   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 71
            0071   0x002C18   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0072   0x002C20   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0073   0x002C28   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            0074   0x002C30   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0075   0x002C38   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            0076   0x002C40   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0077   0x002C48   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0078   0x002C50   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0079   0x002C58   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            007A   0x002C60   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            007B   0x002C68   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            007C   0x002C70   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            007D   0x002C78   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            007E   0x002C80   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            007F   0x002C88   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0080   0x002C90   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0081   0x002C98   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0082   0x002CA0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 8] = 1
            0083   0x002CA8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0084   0x002CB0   43 03 04 00   Move                 r3, r4        r3 = RET_#%alloc-array
            0085   0x002CB8   43 31 01 00   Move                 r49, r1       r49 = player
            0086   0x002CC0   43 32 02 00   Move                 r50, r2       r50 = ellie=cin-flo-see-boat
            0087   0x002CC8   43 33 03 00   Move                 r51, r3       r51 = RET_#%alloc-array
            0088   0x002CD0   1C 00 00 03   CallFf               r0, r0, 3     r0 = wait-animate_(player, ellie=cin-flo-see-boat, RET_#%alloc-array)
            0089   0x002CD8   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@player-anim@1 {
            0000   0x002EC0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <camera-fade-out-auto-gen-animated>
            0001   0x002EC8   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <3.000000>
            0002   0x002ED0   40 02 02 00   LoadStaticFloatImm   r2, 2         r2 = ST[2] -> <5.000000>
            0003   0x002ED8   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <*camera-remap-medium-shot*>
            0004   0x002EE0   43 31 01 00   Move                 r49, r1       r49 = 3.000000
            0005   0x002EE8   43 32 02 00   Move                 r50, r2       r50 = 5.000000
            0006   0x002EF0   43 33 03 00   Move                 r51, r3       r51 = *camera-remap-medium-shot*
            0007   0x002EF8   1B 00 00 03   Call                 r0, r0, 3     r0 = camera-fade-out-auto-gen-animated(3.000000, 5.000000, *camera-remap-medium-shot*)
            0008   0x002F00   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@player-anim@2 {
            0000   0x002768   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <task-complete!>
            0001   0x002770   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <flooded-city>
            0002   0x002778   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <flo-see-boat>
            0003   0x002780   43 31 01 00   Move                 r49, r1       r49 = flooded-city
            0004   0x002788   43 32 02 00   Move                 r50, r2       r50 = flo-see-boat
            0005   0x002790   1B 00 00 02   Call                 r0, r0, 2     r0 = task-complete!(flooded-city, flo-see-boat)
            0006   0x002798   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@player-anim@3 {
            0000   0x0026E8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-for>
            0001   0x0026F0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <jesse-done>
            0002   0x0026F8   43 31 01 00   Move                 r49, r1       r49 = jesse-done
            0003   0x002700   1C 00 00 01   CallFf               r0, r0, 1     r0 = wait-for(jesse-done)
            0004   0x002708   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@player-anim@4 {
            0000   0x0027B8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <update-all-spec-cubemaps>
            0001   0x0027C0   1C 00 00 00   CallFf               r0, r0, 0     r0 = update-all-spec-cubemaps()
            0002   0x0027C8   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@player-anim@5 {
            0000   0x0032D0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <go>
            0001   0x0032D8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <complete>
            0002   0x0032E0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x0032E8   43 31 01 00   Move                 r49, r1       r49 = complete
            0004   0x0032F0   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x0032F8   1C 00 00 02   CallFf               r0, r0, 2     r0 = go(complete, 1)
            0006   0x003300   00 00 00 00   Return               r0            Return 
          }
        }
        track jesse-anim {
          lambda play-cine@start@jesse-anim@0 {
            0000   0x002108   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-animate_>
            0001   0x002110   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <jesse>
            0002   0x002118   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <jesse=cin-flo-see-boat>
            0003   0x002120   15 03 03 00   LookupPointer        r3, 3         r3 = ST[3] -> <#%alloc-array>
            0004   0x002128   4A 04 04 00   LoadStaticU64Imm     r4, 4         r4 = ST[4] -> <single-frame>
            0005   0x002130   0C 05 10 00   LoadU16Imm           r5, 16        r5 = 16
            0006   0x002138   0C 06 05 00   LoadU16Imm           r6, 5         r6 = 5
            0007   0x002140   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0008   0x002148   43 31 04 00   Move                 r49, r4       r49 = single-frame
            0009   0x002150   43 32 05 00   Move                 r50, r5       r50 = 16
            000A   0x002158   43 33 06 00   Move                 r51, r6       r51 = 5
            000B   0x002160   43 34 07 00   Move                 r52, r7       r52 = 1
            000C   0x002168   1C 03 03 04   CallFf               r3, r3, 4     r3 = #%alloc-array(single-frame, 16, 5, 1)
            000D   0x002170   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            000E   0x002178   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            000F   0x002180   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0010   0x002188   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0011   0x002190   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0012   0x002198   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0013   0x0021A0   0C 05 0A 00   LoadU16Imm           r5, 10        r5 = 10
            0014   0x0021A8   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 65535] = 10
            0015   0x0021B0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0016   0x0021B8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0017   0x0021C0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0018   0x0021C8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0019   0x0021D0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            001A   0x0021D8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            001B   0x0021E0   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            001C   0x0021E8   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            001D   0x0021F0   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = 0
            001E   0x0021F8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            001F   0x002200   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0020   0x002208   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0021   0x002210   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0022   0x002218   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 0
            0023   0x002220   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 65535]
            0024   0x002228   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 65535] + 8 -> <[RET_#%alloc-array + 7]>
            0025   0x002230   15 05 05 00   LookupPointer        r5, 5         r5 = ST[5] -> <get-spawner-locator>
            0026   0x002238   4A 06 06 00   LoadStaticU64Imm     r6, 6         r6 = ST[6] -> <cin-flo-see-boat-1>
            0027   0x002240   0C 07 01 00   LoadU16Imm           r7, 1         r7 = 1
            0028   0x002248   43 31 06 00   Move                 r49, r6       r49 = cin-flo-see-boat-1
            0029   0x002250   43 32 07 00   Move                 r50, r7       r50 = 1
            002A   0x002258   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-spawner-locator(cin-flo-see-boat-1, 1)
            002B   0x002260   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 7] = RET_get-spawner-locator
            002C   0x002268   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            002D   0x002270   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            002E   0x002278   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            002F   0x002280   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0030   0x002288   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0031   0x002290   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0032   0x002298   0C 05 1C 00   LoadU16Imm           r5, 28        r5 = 28
            0033   0x0022A0   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 28
            0034   0x0022A8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0035   0x0022B0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0036   0x0022B8   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0037   0x0022C0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0038   0x0022C8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0039   0x0022D0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003A   0x0022D8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            003B   0x0022E0   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            003C   0x0022E8   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            003D   0x0022F0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            003E   0x0022F8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            003F   0x002300   0C 05 01 00   LoadU16Imm           r5, 1         r5 = 1
            0040   0x002308   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0041   0x002310   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 1
            0042   0x002318   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0043   0x002320   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0044   0x002328   15 05 07 00   LookupPointer        r5, 7         r5 = ST[7] -> <get-boolean>
            0045   0x002330   4A 06 08 00   LoadStaticU64Imm     r6, 8         r6 = ST[8] -> <tasked-in?>
            0046   0x002338   4A 07 09 00   LoadStaticU64Imm     r7, 9         r7 = ST[9] -> <self>
            0047   0x002340   43 31 06 00   Move                 r49, r6       r49 = tasked-in?
            0048   0x002348   43 32 07 00   Move                 r50, r7       r50 = self
            0049   0x002350   1C 05 05 02   CallFf               r5, r5, 2     r5 = get-boolean(tasked-in?, self)
            004A   0x002358   2F 4D 05 00   BranchIfNot          r5, 0x4D      IF NOT r5 
            004B   0x002360   40 05 0A 00   LoadStaticFloatImm   r5, 10        r5 = ST[10] -> <0.000000>
            004C   0x002368   2D 4E 00 00   Branch               0x4E          GOTO 
            004D   0x002370   40 05 0B 00   LoadStaticFloatImm   r5, 11        r5 = ST[11] -> <0.800000>
            004E   0x002378   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 0.800000
            004F   0x002380   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0050   0x002388   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0051   0x002390   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0052   0x002398   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0053   0x0023A0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            0054   0x0023A8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0055   0x0023B0   0C 05 1E 00   LoadU16Imm           r5, 30        r5 = 30
            0056   0x0023B8   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 30
            0057   0x0023C0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0058   0x0023C8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0059   0x0023D0   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            005A   0x0023D8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            005B   0x0023E0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            005C   0x0023E8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            005D   0x0023F0   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            005E   0x0023F8   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            005F   0x002400   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            0060   0x002408   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0061   0x002410   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0062   0x002418   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            0063   0x002420   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0064   0x002428   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 2
            0065   0x002430   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0066   0x002438   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0067   0x002440   40 05 0C 00   LoadStaticFloatImm   r5, 12        r5 = ST[12] -> <0.600000>
            0068   0x002448   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 0.600000
            0069   0x002450   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            006A   0x002458   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006B   0x002460   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            006C   0x002468   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            006D   0x002470   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            006E   0x002478   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            006F   0x002480   0C 05 14 00   LoadU16Imm           r5, 20        r5 = 20
            0070   0x002488   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 20
            0071   0x002490   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0072   0x002498   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0073   0x0024A0   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            0074   0x0024A8   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0075   0x0024B0   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            0076   0x0024B8   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0077   0x0024C0   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0078   0x0024C8   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0079   0x0024D0   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            007A   0x0024D8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            007B   0x0024E0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            007C   0x0024E8   0C 05 03 00   LoadU16Imm           r5, 3         r5 = 3
            007D   0x0024F0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            007E   0x0024F8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 3
            007F   0x002500   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0080   0x002508   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0081   0x002510   40 05 0D 00   LoadStaticFloatImm   r5, 13        r5 = ST[13] -> <1075.000000>
            0082   0x002518   11 04 04 05   StoreFloat           r4, [r4], r5  r4, *(f32*)[RET_#%alloc-array + 8] = 1075.000000
            0083   0x002520   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0084   0x002528   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0085   0x002530   0C 05 04 00   LoadU16Imm           r5, 4         r5 = 4
            0086   0x002538   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0087   0x002540   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 4
            0088   0x002548   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0089   0x002550   0C 05 18 00   LoadU16Imm           r5, 24        r5 = 24
            008A   0x002558   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 0] = 24
            008B   0x002560   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            008C   0x002568   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            008D   0x002570   0C 05 04 00   LoadU16Imm           r5, 4         r5 = 4
            008E   0x002578   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            008F   0x002580   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 4
            0090   0x002588   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0091   0x002590   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            0092   0x002598   0C 05 00 00   LoadU16Imm           r5, 0         r5 = 0
            0093   0x0025A0   12 04 04 05   StorePointer         r4, [r4], r5  r4, *(p64*)[RET_#%alloc-array + 8] = 0
            0094   0x0025A8   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            0095   0x0025B0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            0096   0x0025B8   0C 05 04 00   LoadU16Imm           r5, 4         r5 = 4
            0097   0x0025C0   3D 05 05 08   IMulImm              r5, r5, 8     r5 = r5 * 8
            0098   0x0025C8   01 04 04 05   IAdd                 r4, r4, r5    r4 = [RET_#%alloc-array + 0] + 4
            0099   0x0025D0   0F 04 04 00   LoadPointer          r4, [r4]      r4 = *(p64*)[RET_#%alloc-array + 0]
            009A   0x0025D8   3B 04 04 08   IAddImm              r4, r4, 8     r4 = [RET_#%alloc-array + 0] + 8 -> <[RET_#%alloc-array + 8]>
            009B   0x0025E0   0C 05 02 00   LoadU16Imm           r5, 2         r5 = 2
            009C   0x0025E8   56 04 04 05   StoreI32             r4, [r4], r5  r4, *(i32*)[RET_#%alloc-array + 8] = 2
            009D   0x0025F0   43 04 03 00   Move                 r4, r3        r4 = RET_#%alloc-array
            009E   0x0025F8   43 03 04 00   Move                 r3, r4        r3 = RET_#%alloc-array
            009F   0x002600   43 31 01 00   Move                 r49, r1       r49 = jesse
            00A0   0x002608   43 32 02 00   Move                 r50, r2       r50 = jesse=cin-flo-see-boat
            00A1   0x002610   43 33 03 00   Move                 r51, r3       r51 = RET_#%alloc-array
            00A2   0x002618   1C 00 00 03   CallFf               r0, r0, 3     r0 = wait-animate_(jesse, jesse=cin-flo-see-boat, RET_#%alloc-array)
            00A3   0x002620   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@jesse-anim@1 {
            0000   0x0027D8   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <send-event>
            0001   0x0027E0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <jesse-left-cinematic>
            0002   0x0027E8   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <ss-flo-get-boat-mall-entrance-1>
            0003   0x0027F0   43 31 01 00   Move                 r49, r1       r49 = jesse-left-cinematic
            0004   0x0027F8   43 32 02 00   Move                 r50, r2       r50 = ss-flo-get-boat-mall-entrance-1
            0005   0x002800   1C 00 00 02   CallFf               r0, r0, 2     r0 = send-event(jesse-left-cinematic, ss-flo-get-boat-mall-entrance-1)
            0006   0x002808   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@jesse-anim@2 {
            0000   0x001758   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <signal>
            0001   0x001760   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <jesse-done>
            0002   0x001768   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0003   0x001770   43 31 01 00   Move                 r49, r1       r49 = jesse-done
            0004   0x001778   43 32 02 00   Move                 r50, r2       r50 = 0
            0005   0x001780   1C 00 00 02   CallFf               r0, r0, 2     r0 = signal(jesse-done, 0)
            0006   0x001788   00 00 00 00   Return               r0            Return 
          }
        }
        track jesse-visibility {
          lambda play-cine@start@jesse-visibility@0 {
            0000   0x001690   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <npc-on-screen?>
            0001   0x001698   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <jesse>
            0002   0x0016A0   40 02 02 00   LoadStaticFloatImm   r2, 2         r2 = ST[2] -> <0.000000>
            0003   0x0016A8   43 31 01 00   Move                 r49, r1       r49 = jesse
            0004   0x0016B0   43 32 02 00   Move                 r50, r2       r50 = 0.000000
            0005   0x0016B8   1B 00 00 02   Call                 r0, r0, 2     r0 = npc-on-screen?(jesse, 0.000000)
            0006   0x0016C0   2F 0D 00 00   BranchIfNot          r0, 0x11      IF NOT r0 
            0007   0x0016C8   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <cinematic-get-current-maya-frame>
            0008   0x0016D0   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <cin-flo-see-boat>
            0009   0x0016D8   43 31 01 00   Move                 r49, r1       r49 = cin-flo-see-boat
            000A   0x0016E0   1C 00 00 01   CallFf               r0, r0, 1     r0 = cinematic-get-current-maya-frame(cin-flo-see-boat)
            000B   0x0016E8   40 01 05 00   LoadStaticFloatImm   r1, 5         r1 = ST[5] -> <100.000000>
            000C   0x0016F0   25 00 00 01   FLessThan            r0, r0, r1    r0 = r0 < r1
            000D   0x0016F8   2F 11 00 00   BranchIfNot          r0, 0x11      IF NOT r0 
            000E   0x001700   15 00 06 00   LookupPointer        r0, 6         r0 = ST[6] -> <wait-one-frame>
            000F   0x001708   1C 00 00 00   CallFf               r0, r0, 0     r0 = wait-one-frame()
            0010   0x001710   2D 00 00 00   Branch               0x0           GOTO 
            0011   0x001718   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@jesse-visibility@1 {
            0000   0x002720   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <set-visible>
            0001   0x002728   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <jesse>
            0002   0x002730   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0003   0x002738   43 31 01 00   Move                 r49, r1       r49 = jesse
            0004   0x002740   43 32 02 00   Move                 r50, r2       r50 = 0
            0005   0x002748   1C 00 00 02   CallFf               r0, r0, 2     r0 = set-visible(jesse, 0)
            0006   0x002750   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@jesse-visibility@2 {
            0000   0x0015F0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-until-cin-maya-frame>
            0001   0x0015F8   0C 01 64 00   LoadU16Imm           r1, 100       r1 = 100
            0002   0x001600   1A 01 01 00   CastFloat            r1            r1 = float(r1)
            0003   0x001608   4A 02 01 00   LoadStaticU64Imm     r2, 1         r2 = ST[1] -> <cin-flo-see-boat>
            0004   0x001610   43 31 01 00   Move                 r49, r1       r49 = 0.000000
            0005   0x001618   43 32 02 00   Move                 r50, r2       r50 = cin-flo-see-boat
            0006   0x001620   1B 00 00 02   Call                 r0, r0, 2     r0 = wait-until-cin-maya-frame(0.000000, cin-flo-see-boat)
            0007   0x001628   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@jesse-visibility@3 {
            0000   0x0017A0   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <set-visible>
            0001   0x0017A8   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <jesse>
            0002   0x0017B0   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x0017B8   43 31 01 00   Move                 r49, r1       r49 = jesse
            0004   0x0017C0   43 32 02 00   Move                 r50, r2       r50 = 1
            0005   0x0017C8   1C 00 00 02   CallFf               r0, r0, 2     r0 = set-visible(jesse, 1)
            0006   0x0017D0   00 00 00 00   Return               r0            Return 
          }
        }
        track lightning {
          lambda play-cine@start@lightning@0 {
            0000   0x002F28   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <set-boolean>
            0001   0x002F30   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <block-normal-lightning-flash?>
            0002   0x002F38   0C 02 01 00   LoadU16Imm           r2, 1         r2 = 1
            0003   0x002F40   4A 03 02 00   LoadStaticU64Imm     r3, 2         r3 = ST[2] -> <ss-flo-lightning-flash-manager-1>
            0004   0x002F48   43 31 01 00   Move                 r49, r1       r49 = block-normal-lightning-flash?
            0005   0x002F50   43 32 02 00   Move                 r50, r2       r50 = 1
            0006   0x002F58   43 33 03 00   Move                 r51, r3       r51 = ss-flo-lightning-flash-manager-1
            0007   0x002F60   1C 00 00 03   CallFf               r0, r0, 3     r0 = set-boolean(block-normal-lightning-flash?, 1, ss-flo-lightning-flash-manager-1)
            0008   0x002F68   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@lightning@1 {
            0000   0x001640   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <wait-until-cin-maya-frame>
            0001   0x001648   40 01 01 00   LoadStaticFloatImm   r1, 1         r1 = ST[1] -> <170.000000>
            0002   0x001650   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <cin-flo-see-boat>
            0003   0x001658   43 31 01 00   Move                 r49, r1       r49 = 170.000000
            0004   0x001660   43 32 02 00   Move                 r50, r2       r50 = cin-flo-see-boat
            0005   0x001668   1B 00 00 02   Call                 r0, r0, 2     r0 = wait-until-cin-maya-frame(170.000000, cin-flo-see-boat)
            0006   0x001670   00 00 00 00   Return               r0            Return 
          }
          lambda play-cine@start@lightning@2 {
            0000   0x002698   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <send-event>
            0001   0x0026A0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <force-lightning-flash>
            0002   0x0026A8   4A 02 02 00   LoadStaticU64Imm     r2, 2         r2 = ST[2] -> <ss-flo-lightning-flash-manager-1>
            0003   0x0026B0   43 31 01 00   Move                 r49, r1       r49 = force-lightning-flash
            0004   0x0026B8   43 32 02 00   Move                 r50, r2       r50 = ss-flo-lightning-flash-manager-1
            0005   0x0026C0   1C 00 00 02   CallFf               r0, r0, 2     r0 = send-event(force-lightning-flash, ss-flo-lightning-flash-manager-1)
            0006   0x0026C8   00 00 00 00   Return               r0            Return 
          }
        }
        track haptics {
          lambda play-cine@start@haptics@0 {
            0000   0x001498   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <joypad-has-haptics?>
            0001   0x0014A0   0C 01 02 00   LoadU16Imm           r1, 2         r1 = 2
            0002   0x0014A8   43 31 01 00   Move                 r49, r1       r49 = 2
            0003   0x0014B0   1C 00 00 01   CallFf               r0, r0, 1     r0 = joypad-has-haptics?(2)
            0004   0x0014B8   2F 22 00 00   BranchIfNot          r0, 0x22      IF NOT r0 
            0005   0x0014C0   15 00 01 00   LookupPointer        r0, 1         r0 = ST[1] -> <wait-until-cin-frame>
            0006   0x0014C8   40 01 02 00   LoadStaticFloatImm   r1, 2         r1 = ST[2] -> <28.000000>
            0007   0x0014D0   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0008   0x0014D8   43 31 01 00   Move                 r49, r1       r49 = 28.000000
            0009   0x0014E0   43 32 02 00   Move                 r50, r2       r50 = 0
            000A   0x0014E8   1B 00 00 02   Call                 r0, r0, 2     r0 = wait-until-cin-frame(28.000000, 0)
            000B   0x0014F0   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <play-hfx-id>
            000C   0x0014F8   4A 01 04 00   LoadStaticU64Imm     r1, 4         r1 = ST[4] -> <clamber-foot-light-haptic>
            000D   0x001500   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            000E   0x001508   0C 03 02 00   LoadU16Imm           r3, 2         r3 = 2
            000F   0x001510   43 31 01 00   Move                 r49, r1       r49 = clamber-foot-light-haptic
            0010   0x001518   43 32 02 00   Move                 r50, r2       r50 = 0
            0011   0x001520   43 33 03 00   Move                 r51, r3       r51 = 2
            0012   0x001528   1C 00 00 03   CallFf               r0, r0, 3     r0 = play-hfx-id(clamber-foot-light-haptic, 0, 2)
            0013   0x001530   15 00 01 00   LookupPointer        r0, 1         r0 = ST[1] -> <wait-until-cin-frame>
            0014   0x001538   40 01 05 00   LoadStaticFloatImm   r1, 5         r1 = ST[5] -> <105.000000>
            0015   0x001540   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            0016   0x001548   43 31 01 00   Move                 r49, r1       r49 = 105.000000
            0017   0x001550   43 32 02 00   Move                 r50, r2       r50 = 0
            0018   0x001558   1B 00 00 02   Call                 r0, r0, 2     r0 = wait-until-cin-frame(105.000000, 0)
            0019   0x001560   15 00 03 00   LookupPointer        r0, 3         r0 = ST[3] -> <play-hfx-id>
            001A   0x001568   4A 01 06 00   LoadStaticU64Imm     r1, 6         r1 = ST[6] -> <extra-soft-land-rumble-settings>
            001B   0x001570   0C 02 00 00   LoadU16Imm           r2, 0         r2 = 0
            001C   0x001578   0C 03 02 00   LoadU16Imm           r3, 2         r3 = 2
            001D   0x001580   43 31 01 00   Move                 r49, r1       r49 = extra-soft-land-rumble-settings
            001E   0x001588   43 32 02 00   Move                 r50, r2       r50 = 0
            001F   0x001590   43 33 03 00   Move                 r51, r3       r51 = 2
            0020   0x001598   1C 00 00 03   CallFf               r0, r0, 3     r0 = play-hfx-id(extra-soft-land-rumble-settings, 0, 2)
            0021   0x0015A0   2D 23 00 00   Branch               0x23          GOTO 
            0022   0x0015A8   0C 00 00 00   LoadU16Imm           r0, 0         r0 = 0
            0023   0x0015B0   00 00 00 00   Return               r0            Return 
          }
        }
      }
    }
    state complete {
    }
  }
}
