####################################################################################################
#                                                                                                  #
#   generated by dconstruct ver. 1.52.0                                                            #
#   listing for file: game_dumps/t1x/dc1/npc-idle.bin                                              #
#   filesize: 1036 bytes                                                                           #
#   total entries: 1                                                                               #
#   functions: 0                                                                                   #
#   has state script: false                                                                        #
#   game type: t1x                                                                                 #
#   optimizations enabled: false                                                                   #
#                                                                                                  #
####################################################################################################



##############################  ENTRY 0  ##############################

*npc-idle-performances* = map [0x00048] {
  keys: [0x00088], values: [0x00068]

  chloe {
    map [0x000A8] {
      keys: [0x00140], values: [0x00120]

      *chloe-aware* {
        npc-idle-performance-array [0x00218] {
          [0] int: 1
          [1] int: 0
          [2] array [0x220] {size: 1} {
            [0] anonymous struct [0x3d0] {
              [0] sid: aware-idle-performance
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
          }
        }
      }
      *chloe-combat* {
        npc-idle-performance-array [0x00200] {
          [0] int: 1
          [1] int: 0
          [2] array [0x208] {size: 1} {
            [0] anonymous struct [0x2f0] {
              [0] sid: clo-gunout-poses-idle-performance
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
          }
        }
      }
      *chloe-ambient* {
        npc-idle-performance-array [0x001E8] {
          [0] int: 2
          [1] int: 0
          [2] array [0x1f0] {size: 2} {
            [0] anonymous struct [0x298] {
              [0] sid: idle-performance-a
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
            [1] anonymous struct [0x2c0] {
              [0] sid: idle-performance-b
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
          }
        }
      }
    }
  }
  elena {
    map [0x000C8] {
      keys: [0x00180], values: [0x00160]

      *elena-ambient* {
        npc-idle-performance-array [0x001B8] {
          [0] int: 1
          [1] int: 0
          [2] array [0x1c0] {size: 1} {
            [0] anonymous struct [0x260] {
              [0] sid: ef-idle-performance
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
          }
        }
      }
      *elena-aware* {
        npc-idle-performance-array [0x001D0] {
          [0] int: 1
          [1] int: 0
          [2] array [0x1d8] {size: 1} {
            [0] anonymous struct [0x320] {
              [0] sid: ef-gunout-idle-performance
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
          }
        }
      }
      *elena-combat* {
        npc-idle-performance-array [0x001D0] {
          [0] int: 1
          [1] int: 0
          [2] array [0x1d8] {size: 1} {
            [0] anonymous struct [0x320] {
              [0] sid: ef-gunout-idle-performance
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
          }
        }
      }
    }
  }
  sullivan {
    map [0x000E8] {
      keys: [0x001A0], values: [0x00108]

      *sullivan-ambient* {
        npc-idle-performance-array [0x00248] {
          [0] int: 3
          [1] int: 0
          [2] array [0x250] {size: 3} {
            [0] anonymous struct [0x350] {
              [0] sid: idle-performance-b
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
            [1] anonymous struct [0x378] {
              [0] sid: idle-performance-c
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
            [2] anonymous struct [0x3a0] {
              [0] sid: idle-performance-d
              [1] int: 0
              [2] int: 0
              [3] int: 0
              [4] int: 0
              [5] int: 0
              [6] int: 0
              [7] int: 0
              [8] int: 0
            }
          }
        }
      }
      *sullivan-combat* {
        npc-idle-performance-array [0x00230] {
          [0] int: 0
          [1] int: 0
          [2] array [0x238] {size: 0} {
          }
        }
      }
    }
  }
}
