####################################################################################################
#                                                                                                  #
#   generated by dconstruct ver. 1.52.0                                                            #
#   listing for file: .\game_dumps\t2r\dc1\ss-fx\ss-fx-throw-bomb-factions.bin                     #
#   filesize: 2353 bytes                                                                           #
#   total entries: 1                                                                               #
#   functions: 3                                                                                   #
#   has state script: true                                                                         #
#   game type: t2r                                                                                 #
#   optimizations enabled: true                                                                    #
#                                                                                                  #
####################################################################################################



##############################  ENTRY 0  ##############################

ss-fx-throw-bomb-factions = state-script [0x00048] {
  DECLARATIONS: 
    [0x0001D0] bound-frame location             = uninitialized
    [0x000200] int32    upgrade-level        = uninitialized
    [0x000230] symbol   attacker-id          = uninitialized
    [0x000260] int32    attacker-net-id      = uninitialized
    [0x000290] timer    main-timer           = uninitialized
    [0x0004D8] uint64   smoke-handle         = 0
    [0x0004E8] float    scale                = 0.00
    [0x0004F8] float    awaylarge            = 0.00
    [0x000508] float    awaysmall            = 0.00
    [0x000518] float    flare                = 0.00
    [0x000580] vector   color                = (1.00, 1.00, 1.00, 1.00)
    [0x000528] symbol   fire-core            = #0000000000000000
    [0x000538] symbol   fire-bit             = #0000000000000000
    [0x000548] symbol   impact-smoke         = #0000000000000000
    [0x000558] symbol   impact-smoke-snow    = #0000000000000000
    [0x000568] float    radius               = 4.00
    STATE throw-bomb-floor {
      ON start {
      }
      ON event spawn-particles {
        TRACK main {
          {
            0000   0x000720   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <start-timer>
            0001   0x000728   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <main-timer>
            0002   0x000730   40 02 02 00   LoadStaticFloatImm   r2, 2         r2 = ST[2] -> <10.000000>
            0003   0x000738   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <self>
            0004   0x000740   0C 04 01 00   LoadU16Imm           r4, 1         r4 = 1
            0005   0x000748   43 31 01 00   Move                 r49, r1       r49 = main-timer
            0006   0x000750   43 32 02 00   Move                 r50, r2       r50 = 10.000000
            0007   0x000758   43 33 03 00   Move                 r51, r3       r51 = self
            0008   0x000760   43 34 04 00   Move                 r52, r4       r52 = 1
            0009   0x000768   1B 00 00 04   Call                 r0, r0, 4     r0 = start-timer(main-timer, 10.000000, self, 1)
            000A   0x000770   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x000778    function: start-timer
            0001   0x000780    sid: main-timer
            0002   0x000788    float: 10.000000
            0003   0x000790    sid: self
          }
          {
            0000   0x000798   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <spawn-particles-at-bound-frame>
            0001   0x0007A0   4A 01 01 00   LoadStaticU64Imm     r1, 1         r1 = ST[1] -> <trap-bomb>
            0002   0x0007A8   15 02 02 00   LookupPointer        r2, 2         r2 = ST[2] -> <get-bound-frame>
            0003   0x0007B0   4A 03 03 00   LoadStaticU64Imm     r3, 3         r3 = ST[3] -> <location>
            0004   0x0007B8   4A 04 04 00   LoadStaticU64Imm     r4, 4         r4 = ST[4] -> <self>
            0005   0x0007C0   43 31 03 00   Move                 r49, r3       r49 = location
            0006   0x0007C8   43 32 04 00   Move                 r50, r4       r50 = self
            0007   0x0007D0   1C 02 02 02   CallFf               r2, r2, 2     r2 = get-bound-frame(location, self)
            0008   0x0007D8   4A 03 05 00   LoadStaticU64Imm     r3, 5         r3 = ST[5] -> <none>
            0009   0x0007E0   43 31 01 00   Move                 r49, r1       r49 = trap-bomb
            000A   0x0007E8   43 32 02 00   Move                 r50, r2       r50 = RET_get-bound-frame
            000B   0x0007F0   43 33 03 00   Move                 r51, r3       r51 = none
            000C   0x0007F8   1C 00 00 03   CallFf               r0, r0, 3     r0 = spawn-particles-at-bound-frame(trap-bomb, RET_get-bound-frame, none)
            000D   0x000800   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x000808    function: spawn-particles-at-bound-frame
            0001   0x000810    sid: trap-bomb
            0002   0x000818    function: get-bound-frame
            0003   0x000820    sid: location
            0004   0x000828    sid: self
            0005   0x000830    sid: none
          }
        }

      }
      ON event main-timer {
        TRACK main {
          {
            0000   0x000838   15 00 00 00   LookupPointer        r0, 0         r0 = ST[0] -> <terminate>
            0001   0x000840   1C 00 00 00   CallFf               r0, r0, 0     r0 = terminate()
            0002   0x000848   00 00 00 00   Return               r0            Return 

            SYMBOL TABLE: 
            0000   0x000850    function: terminate
          }
        }

      }
    } END STATE throw-bomb-floor

}
